Repository yt-dlp/yt-dlp, pull requests merged in 2021-11, with the labels that each got.

#1541 [iPrima] Fix extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/iprima.py
Labels: pending-fixes

#1505 [Gab] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/gab.py
Labels: pending-review

#1578 [Tokentube] Fix description
  yt_dlp/extractor/tokentube.py
Labels: pending-fixes

#1668 [Stripchat] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/stripchat.py
Labels: NSFW

#1661 [hls] Improve DRM checks
  yt_dlp/downloader/hls.py
  yt_dlp/extractor/common.py
Labels: enhancement

#1686 AbemaTV batch 1/3: [AES] add ECB mode
  test/test_aes.py
  yt_dlp/aes.py
Labels: enhancement

#1681 [VidLii] Add 720p support
  yt_dlp/extractor/vidlii.py
Labels: site-enhancement

#1717 [bbc] Get all available formats, deprioritize audio description
  yt_dlp/extractor/bbc.py
Labels: site-enhancement

#1723 [willow] new extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/willow.py
Labels: site-request

#1593 [radiozet] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/radiozet.py
Labels: site-request, pending-fixes

#1736 Streamff extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/streamff.py
Labels: site-request

#1434 [extractor/breitbart] Breitbart.com website support
  yt_dlp/extractor/breitbart.py
  yt_dlp/extractor/extractors.py
Labels: site-request

#1694 [nebula] Rewrite extractor with channel support / fix #1690 "Unable to extract API key"
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/nebula.py
Labels: extractor-bug

#1799 [xvideos] extractor fix
  yt_dlp/extractor/xvideos.py
Labels: pending-fixes

#1631 [redgifs] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/redgifs.py
Labels: site-request

#1357 [Tvplayhome][tvplay] extractor updates
  yt_dlp/extractor/tvplay.py
Labels: extractor-bug

#1515 Twitch VOD extractor - chapters
  yt_dlp/extractor/twitch.py
Labels: site-enhancement

#1577 [Aljazeera] Fix extractor
  yt_dlp/extractor/aljazeera.py
Labels: site-enhancement

#1435 Senate.gov website downloading fixes
  yt_dlp/extractor/cspan.py
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/senategov.py
  yt_dlp/extractor/senateisvp.py
Labels: site-enhancement

#1808 [RedGifsSearch] Add RedGifs search (and user) extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/redgifs.py
Labels: site-enhancement

#1738 [CleanUp] Clean regexes
  yt_dlp/extractor/amazon.py
  yt_dlp/extractor/canalalpha.py
  yt_dlp/extractor/chingari.py
  yt_dlp/extractor/cozytv.py
  yt_dlp/extractor/epicon.py
  yt_dlp/extractor/euscreen.py
  yt_dlp/extractor/gab.py
  yt_dlp/extractor/gronkh.py
  yt_dlp/extractor/hotstar.py
  yt_dlp/extractor/koo.py
  yt_dlp/extractor/mlssoccer.py
  yt_dlp/extractor/musescore.py
  yt_dlp/extractor/mxplayer.py
  yt_dlp/extractor/onefootball.py
  yt_dlp/extractor/planetmarathi.py
  yt_dlp/extractor/projectveritas.py
  yt_dlp/extractor/shemaroome.py
  yt_dlp/extractor/skynewsau.py
  yt_dlp/extractor/threespeak.py
  yt_dlp/extractor/utreon.py
  yt_dlp/extractor/voot.py
  yt_dlp/extractor/zee5.py
Labels: docs/meta/cleanup

#1716 [Bilibili] Fix extractor
  yt_dlp/extractor/bilibili.py
Labels: extractor-bug
