Repository yt-dlp/yt-dlp, pull requests merged in 2021-09, with the labels that each got.

#844 [XHamster] fix: extract uploader_id
  yt_dlp/extractor/xhamster.py
Labels: do-not-merge

#896 Adding improvements to 9Now to handle episodic series
  yt_dlp/extractor/ninenow.py
Labels: pending-fixes

#913 [ITV] Fix Extractor
  yt_dlp/extractor/itv.py
Labels: geo-blocked, help testing

#973 Add MediaiteIE.
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/mediaite.py
Labels: pending-review

#1001 [itv] Prefer last matching featureset
  yt_dlp/extractor/itv.py
Labels: help testing

#1006 Fix MPD BaseURL handling when root-relative URL
  yt_dlp/extractor/common.py
Labels: pending-fixes

#1012 ATV.at: fix extractor using the new jwt JSON Web Token
  yt_dlp/extractor/atvat.py
  yt_dlp/utils.py
Labels: pending-review

#1038 Add ChingariIE and ChingariUserIE.
  yt_dlp/extractor/chingari.py
  yt_dlp/extractor/extractors.py
Labels: pending-review

#1044 Add KooIE.
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/koo.py
Labels: pending-review

#786 [youtube] misc auth cleanup
  yt_dlp/downloader/youtube_live_chat.py
  yt_dlp/extractor/youtube.py
Labels: pending-review

#1068 Add Theta stream extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/theta.py
Labels: pending-review

#1080 [N1] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/n1.py
Labels: pending-review
