Repository yt-dlp/yt-dlp, pull requests merged in 2021-12, with the labels that each got.

#1904 [ceskatelevize] Update to 2021-12-06 changes (#1899)
  yt_dlp/extractor/ceskatelevize.py
Labels: extractor-bug

#1915 [ntvcojp] fix extractor
  yt_dlp/extractor/ntvcojp.py
Labels: extractor-bug

#1938 [crackle] Always look for non-DRM formats
  yt_dlp/extractor/crackle.py
Labels: extractor-bug

#1916 [skeb] add support for skeb.jp
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/skeb.py
  yt_dlp/utils.py
Labels: site-request

#1913 [CBC Gem] Support 1080p shows
  yt_dlp/extractor/cbc.py
Labels: site-enhancement

#1893 [zdf] add support for videos with different ptmd-template location
  yt_dlp/extractor/zdf.py
Labels: extractor-bug

#1850 gofile Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/gofile.py
Labels: site-request

#1664 [SponsorBlock]: Support for Filler category
  README.md
  test/test_postprocessors.py
  yt_dlp/options.py
  yt_dlp/postprocessor/modify_chapters.py
  yt_dlp/postprocessor/sponsorblock.py
Labels: enhancement

#1929 [TVer/brightcove]added support for higher resolution thumbnail extraction
  yt_dlp/extractor/brightcove.py
Labels: site-enhancement

#1785 [web.archive:youtube] Improve extractor
  README.md
  yt_dlp/extractor/archiveorg.py
Labels: site-enhancement

#1928 Updated fujitv.py on extracting 1080P stream from tv_android m3u8
  yt_dlp/extractor/fujitv.py
Labels: site-enhancement

#1970 [Rutube]Add RutubeChannelIE
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/rutube.py
Labels: site-enhancement

#1950 [NateTV] Add extractor(s)
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/nate.py
Labels: site-request

#1959 [SonyLiv]Add otp login support
  yt_dlp/extractor/sonyliv.py
Labels: site-enhancement

#1972 [ok.ru] add mobile fallback
  yt_dlp/extractor/odnoklassniki.py
Labels: site-enhancement

#1626 [youtube:comments] Add more options for limiting comments extracted and misc cleanup
  README.md
  yt_dlp/extractor/youtube.py
Labels: docs/meta/cleanup, site-enhancement

#2014 [test/download] ignore field webpage_url_domain
  test/helper.py
Labels: docs/meta/cleanup

#1983 [extractor/common] Tweak JSON-LD extraction to support default implicit graph
  test/test_InfoExtractor.py
  yt_dlp/extractor/common.py
Labels: enhancement

#2019 [gronkh] Fix url pattern
  yt_dlp/extractor/gronkh.py
Labels: extractor-bug, pending-fixes

#2003 [docs] improve format of manpage
  README.md
  devscripts/prepare_manpage.py
Labels: docs/meta/cleanup

#2012 Add replacement output template via `&`
  README.md
  test/test_YoutubeDL.py
  yt_dlp/YoutubeDL.py
Labels: enhancement, pending-fixes

#2033 Fix some typos.
  CONTRIBUTING.md
  README.md
  pyinst.py
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/sendtonews.py
  yt_dlp/jsinterp.py
  yt_dlp/options.py
Labels: docs/meta/cleanup

#1000 [soundcloud] Add related tracks extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/soundcloud.py
Labels: pending-review

#1203 [extractor/audiomack] Updated album and song URL regex
  yt_dlp/extractor/audiomack.py
Labels: extractor-bug, pending-review

#1630 [ABC] Add extractor for latest episode of an iView show
  yt_dlp/extractor/abc.py
  yt_dlp/extractor/extractors.py
Labels: pending-review

#1018 [youtube:tab] Extract more metadata for feeds/channels/playlists
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#888 [youtube] download live from the start, to the end
  README.md
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/downloader/__init__.py
  yt_dlp/downloader/dash.py
  yt_dlp/downloader/f4m.py
  yt_dlp/downloader/fragment.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/youtube.py
  yt_dlp/minicurses.py
  yt_dlp/options.py
  yt_dlp/postprocessor/__init__.py
  yt_dlp/postprocessor/common.py
  yt_dlp/postprocessor/ffmpeg.py
  yt_dlp/utils.py
Labels: enhancement, site-enhancement

#1657 [rtve] Add support for audio only
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/rtve.py
Labels: site-enhancement

#2075 [NJPWWorld] use _extract_m3u8_formats
  yt_dlp/extractor/njpwworld.py
Labels: site-enhancement

#2066 Add --fileopen-retries to retry on file access errors.
  README.md
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/downloader/common.py
  yt_dlp/downloader/external.py
  yt_dlp/downloader/fragment.py
  yt_dlp/downloader/http.py
  yt_dlp/options.py
Labels: enhancement

#2062 [LBRY] Add support for live streams.
  yt_dlp/extractor/lbry.py
Labels: site-enhancement

#2050 [RCTIPlusSeries] Properly yield entries + add video type selection
  yt_dlp/extractor/rcti.py
Labels: site-enhancement

#2096 [youtube:tab] Extract video thumbnails from playlist
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#2045 [dropout] Added extractor
  yt_dlp/extractor/dropout.py
  yt_dlp/extractor/extractors.py
Labels: site-request

#1905 [OpenCast] Add extractor
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/opencast.py
  yt_dlp/utils.py
Labels: site-request, pending-review

#2029 [Steam] Fix extractor
  yt_dlp/extractor/steam.py
Labels: extractor-bug

#2036 [GameJolt] Add extractors
  README.md
  yt_dlp/extractor/common.py
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/gamejolt.py
Labels: site-request

#2032 Fixed Gnome keyring support
  README.md
  test/test_cookies.py
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/cookies.py
  yt_dlp/options.py
Labels: bug, enhancement

#2006 [Instagram] Add story/highlight extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/instagram.py
Labels: site-enhancement

#1547 [Drooble] Add extractor
  yt_dlp/extractor/drooble.py
  yt_dlp/extractor/extractors.py
Labels: site-request, pending-fixes

#2116 Add extractor arg for Hotstar to ignore tags
  README.md
  yt_dlp/extractor/hotstar.py
Labels: site-enhancement, pending-fixes
