Repository yt-dlp/yt-dlp, pull requests merged in 2022-07, with the labels that each got.

#4266 Skip some PPs if Remux or VideoConvertor is also queued
  yt_dlp/YoutubeDL.py
Labels: enhancement

#4250 [syvdk] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/syvdk.py
Labels: site-request

#4213 [extractor/mocha] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mocha.py
Labels: site-request

#4325 [theholetv] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/theholetv.py
Labels: site-request, pending-fixes

#4340 Clarify download_ranges
  yt_dlp/YoutubeDL.py
Labels: docs/meta/cleanup

#4334 [extractor/youtube] More parameters for storyboards
  yt_dlp/extractor/common.py
  yt_dlp/extractor/youtube.py
Labels: enhancement, site-enhancement, pending-fixes

#4333 [extractor/cellebrite] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/cellebrite.py
Labels: site-request, pending-fixes

#4339 [extractor/Ximalaya] fix Ximalaya
  yt_dlp/extractor/ximalaya.py
Labels: site-bug, pending-fixes

#4284 [extractor/detik] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/detik.py
Labels: site-request

#4228 [extractor/acfun] add video, bangumi
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/acfun.py
Labels: site-request

#4208 [Trovo] Fix extractor
  yt_dlp/extractor/trovo.py
Labels: site-bug

#4191 [StarTrek] Add extractor for startrek.com videos
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/startrek.py
Labels: site-request

#4222 [extractor/rtl.nl] Add rtl.lu extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/rtlnl.py
Labels: site-request, pending-fixes

#2397 [TubeTuGraz] Add new extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tubetugraz.py
Labels: site-request, pending-fixes

#4357 Allow users to specify encoding in each config files
  README.md
  test/test_utils.py
  yt_dlp/utils.py
Labels: enhancement

#4355 make pyinst.py build name more PEP425 compatible
  pyinst.py
Labels: docs/meta/cleanup

#4268 Fix video id extractor for wsj articles
  yt_dlp/extractor/wsj.py
Labels: site-bug, pending-fixes

#2586 New IE for RTVSLO (rtvslo.si)
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/rtvslo.py
Labels: site-request

#3854 [Netverse] Add extractor
  yt_dlp/extractor/netverse.py
Labels: site-request

#4314 Add support for wikimedia.org
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/wikimedia.py
Labels: site-request

#4330 [wetv] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/wetv.py
Labels: site-request

#4376 [extractor/AbemaTVTitle] Implement paging
  yt_dlp/extractor/abematv.py
Labels: site-enhancement

#4398 [extractor/patreon] Fix and improve extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/patreon.py
Labels: site-enhancement, site-bug

#4380 [rai] Rainews fix #3911
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/rai.py
Labels: site-bug

#4405 Crunchyroll missing thumbnail fix
  yt_dlp/extractor/crunchyroll.py
Labels: site-bug, needs testing

#4186 [Go] Extract original airdate
  yt_dlp/extractor/go.py
Labels: site-enhancement, pending-fixes

#3302 [arte] Move to v2 API
  yt_dlp/extractor/arte.py
Labels: site-enhancement, pending-fixes

#4128 [extractor/vk] fix video extractor
  yt_dlp/extractor/vk.py
Labels: site-bug, pending-fixes

#4472 [bbc] Fix news articles
  yt_dlp/extractor/bbc.py
Labels: site-enhancement

#4461 [extractor/archiveorg] Fix handling of formats
  yt_dlp/extractor/archiveorg.py
  yt_dlp/utils.py
Labels: site-bug

#4384 Fixed incorrect padding issue for cloudflarestream
  yt_dlp/extractor/cloudflarestream.py
Labels: site-bug, pending-fixes

#4491 fix: '@' symbol in url [stripchat]
  yt_dlp/extractor/stripchat.py
Labels: site-bug, pending-fixes

#4453 Extend chapter extraction for single chapter VODs
  yt_dlp/extractor/twitch.py
Labels: site-enhancement, pending-fixes

#4434 Add support for holodex
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/holodex.py
Labels: site-request

#4410 [angel] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/angel.py
Labels: site-request
