Repository yt-dlp/yt-dlp, pull requests merged in 2022-01, with the labels that each got.

#2031 [common] Extract chapters from JSON-LD
  test/test_InfoExtractor.py
  yt_dlp/extractor/common.py
Labels: enhancement

#2163 [youtube:api] Update Innertube clients
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#2229 [gfycat] Support Embeds
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/gfycat.py
Labels: site-enhancement

#2180 [MainStreaming] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/mainstreaming.py
Labels: site-request

#2129 [utils] Improve parsing for nested HTML elements
  test/test_utils.py
  yt_dlp/utils.py
Labels: enhancement

#2000 [callin] Add extractor
  yt_dlp/extractor/callin.py
  yt_dlp/extractor/extractors.py
Labels: site-request

#2069 [youtube:tab] Extract view count, playlist count and last updated for playlists
  README.md
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#2236 [Pornez] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/pornez.py
Labels: site-request, NSFW

#2097 [afreecatv] Add support for livestreams
  yt_dlp/extractor/afreecatv.py
  yt_dlp/extractor/extractors.py
Labels: site-enhancement

#2248 Fix VKUserVideosIE
  yt_dlp/extractor/vk.py
Labels: site-bug

#2251 [veoh] Accept "videos" URLs; prefer HQ format; get additional metadata
  yt_dlp/extractor/veoh.py
Labels: pending-fixes

#2279 [Rule34video] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/rule34video.py
Labels: site-request, pending-fixes

#2293 [noodlemagazine] Add extrator
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/noodlemagazine.py
Labels: site-request, NSFW

#1955 [rai] Raiplaysound support, fixes #1951
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/rai.py
Labels: site-bug, pending-review

#1931 add support for digitalconcerthall.com
  yt_dlp/extractor/common.py
  yt_dlp/extractor/digitalconcerthall.py
  yt_dlp/extractor/extractors.py
Labels: site-request, pending-fixes

#1616 [streamcz] fix extractor
  yt_dlp/extractor/streamcz.py
Labels: site-enhancement

#1975 [yahoo:gyao] Improved playlist handling
  yt_dlp/extractor/yahoo.py
Labels: site-enhancement, pending-fixes

#1979 [extractor/glomex] Add new extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/glomex.py
Labels: site-request

#2331 [PokerGo] Add extractors.
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/pokergo.py
Labels: site-request

#1980 [extractor/megatvcom] Add new extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/megatvcom.py
Labels: site-request

#2379 [daftsex] Add new extractors
  yt_dlp/extractor/daftsex.py
  yt_dlp/extractor/extractors.py
Labels: site-request, NSFW

#2377 [RTNews] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/rtnews.py
Labels: site-request, pending-fixes

#2297 [extractor/tvopengr] Add new extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/tvopengr.py
Labels: site-request

#2323 Adjust regex of Theta stream extractor
  yt_dlp/extractor/theta.py
Labels: site-bug

#2318 [youtube:tab] Raise error on silent tab redirect
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-enhancement, site-bug

#2354 [iq.com] Add extractor
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/iqiyi.py
Labels: site-request

#2185 [TikTok] Extract auto captions
  yt_dlp/extractor/tiktok.py
Labels: site-enhancement, pending-fixes

#2400 [youtube:tab] Extract channel banner
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#2402 [youtube] Enforce UTC and use utcnow() in `datetime_from_str`
  yt_dlp/extractor/youtube.py
  yt_dlp/utils.py
Labels: bug, site-bug

#2399 [youtube] Extract channel subscribers
  README.md
  yt_dlp/extractor/common.py
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#778 [options] Add --legacy-server-connect
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/options.py
  yt_dlp/utils.py
Labels: enhancement

#2245 [PRX] Add Extractors
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/prx.py
Labels: site-request

#2500 [YandexVideoPreview] Add extractor for yandex video preview urls
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/yandexvideo.py
Labels: site-request

#2505 Fujitv premium info extract
  yt_dlp/extractor/fujitv.py
Labels: site-enhancement

#2506 [crunchyroll:beta] Add self-contained support for crunchyroll beta for logged in users
  README.md
  yt_dlp/extractor/crunchyroll.py
Labels: site-bug

#2510 [MySpass] fix video url processing
  yt_dlp/extractor/myspass.py
Labels: site-bug

#1964 [Bilibili] Add 8k support
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement, site-bug

#2540 [viki] Fix "Bad request" error on manifest request
  yt_dlp/extractor/viki.py
Labels: site-bug

#2530 [crunchyroll] Login support
  yt_dlp/extractor/crunchyroll.py
Labels: site-enhancement

#2533 [mildom] Fixes and improvements (should close #2519 )
  yt_dlp/extractor/mildom.py
Labels: site-bug

#2542 [tumblr] Fix 403 errors; handle Vimeo embeds
  yt_dlp/extractor/tumblr.py
Labels: site-bug

#2550 [Pladform] Fix redirection to external player
  yt_dlp/extractor/pladform.py
Labels: site-enhancement, pending-fixes
