Repository yt-dlp/yt-dlp, pull requests merged in 2022-11, with the labels that each got.

#4986 [kaltura] Add support for playlists to Kaltura downloader
  yt_dlp/extractor/kaltura.py
Labels: site-enhancement

#5101 add agora extractors (tokfm, wyborcza)
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/agora.py
  yt_dlp/utils.py
Labels: site-request, hacktoberfest-accepted

#5221 [extractor/genius] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/genius.py
Labels: site-request

#5134 OF.TV extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/oftv.py
Labels: site-request, pending-fixes, hacktoberfest-accepted

#5453 [extractor/twitcasting] Fix `data-movie-playlist` extraction
  yt_dlp/extractor/twitcasting.py
Labels: site-bug

#5435 [lbry] pass authentication token from cookies
  yt_dlp/extractor/lbry.py
Labels: site-enhancement

#5376 [extractor/youtube] Update playlist metadata extraction for new layout
  yt_dlp/extractor/youtube.py
Labels: site-bug

#5388 Add extractors for 2m.ma
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/deuxm.py
Labels: site-request, hacktoberfest-accepted

#5371 [extractor/swearnet] Add SwearnetEpisode Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/swearnet.py
Labels: site-request, hacktoberfest-accepted

#5387 [extractor/epoch] Support videos without data-trailer
  yt_dlp/extractor/epoch.py
  yt_dlp/utils.py
Labels: site-bug, hacktoberfest-accepted

#5352 [RedGifs] Refresh auth token when API returns HTTP 401
  yt_dlp/extractor/redgifs.py
Labels: NSFW, site-bug, hacktoberfest-accepted

#5346 tvp: vod refactor, domain list update, general improvements
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tvp.py
Labels: site-bug, hacktoberfest-accepted

#5329 New extractor for Qingting.fm(蜻蜓FM)
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/qingting.py
Labels: site-request, hacktoberfest-accepted

#5310 [listennotes.com] Add extractor
  yt_dlp/compat/__init__.py
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/listennotes.py
Labels: site-request, hacktoberfest-accepted

#5294 [extractor/crunchyroll] Beta is no longer beta
  README.md
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/crunchyroll.py
Labels: site-bug, hacktoberfest-accepted

#5358 [extractor/telegram] Add playlist support and more metadata
  yt_dlp/extractor/telegram.py
  yt_dlp/utils.py
Labels: site-enhancement

#5445 [extractor/stripchat] Fix hostname for HLS stream
  yt_dlp/extractor/stripchat.py
Labels: NSFW, site-bug, needs-testing

#5309 [movefiles] Work around `PermissionError` on FreeBSD
  yt_dlp/compat/shutil.py
  yt_dlp/postprocessor/movefilesafterdownload.py
Labels: enhancement, hacktoberfest-accepted

#5303 [mxplayer] Improve extractor
  yt_dlp/extractor/mxplayer.py
Labels: site-bug, hacktoberfest-accepted

#5105 [extractor/odnoklassniki] Boosty.to support
  yt_dlp/extractor/odnoklassniki.py
Labels: site-enhancement, pending-fixes, hacktoberfest-accepted

#5475 [extractor/stripchat] fix unbound formats variable
  yt_dlp/extractor/stripchat.py
Labels: NSFW, site-bug

#5465 [camsoda] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/camsoda.py
Labels: site-request, NSFW

#5066 [bitchute] extractor overhaul
  yt_dlp/extractor/bitchute.py
  yt_dlp/utils.py
Labels: site-enhancement

#5439 [extractor/youtube] Improve channel tab handling
  README.md
  test/test_youtube_lists.py
  yt_dlp/extractor/youtube.py
Labels: site-enhancement, site-bug

#5474 [bitchute] raise on restricted videos
  yt_dlp/extractor/bitchute.py
Labels: site-enhancement

#5483 [extractor/unsupported] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/unsupported.py
Labels: enhancement

#5280 [rumble] add HLS formats
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/rumble.py
Labels: site-enhancement, site-bug, pending-fixes, hacktoberfest-accepted

#5410 GitHub Workflows security hardening
  .github/workflows/build.yml
  .github/workflows/core.yml
  .github/workflows/download.yml
  .github/workflows/quick-test.yml
Labels: docs/meta/cleanup

#5149 Update py2exe
  .github/workflows/build.yml
  setup.py
Labels: docs/meta/cleanup, pending-fixes, hacktoberfest-accepted

#5490 [extractor/youtube] Ignore incomplete data error for comment replies
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#5493 [extractor/nzherald] Support new video embed
  yt_dlp/extractor/nzherald.py
Labels: site-bug

#5449 Add armv7 & aarch64 build artifacts to the build workflow
  .github/workflows/build.yml
  README.md
  pyinst.py
  yt_dlp/update.py
  yt_dlp/utils.py
Labels: docs/meta/cleanup

#5423 [build] Use conda to create a really distribution-agnostic standalone binary
  .github/workflows/build.yml
Labels: docs/meta/cleanup

#5279 [extractor/cinetecamilano] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/cinetecamilano.py
Labels: site-request, hacktoberfest-accepted

#5270 Add areena.yle.fi video download support
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/yle_areena.py
Labels: site-request, hacktoberfest-accepted

#5242 Veoh user IE support
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/veoh.py
Labels: site-request, hacktoberfest-accepted

#5559 [extractor/redgifs] Fix bug in 8c188d5 (#5352)
  yt_dlp/extractor/redgifs.py
Labels: NSFW, site-bug

#5560 [extractor/twitter] Refresh guest token when expired
  yt_dlp/extractor/twitter.py
Labels: site-bug

#5577 [extractor/generic] Fix JSON LD manifest extraction
  yt_dlp/extractor/generic.py
Labels: bug

#5591 [extractor/reddit] add vcodec to fallback format
  yt_dlp/extractor/reddit.py
Labels: site-enhancement

#5528 Add `fragment_query` generic extractor arg for DASH and native HLS
  README.md
  yt_dlp/downloader/dash.py
  yt_dlp/extractor/generic.py
Labels: enhancement

#5596 [extractor/vimeo] Add `VimeoProIE`
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/vimeo.py
Labels: site-enhancement

#5604 [extractor/screencastify] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/screencastify.py
Labels: site-request

#5620 [extractor/naver] Improve `_VALID_URL` for `NaverNowIE`
  yt_dlp/extractor/naver.py
Labels: site-bug

#5575 Add new extractor: Kanal2
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/kanal2.py
Labels: site-request

#5628 added the new url format for Gronkh and tests [Issue #5531]
  yt_dlp/extractor/gronkh.py
Labels: site-bug

#2768 [youporn] Fix extraction of metadata
  yt_dlp/extractor/youporn.py
Labels: NSFW, site-enhancement

#3628 [amazonminitv] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/amazonminitv.py
Labels: site-request
