Repository yt-dlp/yt-dlp, pull requests merged in 2022-02, with the labels that each got.

#2338 [extractor/ertgr] Add new extractors
  yt_dlp/extractor/ertgr.py
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/generic.py
Labels: site-request

#2401 Discovery Affiliates Site Change Update
  yt_dlp/extractor/dplay.py
  yt_dlp/extractor/extractors.py
Labels: site-enhancement, pending-fixes

#2449 [TikTok] Iterate through app versions
  README.md
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#2521 [twitcasting] enforce UTF-8 for POST payload
  yt_dlp/extractor/twitcasting.py
Labels: site-bug

#2158 [mediaset] fix #2149
  yt_dlp/extractor/mediaset.py
Labels: site-bug

#2579 [nfb] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/nfb.py
Labels: site-request, pending-fixes

#1066 Modify sanitize_open() to use locked_file()
  yt_dlp/utils.py
Labels: enhancement

#2616 Fixing #2592
  yt_dlp/extractor/beeg.py
Labels: NSFW, site-bug

#2661 [Gettr] Add `GettrStreamingIE`
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/gettr.py
Labels: site-enhancement

#2698 Add regexp operator to format filters
  README.md
  yt_dlp/YoutubeDL.py
Labels: enhancement

#2699 [zoom] Adding support for downloading screen cast via formats
  yt_dlp/extractor/zoom.py
Labels: site-enhancement, pending-fixes

#2765 [youtube] Ensure subtitle urls are absolute
  yt_dlp/extractor/youtube.py
Labels: site-bug

#2665 [ruv.is] add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/ruv.py
Labels: site-enhancement, pending-fixes

#2414 [peekvids] add new extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/peekvids.py
Labels: site-request, NSFW, pending-fixes

#2387 [murrtube] Add new extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/murrtube.py
Labels: site-request, NSFW, pending-fixes

#2295 [extractor/cspan] Support of C-Span congress videos
  yt_dlp/extractor/cspan.py
  yt_dlp/extractor/extractors.py
Labels: site-enhancement

#2793 Sponsorblock minor fixes
  yt_dlp/postprocessor/ffmpeg.py
  yt_dlp/postprocessor/modify_chapters.py
Labels: bug

#2796 [washingtonpost] Add feature to read data from json that will be loaded on page.
  yt_dlp/extractor/washingtonpost.py
Labels: site-bug, pending-fixes

#2731 Fixing Biqle #193
  yt_dlp/extractor/biqle.py
Labels: NSFW, site-bug

#2829 [tubitv] TV series extraction fix & metadata improvements
  yt_dlp/extractor/tubitv.py
  yt_dlp/utils.py
Labels: site-enhancement, site-bug, pending-fixes

#2827 Added support for web-series
  yt_dlp/extractor/zee5.py
Labels: site-enhancement

#2850 [nhk] Add support for NHK for School
  yt_dlp/extractor/common.py
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/nhk.py
Labels: site-request

#2824 [YoutubeDL] Fill more fields for playlists
  yt_dlp/YoutubeDL.py
Labels: enhancement

#1688 AbemaTV batch 3/3: [AbemaTV] add support for abema.tv
  yt_dlp/extractor/abematv.py
  yt_dlp/extractor/extractors.py
  yt_dlp/utils.py
Labels: site-request

#2418 [fc2:live] add support for live.fc2.com
  yt_dlp/downloader/__init__.py
  yt_dlp/downloader/fc2.py
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/fc2.py
  yt_dlp/utils.py
Labels: site-request

#2901 [downloader/fragment] Fix bugs around resuming with Range
  yt_dlp/downloader/fragment.py
  yt_dlp/downloader/http.py
  yt_dlp/utils.py
Labels: bug
