Repository yt-dlp/yt-dlp, pull requests merged in 2022-12, with the labels that each got.

#5677 [extractor/reddit] Extract video embeds in text posts
  yt_dlp/extractor/reddit.py
Labels: site-enhancement

#5681 [extractor/swearnet] Fix description bug
  yt_dlp/extractor/swearnet.py
Labels: site-bug

#5690 [extractor/tiktok] TikTokBaseIE update api hostname
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#5708 [extractor/tiktok] Update `_VALID_URL`, add `api_hostname` arg
  README.md
  yt_dlp/extractor/tiktok.py
Labels: site-enhancement, site-bug

#5538 [extractor/la7] fix #5360 + drm check
  yt_dlp/extractor/la7.py
Labels: site-bug, pending-fixes

#5715 [webcamerapl] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/webcamerapl.py
Labels: site-request

#5640 [mediastream] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mediastream.py
Labels: site-request, pending-fixes

#5735 [yle_areena] Extended to proceed protected content.
  yt_dlp/extractor/yle_areena.py
Labels: site-bug

#5664 [extractor/mediaset] Better DRM/Paywall message + _EMBED_REGEX
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/mediaset.py
Labels: site-enhancement

#5737 [extractor/slideslive] Fix extractor
  yt_dlp/extractor/slideslive.py
Labels: site-bug

#5659 Fix headers for ffmpeg and video+audio formats
  yt_dlp/downloader/external.py
  yt_dlp/extractor/generic.py
Labels: bug

#5757 [extractor/twitter] Heed `--no-playlist` for multi-video tweets
  yt_dlp/extractor/twitter.py
Labels: site-enhancement

#5719 [extractor/foxsports] Fix extractor
  yt_dlp/extractor/foxsports.py
  yt_dlp/extractor/uplynk.py
Labels: site-bug

#5739 [extractor/pinterest] Fix extractor
  yt_dlp/extractor/pinterest.py
Labels: site-bug

#5533 [extractor/airtv] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/airtv.py
Labels: site-request

#5547 [extractor/europarl] Add EuroParlWebstream Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/europa.py
Labels: site-request

#5568 [extractor/netverse] Add capabilites to extract comment
  yt_dlp/extractor/netverse.py
Labels: site-enhancement, pending-fixes

#5761 [extractor/rutube] Support private videos
  yt_dlp/extractor/rutube.py
Labels: site-enhancement, pending-fixes

#5549 [extractor/oneplace] Add OnePlacePodcast extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/oneplace.py
Labels: site-request

#5569 [extractor/youtube:tab] Extract more metadata from channel renderers
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#5801 [extractor/reddit] Extract crossposted media
  yt_dlp/extractor/reddit.py
Labels: site-bug

#5009 [extractor/trtcocuk] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/trtcocuk.py
Labels: site-request

#4606 [urplay] Add support for audio-only formats
  yt_dlp/extractor/urplay.py
Labels: site-bug, pending-fixes

#5304 [extractor/beatbump] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/beatbump.py
Labels: site-request, hacktoberfest-accepted

#5879 [ArteTV] extract chapters
  yt_dlp/extractor/arte.py
Labels: site-enhancement

#5529 [cda] premium content downloading, fix login by e-mail, reduce followed redirects for web
  yt_dlp/cache.py
  yt_dlp/extractor/cda.py
Labels: site-enhancement, site-bug

#5416 [polskieradio] adapt to next.js redesigns
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/arte.py
  yt_dlp/extractor/polskieradio.py
Labels: site-bug, pending-fixes

#5601 [extractor/ciscowebex] Support password-protected videos
  yt_dlp/extractor/ciscowebex.py
Labels: site-enhancement

#5622 [extractor/youku] Fix youku extraction
  yt_dlp/extractor/youku.py
Labels: site-bug

#5729 [extractor/kankanews] Add new extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/kankanews.py
Labels: site-request

#5730 [couriositystream] Fix passing auth.
  yt_dlp/extractor/curiositystream.py
Labels: site-bug

#5791 [spankbang] fix missing playlist title and #5731
  yt_dlp/extractor/spankbang.py
Labels: NSFW, site-bug, pending-fixes

#5838 [extractor/netverse] Add NetverseSearch extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/netverse.py
Labels: site-request

#5784 [extractor/slideslive] Add support for embeds and slideshows
  yt_dlp/extractor/slideslive.py
Labels: site-enhancement

#5824 [extractor/videoken] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/videoken.py
Labels: site-request

#5857 [extractor/amazon] Add `AmazonReviewsIE`
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/amazon.py
Labels: site-enhancement

#5415 [extractor/wistia] Improve extension detection
  yt_dlp/extractor/wistia.py
  yt_dlp/utils.py
Labels: site-bug

#5736 [extractor/kick] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/kick.py
Labels: site-request

#5842 [extractor/soundcloud] Implement user permalink support
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/soundcloud.py
Labels: site-enhancement

#5800 fix: avoid for loop.
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/adn.py
  yt_dlp/extractor/discovery.py
  yt_dlp/extractor/funimation.py
  yt_dlp/extractor/linuxacademy.py
  yt_dlp/extractor/tencent.py
  yt_dlp/extractor/tiktok.py
  yt_dlp/extractor/videa.py
  yt_dlp/extractor/viu.py
  yt_dlp/extractor/vrv.py
  yt_dlp/extractor/youku.py
Labels: docs/meta/cleanup

#5771 [extractor/sovietscloset] Fix __NUXT_JSONP__ extraction
  test/test_utils.py
  yt_dlp/utils.py
Labels: bug, regression

#5537 [extractor/bandcamp] Add album_artist metadata (#5536)
  yt_dlp/extractor/bandcamp.py
Labels: site-enhancement
