Repository yt-dlp/yt-dlp, pull requests merged in 2022-06, with the labels that each got.

#3455 [npr]: get stream url from json-ld
  yt_dlp/extractor/common.py
  yt_dlp/extractor/npr.py
Labels: site-bug

#3775 [youtube] Fix :ytnotifications extractor
  yt_dlp/extractor/youtube.py
Labels: site-bug

#2283 [ESPN] Add extractor for WatchESPN videos
  yt_dlp/extractor/espn.py
  yt_dlp/extractor/extractors.py
Labels: site-enhancement, pending-fixes

#3975 turn cookie store detection on it's feet
  yt_dlp/cookies.py
Labels: bug, pending-fixes

#3493 [suggestion] show total frags when downloading YouTube live video with --live-from-start
  yt_dlp/downloader/dash.py
  yt_dlp/downloader/fragment.py
  yt_dlp/extractor/youtube.py
Labels: enhancement

#4008 [SouthPark] South Park with Spanish Latam (Regex Fixed)
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/southpark.py
Labels: site-request, pending-fixes

#3916 [extractor/youtube] Add `innertube_host` and `innertube_key` extractor args
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#3587 [freetv] Add an extractor for freetv.com
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/freetv.py
Labels: site-request

#3866 [navernow] New extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/naver.py
Labels: site-request

#3874 [FranceCulture] Fix extractor (#3742)
  yt_dlp/extractor/common.py
  yt_dlp/extractor/franceculture.py
Labels: site-bug

#4009 [GoogleDrive:Folder] Add extractor
  yt_dlp/extractor/common.py
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/googledrive.py
Labels: site-request, pending-fixes

#4104 [extractor/pornhub] Extract `uploader_id` field
  yt_dlp/extractor/pornhub.py
Labels: site-enhancement

#3999 [MirrorCoUK] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mirrorcouk.py
Labels: site-request

#4011 [substack] Add new extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/substack.py
Labels: site-request

#4057 [extractor/common] Add `default` parameter to `_search_json`
  yt_dlp/extractor/archiveorg.py
  yt_dlp/extractor/common.py
Labels: bug

#4065 [extractor/radiofrance] Add support for FIP, Le Mouv, France Musique
  yt_dlp/extractor/radiofrance.py
Labels: site-enhancement, pending-fixes

#3953 [ixigua] Add Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/ixigua.py
Labels: site-request, pending-fixes

#4084 [DailyWire] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/dailywire.py
Labels: site-request

#4073 [kicker.de] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/kicker.py
Labels: site-request

#2324 [Tennistv] Rewrite
  yt_dlp/extractor/tennistv.py
Labels: account-needed, site-bug, help testing, stale-pr

#4075 Use existing dropout session when found in cookies
  yt_dlp/extractor/dropout.py
Labels: account-needed, site-enhancement, help testing

#4146 [extractor/youtube] Fully implement "mark_watched"
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#4158 Fix bug when handling HTTP requests
  yt_dlp/utils.py
Labels: bug

#4151 [extractor/fuyin.tv] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/fuyintv.py
Labels: site-request

#4194 Typo Fixes
  CONTRIBUTING.md
  Changelog.md
  README.md
  pyinst.py
  yt_dlp/dependencies.py
  yt_dlp/extractor/abematv.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/rokfin.py
  yt_dlp/extractor/youtube.py
  yt_dlp/options.py
  yt_dlp/postprocessor/ffmpeg.py
  yt_dlp/update.py
  yt_dlp/utils.py
  ytdlp_plugins/extractor/sample.py
Labels: docs/meta/cleanup, pending-fixes

#4106 Support macOS from 10.9
  .github/workflows/build.yml
  README.md
Labels: docs/meta/cleanup

#4147 [ViMP] Support playlists, add more instances
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/videocampus_sachsen.py
Labels: site-request

#4204 [livestreamfails] Add new extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/livestreamfails.py
Labels: site-request

#4220 Make the build reproducible
  devscripts/make_lazy_extractors.py
Labels: docs/meta/cleanup
