Repository yt-dlp/yt-dlp, pull requests merged in 2022-04, with the labels that each got.

#3265 [youtube:search] Support hashtag tile entry
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#3267 [openrec] Downloading archived livestreams
  yt_dlp/extractor/openrec.py
Labels: site-bug

#3264 [Cybrary] Add extractor
  yt_dlp/extractor/cybrary.py
  yt_dlp/extractor/extractors.py
Labels: site-request

#3291 [Imdb] Improve extractor
  yt_dlp/extractor/imdb.py
Labels: site-enhancement

#2955 [crunchyroll:playlist:beta] implement directly through beta api
  yt_dlp/extractor/crunchyroll.py
Labels: site-enhancement

#3294 [ruutu] Add extractor for nelonen.fi
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/ruutu.py
Labels: site-enhancement

#3218 [fptplay] Improve extractor
  yt_dlp/extractor/fptplay.py
Labels: site-bug

#3282 [Moviepilot] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/moviepilot.py
Labels: site-request, pending-fixes

#3319 [twitcasting] Don't return multi_video for archive with single hls manifest
  yt_dlp/extractor/twitcasting.py
Labels: site-enhancement

#2994 Do not O_TRUNC writeable files before obtaining an advisory lock
  yt_dlp/utils.py
Labels: bug

#3268 [TVer] Fix extractor
  yt_dlp/extractor/tver.py
Labels: site-bug, pending-fixes

#3286 [AfreecaTV] Improve extractor
  yt_dlp/extractor/afreecatv.py
  yt_dlp/extractor/extractors.py
Labels: site-request

#3231 [NRK] Improve extractor
  yt_dlp/extractor/nrk.py
Labels: site-enhancement

#2288 [Zattoo] Fix information extractor (closes #1244)
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/zattoo.py
Labels: site-bug, pending-fixes

#3341 [Jable] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/jable.py
Labels: site-request, pending-fixes

#3347 [youtube] Add :ytnotifications extractor
  README.md
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/youtube.py
Labels: site-request

#3392 [facebook] Fix thumbnail extraction
  yt_dlp/extractor/facebook.py
Labels: site-bug, pending-fixes

#3320 [icareus] Add new extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/icareus.py
Labels: site-request

#3368 [bandcamp] exclude merch links for user info extractor
  yt_dlp/extractor/bandcamp.py
Labels: site-bug

#3559 Fix `NiconicoIE` login
  yt_dlp/extractor/niconico.py
Labels: site-enhancement, pending-fixes

#3573 [InfoQ] Don't fail on missing audio format, Remove 404 test case
  yt_dlp/extractor/infoq.py
Labels: site-bug, pending-fixes

#3575 [extractor/common] Use validated url in various extractors
  yt_dlp/extractor/common.py
Labels: enhancement, pending-fixes

#3555 [lrt] improve extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/lrt.py
Labels: site-enhancement
