Repository yt-dlp/yt-dlp, pull requests merged in 2022-05, with the labels that each got.

#3362 [youtube] Add YoutubeStoriesIE
  README.md
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/youtube.py
Labels: site-request, site-enhancement

#3406 [bilibili] Add extractor for live.bilibili.com
  yt_dlp/extractor/bilibili.py
  yt_dlp/extractor/extractors.py
Labels: site-request

#3577 Fix redirect HTTP method handling
  yt_dlp/utils.py
Labels: bug

#3435 Add support for client certificate authentication
  README.md
  test/test_http.py
  test/testdata/certificate/ca.crt
  test/testdata/certificate/ca.key
  test/testdata/certificate/ca.srl
  test/testdata/certificate/client.crt
  test/testdata/certificate/client.csr
  test/testdata/certificate/client.key
  test/testdata/certificate/clientencrypted.key
  test/testdata/certificate/clientwithencryptedkey.crt
  test/testdata/certificate/clientwithkey.crt
  test/testdata/certificate/instructions.md
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/options.py
  yt_dlp/utils.py
Labels: enhancement

#3509 [trovo] Update to new API, show proper error for subscriber-only videos
  yt_dlp/extractor/trovo.py
Labels: site-bug, pending-fixes

#3414 [Fifa.com] New Fifa Extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/fifa.py
Labels: site-request

#3358 [masters] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/masters.py
Labels: site-request

#3625 [Likee] Add new extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/likee.py
Labels: site-request

#3634 [TVer] improve extraction
  yt_dlp/extractor/tver.py
Labels: site-bug

#3462 [khan academy] Fix extractor
  yt_dlp/extractor/khanacademy.py
Labels: site-bug, pending-fixes

#3639 [iwara] Add extractors
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/iwara.py
Labels: NSFW, site-enhancement, pending-fixes

#3337 [gronkh] Improve extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/gronkh.py
Labels: site-request

#3423 [ZingMp3] Improve extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/zingmp3.py
Labels: site-request

#3547 [ruutu] Add hs.fi embeds
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/ruutu.py
Labels: site-enhancement

#3655 [radiko] Fix extractor
  yt_dlp/extractor/radiko.py
Labels: site-bug

#3665 [Podchaser] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/podchaser.py
Labels: site-request

#2992 [Rokfin] Search & login
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/rokfin.py
Labels: site-enhancement

#3686 [goodgame] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/goodgame.py
Labels: site-request, pending-fixes

#3807 [ina] Update extractor
  yt_dlp/extractor/ina.py
Labels: site-bug, pending-fixes

#3889 [utils] Send HTTP/1.1 ALPN entension
  yt_dlp/utils.py
Labels: bug, enhancement

#3891 [duboku] Fix hostname change and require referer
  yt_dlp/extractor/duboku.py
Labels: site-bug

#845 [playsuisse] Add new extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/playsuisse.py
Labels: site-request, patch-available
