Repository yt-dlp/yt-dlp, pull requests merged in 2022-03, with the labels that each got.

#2884 [youtube:tab] Follow non-standard redirect to regional channel
  yt_dlp/extractor/youtube.py
Labels: site-bug

#2714 fallback to lockf()
  yt_dlp/utils.py
Labels: bug

#2224 Extend file access retries to check rename and remove as well
  yt_dlp/downloader/common.py
  yt_dlp/downloader/external.py
  yt_dlp/downloader/fragment.py
  yt_dlp/options.py
Labels: enhancement

#2939 [extractor/common] Fix bug with mark watched when extractor does not support user/pass auth
  yt_dlp/extractor/common.py
Labels: bug

#2922 [New extractor] telegram
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/telegram.py
Labels: site-request, pending-fixes

#2924 Feat: new extractor daystar
  yt_dlp/extractor/daystar.py
  yt_dlp/extractor/extractors.py
Labels: site-request, pending-fixes

#2889 Feat: update new version for zingmp3
  yt_dlp/extractor/zingmp3.py
Labels: site-bug, pending-fixes

#2920 [Gettr] Improve extractor
  yt_dlp/extractor/gettr.py
Labels: site-enhancement

#2787 [VideocampusSachsen] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/videocampus_sachsen.py
Labels: site-request

#1982 [extractor/ant1newsgr] Add new extractor
  yt_dlp/extractor/ant1newsgr.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/tvopengr.py
  yt_dlp/utils.py
Labels: site-request

#2883 [tumblr] Fix extraction; fix login; get additional metadata
  yt_dlp/extractor/tumblr.py
Labels: site-bug, pending-fixes

#2940 [mildom] Rework extractors
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/mildom.py
Labels: docs/meta/cleanup

#2977 [adobepass] Add Suddenlink MSO
  yt_dlp/extractor/adobepass.py
Labels: site-enhancement, pending-fixes

#2433 [core] Add brotli content encoding support
  README.md
  pyinst.py
  requirements.txt
  setup.py
  yt_dlp/YoutubeDL.py
  yt_dlp/compat.py
  yt_dlp/utils.py
Labels: enhancement, pending-fixes

#2986 [peertube] Add support for media.fsfe.org
  yt_dlp/extractor/peertube.py
Labels: site-enhancement

#2963 [xinpianchang] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/xinpianchang.py
Labels: site-request

#1534 [Rokfin] Add extractor
  yt_dlp/extractor/rokfin.py
Labels: site-enhancement, do-not-merge

#2570 Refactor `__init__.py`
  yt_dlp/__init__.py
  yt_dlp/options.py
  yt_dlp/postprocessor/ffmpeg.py
  yt_dlp/utils.py
Labels: docs/meta/cleanup

#2908 [panopto] Add Extractors
  README.md
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/panopto.py
  yt_dlp/options.py
Labels: site-request

#2971 [MangoTV] Improve extractor
  yt_dlp/extractor/mgtv.py
Labels: site-enhancement

#3004 [Zingmp3] Hotfix for get signature
  yt_dlp/extractor/zingmp3.py
Labels: site-bug, pending-fixes

#3029 [youtube] refactor and improve time text extraction
  yt_dlp/extractor/youtube.py
Labels: site-enhancement, site-bug

#3044 [downloader/mhtml] Fix fragments with absolute urls
  yt_dlp/downloader/mhtml.py
  yt_dlp/extractor/francetv.py
  yt_dlp/extractor/youtube.py
Labels: bug

#1872 Add playlist support to FranceCulture extractor
  yt_dlp/extractor/franceculture.py
Labels: site-enhancement

#2757 [daftsex] Fix yt-dlp#2637
  yt_dlp/extractor/daftsex.py
Labels: site-request, NSFW

#3018 [niconico] Rewrite NiconicoIE
  README.md
  yt_dlp/extractor/niconico.py
Labels: site-enhancement, pending-fixes

#3099 [nitter] Update instance list; fix minor metadata bugs
  yt_dlp/extractor/nitter.py
Labels: site-enhancement

#3065 [downloader/http] Make retrying more lenient
  yt_dlp/downloader/http.py
Labels: enhancement

#3009 [panopto] Extract slides + subtitles for videos without m3u8 subs
  yt_dlp/extractor/panopto.py
Labels: site-enhancement

#3079 [downloader/http] Reject broken range before request
  yt_dlp/downloader/http.py
Labels: bug

#3152 [downloader/external] Fix WgetFD proxy
  yt_dlp/downloader/external.py
Labels: bug

#3115 [core] Use certificates from certifi if installed
  README.md
  pyinst.py
  requirements.txt
  yt_dlp/YoutubeDL.py
  yt_dlp/options.py
  yt_dlp/utils.py
Labels: enhancement, help testing

#3156 [generic] Extract subtitles from video.js
  yt_dlp/extractor/generic.py
Labels: enhancement, pending-fixes

#3153 [core] Remove `Accept-Encoding` header from `std_headers`
  yt_dlp/downloader/external.py
  yt_dlp/utils.py
Labels: bug

#3141 [LastFM] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/lastfm.py
Labels: site-request, pending-fixes

#3136 [viu] Fixed bugs and API updated
  yt_dlp/extractor/viu.py
Labels: geo-blocked, site-bug

#3168 [youtube:tab] Use shorts video url
  yt_dlp/extractor/youtube.py
Labels: site-enhancement, pending-fixes

#3219 Manifest subtitles V
  yt_dlp/extractor/go.py
  yt_dlp/extractor/viu.py
Labels: site-enhancement

#3171 [youtube:tab] Fix duration extraction for shorts
  test/test_utils.py
  yt_dlp/extractor/youtube.py
  yt_dlp/utils.py
Labels: site-bug

#3203 [BiliIntl] Support user-generated content videos
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement, pending-fixes

#3045 [WasdTV] Add extractor
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/wasdtv.py
Labels: site-request, do-not-merge

#3188 Added xnxx.com's alternative domain support.
  yt_dlp/extractor/xnxx.py
Labels: NSFW, site-enhancement

#3220 Add a simple .editorconfig file
  .editorconfig
Labels: docs/meta/cleanup

#3197 change licensing info slightly
  README.md
Labels: docs/meta/cleanup

#3208 [Craftsy] Add support for craftsy site.
  yt_dlp/extractor/craftsy.py
  yt_dlp/extractor/extractors.py
Labels: site-request, pending-fixes
