Repository yt-dlp/yt-dlp, pull requests merged in 2022-10, with the labels that each got.

#5099 [downloader/aria2c] fix errors when temp files for fragment downloads contain leading whitespace
  yt_dlp/downloader/external.py
Labels: bug

#5117 [extractor/iltalehti] New extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/iltalehti.py
Labels: site-request, pending-fixes

#5096 [extractor/hrfensehen] : fixed `hrfensehen` broken extractor
  yt_dlp/extractor/hrfensehen.py
Labels: site-bug, needs-testing, hacktoberfest-suggested, hacktoberfest-accepted

#5094 [extractor/bundesliga] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/bundesliga.py
Labels: site-request, hacktoberfest-suggested

#5082 Extractor for Microsoft embedded videos
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/microsoftembed.py
Labels: site-request, hacktoberfest-suggested, hacktoberfest-accepted

#5124 zee5 regex fix
  yt_dlp/extractor/zee5.py
Labels: site-bug, pending-fixes

#5074 [extractor/anvato] Fix extractor
  Makefile
  setup.py
  yt_dlp/extractor/anvato.py
  yt_dlp/extractor/anvato_token_generator/__init__.py
  yt_dlp/extractor/anvato_token_generator/common.py
  yt_dlp/extractor/anvato_token_generator/nfl.py
Labels: site-bug, pending-fixes

#5126 [extractor/paramountplus] Fix formats request and detection
  yt_dlp/extractor/paramountplus.py
Labels: site-bug

#5112 [extractor/JWPlatform] Fix extractor
  yt_dlp/extractor/common.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/jwplatform.py
Labels: site-bug

#5111 [extractor/AmazonStore] Fix JSON extraction
  yt_dlp/extractor/amazon.py
Labels: site-bug

#4948 [extractor/holodex] fix id regex
  yt_dlp/extractor/holodex.py
Labels: site-bug, pending-fixes

#5091 [extractor/youtube] Download manifestless post-live videos from the start
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#5089 Add Israel National News extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/israelnationalnews.py
Labels: site-request, pending-fixes, hacktoberfest-suggested, hacktoberfest-accepted

#5043 [Bilibili] fix BilibiliSpaceBaseIE with playlist-items
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#4899 [extractor/detik] Generalize detik extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/cnn.py
  yt_dlp/extractor/detik.py
Labels: site-request

#4892 [redgifs] Fix extractor
  yt_dlp/extractor/redgifs.py
Labels: site-bug

#4834 [extractor/booyah] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/booyah.py
Labels: site-request

#5121 [extractor/24tv.ua] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tv24ua.py
Labels: site-request

#4774 [extractor/prankcast] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/prankcast.py
Labels: site-request

#5088 [extractor/onenewsnz] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/onenewsnz.py
Labels: site-request, pending-fixes

#5139 [livestreamfails] Support alternative URLs
  yt_dlp/extractor/livestreamfails.py
Labels: site-enhancement, pending-fixes

#5150 Tnaflix 500 err
  yt_dlp/extractor/tnaflix.py
Labels: NSFW, site-bug, needs-testing, hacktoberfest-suggested, hacktoberfest-accepted

#5152 [extractor/youtube] Extract concurrent view count for live streams
  README.md
  yt_dlp/extractor/common.py
  yt_dlp/extractor/youtube.py
Labels: enhancement, site-enhancement

#5174 [utils] `traverse_obj`: Allow `re.Match` objects
  test/test_utils.py
  yt_dlp/utils.py
Labels: enhancement

#5137 [extractor/screen9] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/screen9.py
Labels: site-request

#4930 [VK] Fix playlist URLs
  yt_dlp/extractor/vk.py
Labels: site-bug

#4822 [extractor/nos.nl] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nosnl.py
Labels: site-request

#5173 [extractor/viu] Added support for second subtitle and updated testing url
  yt_dlp/extractor/viu.py
Labels: site-enhancement, needs-testing

#5145 [extractor/common] Fix `json_ld` type checks
  yt_dlp/extractor/common.py
  yt_dlp/extractor/generic.py
Labels: bug

#5087 [extractor/wordpress:mb.miniAudioPlayer] Add generic embed extractor
  test/test_utils.py
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/wordpress.py
  yt_dlp/utils.py
Labels: site-request

#4971 [extractors/podbayfm] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/podbayfm.py
  yt_dlp/utils.py
Labels: site-request, needs-testing

#5195 [cookies] Fix and simplify `LenientSimpleCookie` parsing behavior
  test/test_cookies.py
  yt_dlp/cookies.py
Labels: enhancement

#5208 [extractor/twitter] Full onion support
  yt_dlp/extractor/twitter.py
Labels: site-enhancement, hacktoberfest-suggested

#5205 Aeon.co Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/aeonco.py
Labels: site-request, pending-fixes, hacktoberfest-suggested

#5100 cda: allow using api
  yt_dlp/extractor/cda.py
Labels: site-enhancement

#5243 Add Fox TV thumbnail support
  yt_dlp/extractor/fox.py
Labels: site-enhancement, hacktoberfest-suggested

#5255 Fix YouTube clip end_time not being set.
  yt_dlp/YoutubeDL.py
Labels: bug, regression

#5260 [SponsorBlock] Add support for chapter category
  README.md
  test/test_postprocessors.py
  yt_dlp/options.py
  yt_dlp/postprocessor/modify_chapters.py
  yt_dlp/postprocessor/sponsorblock.py
Labels: enhancement

#5285 [extractor/paramountplus] Update API token
  yt_dlp/extractor/paramountplus.py
Labels: site-bug

#5247 [extractor/twitter] Base extractor api overhaul
  README.md
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/twitter.py
Labels: site-enhancement, site-bug

#5289 [zeenews] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/zeenews.py
Labels: site-request

#5343 [extractor/americastestkitchen] Fix `_VALID_URL` and season extraction
  yt_dlp/extractor/americastestkitchen.py
Labels: site-bug

#5268 [zen.yandex.ru] Fix download
  test/test_download.py
  yt_dlp/extractor/yandexvideo.py
Labels: site-enhancement

#4832 [extractor/mlb.py] Add MLBArticle extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mlb.py
Labels: site-request

#4945 [extractor/bilibili] fix bangumi and bangumi playlist
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#5368 [extractor/japandiet] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/japandiet.py
Labels: site-request, pending-fixes
