Repository yt-dlp/yt-dlp, pull requests merged in 2022-08, with the labels that each got.

#4515 [doc] Fix capitalization in references
  README.md
  yt_dlp/options.py
Labels: docs/meta/cleanup

#4480 [extractor/YahooJapanNews] Fix extractor
  yt_dlp/extractor/yahoo.py
Labels: geo-blocked, site-bug

#4524 [rai] added raisudtirol support (fix #4206)
  test/test_utils.py
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/rai.py
  yt_dlp/utils.py
Labels: site-request

#1649 Generalize retries
  README.md
  test/test_downloader_http.py
  yt_dlp/downloader/common.py
  yt_dlp/downloader/external.py
  yt_dlp/downloader/fragment.py
  yt_dlp/downloader/http.py
  yt_dlp/downloader/ism.py
  yt_dlp/downloader/youtube_live_chat.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/soundcloud.py
  yt_dlp/extractor/tiktok.py
  yt_dlp/extractor/youtube.py
  yt_dlp/options.py
  yt_dlp/postprocessor/common.py
  yt_dlp/utils.py
Labels: enhancement

#4494 [extractor/xfileshare] Add Referer in HTTP header
  yt_dlp/extractor/xfileshare.py
Labels: site-bug, pending-fixes, piracy/illegal

#1482 [core] merging formats by codecs, determining extension before download
  README.md
  test/test_utils.py
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/options.py
  yt_dlp/utils.py
Labels: enhancement

#4415 [extractor/NovaPlay] Fix extractor and update tests
  yt_dlp/extractor/novaplay.py
Labels: site-bug, pending-fixes

#4593 [extractor/youtube] Guard against YouTube returning a player response of a different video
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-bug

#4513 [build] Improve build process
  .github/workflows/build.yml
  .github/workflows/core.yml
  .github/workflows/download.yml
  .github/workflows/quick-test.yml
Labels: docs/meta/cleanup

#4540 [extractor/harpodeon] Add Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/harpodeon.py
Labels: site-request

#4479 [extractor/rtbf] Update extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/parliamentliveuk.py
  yt_dlp/extractor/redbee.py
  yt_dlp/extractor/rtbf.py
Labels: site-bug

#4638 [patreon] Ignore erroneous attachment media
  yt_dlp/extractor/patreon.py
Labels: site-bug

#4643 Unify various _exempli gratia_ with "e.g."
  CONTRIBUTING.md
  Changelog.md
  README.md
  supportedsites.md
  yt_dlp/YoutubeDL.py
  yt_dlp/downloader/f4m.py
  yt_dlp/extractor/abematv.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/openload.py
  yt_dlp/extractor/youtube.py
  yt_dlp/minicurses.py
  yt_dlp/options.py
  yt_dlp/utils.py
Labels: docs/meta/cleanup

#4616 [parler] Add new extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/parler.py
Labels: site-request

#4660 [facebook] add reel support
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/facebook.py
Labels: site-request, pending-fixes

#4609 [truth] added new extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/truth.py
Labels: site-request

#4607 [extractor/moview] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/jixie.py
  yt_dlp/extractor/kompas.py
  yt_dlp/extractor/moview.py
Labels: site-request

#4586 [MLB.tv] New Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mlb.py
Labels: site-request, account-needed

#4671 [extractor/rtbf] Update stream extractor
  yt_dlp/extractor/redbee.py
Labels: site-bug

#4739 [extractor/medaltv] Fix extraction and account for new url format
  yt_dlp/extractor/medaltv.py
Labels: site-bug, pending-fixes

#4761 [screencastomatic] Add support for protected videos
  yt_dlp/extractor/screencastomatic.py
Labels: site-enhancement

#4779 [extractor/IslamChannel] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/islamchannel.py
Labels: site-request

#4770 [extractor/youtube] Use mobile user-agent for mobile client requests
  yt_dlp/extractor/youtube.py
Labels: site-bug

#4792 [youtube] Bump iOS clients versions & Add Creator/Music apps UA
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#4666 Unset LD_LIBRARY_PATH for child processes on non-Windows systems
  yt_dlp/utils.py
Labels: enhancement

#4725 [extractor/newspicks] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/newspicks.py
Labels: site-request

#4781 [extractor/stripchat] remove trailing slash from url causing redirect to dummy domain.
  yt_dlp/extractor/stripchat.py
Labels: NSFW, site-bug

#4772 [extractor/epoch] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/epoch.py
Labels: site-request

#4613 [extractor/eurosport] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/eurosport.py
Labels: site-request

#4759 [extractor/bilibili] Support flac format.
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement, needs-testing
