Repository yt-dlp/yt-dlp, pull requests merged in 2022-09, with the labels that each got.

#4706 Add VQQ extractor and JSInterp improvements
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tencent.py
  yt_dlp/extractor/wetv.py
Labels: site-request, needs-testing

#4712 [extractor/triller] Add Triller extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/triller.py
Labels: site-request, pending-fixes

#4771 [extractor/youtube] Add compat-opt to revert "Prefer UTC upload date for videos"
  README.md
  yt_dlp/extractor/youtube.py
  yt_dlp/options.py
Labels: site-enhancement

#4790 Make `make tar' ignore DESTDIR
  Makefile
Labels: docs/meta/cleanup

#4813 [extractor/triller] Fix auth token bug
  yt_dlp/extractor/triller.py
Labels: site-bug, pending-fixes

#4811 [extractor/amazonstore] Retry to avoid captcha page
  yt_dlp/extractor/amazon.py
Labels: site-enhancement

#4817 [extractor/mediaworksnz] Add MediaWorksNZVOD extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mediaworksnz.py
Labels: site-request

#4841 [utils] Do not ignore base_url path components that contain ampersand
  test/test_utils.py
  yt_dlp/utils.py
Labels: bug

#4470 [extractor/youtube] Support changing extraction langauge
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-enhancement, needs-testing

#4940 Allow open ranges for chapters
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/options.py
Labels: enhancement

#4780 Manually parse cookies
  test/test_cookies.py
  yt_dlp/cookies.py
  yt_dlp/extractor/common.py
Labels: bug

#4958 Fixing [Errno 18] Invalid cross-device-link appearing on 'python3 devscripts/make_lazy_extractors.py' execution
  devscripts/make_lazy_extractors.py
Labels: docs/meta/cleanup

#3412 [GoPlay] Adds extractor as a replacement of old Vier extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/goplay.py
  yt_dlp/extractor/vier.py
Labels: site-request, needs-testing

#4932 [extractor/youtube] Add support for extracting shorts audio pivot feed
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/youtube.py
Labels: site-request

#4708 [extractor/instagram] Fix missing metadata in post extractor
  yt_dlp/extractor/instagram.py
Labels: site-enhancement

#4819 [extractor/wistia] Add support for channels
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/wistia.py
Labels: site-request, site-bug

#5015 [extractor/Smotrim] Add extractor (again)
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/smotrim.py
Labels: site-request

#5016 [extractor/RUTV] Fix warnings for livestreams
  yt_dlp/extractor/rutv.py
Labels: site-bug

#5024 [core] `traverse_obj`: Various fixes
  test/test_utils.py
  yt_dlp/utils.py
Labels: docs/meta/cleanup, enhancement

#5029 [extractor/heise] Fix extractor
  yt_dlp/extractor/heise.py
  yt_dlp/extractor/youtube.py
Labels: site-bug

#5047 [extractor/artetv] Remove duplicate stream urls
  yt_dlp/extractor/arte.py
Labels: site-enhancement

#4965 [soundcloud] Enriched search results
  yt_dlp/extractor/soundcloud.py
Labels: site-enhancement, pending-fixes

#4921 [BerufeTV] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/berufetv.py
Labels: site-request

#5012 [extractor/wordpress] Add generic playlist embed extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/wordpress.py
Labels: site-request

#5040 [extractor/ondemandkorea] Update jw_config regex
  yt_dlp/extractor/ondemandkorea.py
Labels: site-bug

#5041 [extractor/crunchyroll:beta] Provide hardsub formats where possible
  README.md
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/crunchyroll.py
Labels: site-enhancement, site-bug

#5077 [extractor/nbc] Add NBCStationsIE
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nbc.py
Labels: site-request

#4803 [extractor/audioboom] Sanitize webpage URL before downloading
  yt_dlp/extractor/audioboom.py
Labels: site-bug

#4880 [extractor/trovo] fix extractor
  yt_dlp/extractor/trovo.py
Labels: site-bug

#4966 [Mxplayer] Fix extractor
  yt_dlp/extractor/mxplayer.py
Labels: site-bug
