Repository yt-dlp/yt-dlp, pull requests merged in 2023-10, with the labels that each got.

#8238 [ie/youtube] Raise a warning for `Incomplete Data` error instead by default
  README.md
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-enhancement

#8232 [ie/xhamster:user] Support creator urls
  yt_dlp/extractor/xhamster.py
Labels: NSFW, site-enhancement

#8272 [ie/WrestleUniverseVOD] Call API with device ID
  yt_dlp/extractor/wrestleuniverse.py
Labels: site-bug

#7785 [extractor/litv] Fix playlist and video download
  yt_dlp/extractor/litv.py
Labels: site-bug

#8181 [extractor/neteasemusic] Fix broken extractor
  yt_dlp/extractor/neteasemusic.py
Labels: site-bug

#8201 [ie/abc:iview] Extract episode name from title
  yt_dlp/extractor/abc.py
Labels: site-enhancement

#8213 [WIP] [ie/lbry] playlist support, fix #5982
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/lbry.py
Labels: site-enhancement

#8218 [extractor/substack] Fix embed URL extraction
  yt_dlp/extractor/substack.py
Labels: site-bug

#8219 [extractor/substack] Return canonical URLs
  yt_dlp/extractor/substack.py
Labels: site-bug

#8221 Various radiko enhancements
  yt_dlp/extractor/radiko.py
Labels: geo-blocked, site-enhancement

#8260 [ie/iqiyi] Fix extractor
  yt_dlp/extractor/iqiyi.py
Labels: site-bug

#8264 Add erocast extractor.
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/erocast.py
Labels: site-request, NSFW

#8244 [ie/lbry] Extract `uploader_id`
  yt_dlp/extractor/lbry.py
Labels: site-enhancement

#8249 extract nhk world's new stream provider
  yt_dlp/extractor/nhk.py
Labels: site-bug

#7718 Fixtests
  yt_dlp/extractor/aenetworks.py
  yt_dlp/extractor/amcnetworks.py
  yt_dlp/extractor/cbc.py
  yt_dlp/extractor/cbs.py
  yt_dlp/extractor/cnbc.py
  yt_dlp/extractor/corus.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/mediaset.py
  yt_dlp/extractor/movieclips.py
  yt_dlp/extractor/nationalgeographic.py
  yt_dlp/extractor/nbc.py
  yt_dlp/extractor/scrippsnetworks.py
  yt_dlp/extractor/syfy.py
  yt_dlp/extractor/theplatform.py
  yt_dlp/extractor/theweatherchannel.py
Labels: docs/meta/cleanup

#8251 Eliminate Theta extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/theta.py
Labels: docs/meta/cleanup

#8299 [ie/youtube] Fix `heatmap` extraction
  yt_dlp/extractor/youtube.py
Labels: site-bug

#8300 [cleanup] Misc
  .github/workflows/core.yml
  .github/workflows/download.yml
  yt_dlp/extractor/common.py
  yt_dlp/extractor/tmz.py
Labels: docs/meta/cleanup

#8295 [core] Use lazy quantifier in regex for sanitizing dates in js_to_json
  test/test_utils.py
  yt_dlp/utils/_utils.py
Labels: bug

#8241 [fd/fragments] Refactor and improve progress calculation
  yt_dlp/downloader/fragment.py
  yt_dlp/utils/progress.py
Labels: enhancement

#8160 [youku] Fix extractor youku to support tudou.com
  yt_dlp/extractor/youku.py
Labels: site-bug

#8301 [arte] Allow downloading age restricted content
  yt_dlp/extractor/arte.py
Labels: site-bug

#7939 [tenplay] Add support for downloading whole seasons
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tenplay.py
Labels: site-enhancement

#8309 NHK World regex fixes 2
  yt_dlp/extractor/nhk.py
Labels: site-bug

#8205 Use `os.setxattr` if available
  README.md
  yt_dlp/utils/_utils.py
Labels: enhancement

#8328 [ie/youtube] Fix `--extractor-retries inf`
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-bug, regression

#8312 Add mbn.co.kr extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mbn.py
Labels: site-request

#8314 Add jtbc.co.kr extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/jtbc.py
Labels: site-request

#7985 Ensure dir existence for thumbnails and subtitles
  yt_dlp/YoutubeDL.py
Labels: bug, enhancement, regression

#8338 [cleanup] Misc - October 2023 edition part 2
  README.md
  yt_dlp/extractor/banbye.py
  yt_dlp/extractor/breitbart.py
  yt_dlp/extractor/craftsy.py
  yt_dlp/extractor/cybrary.py
  yt_dlp/extractor/fifa.py
  yt_dlp/extractor/filmmodu.py
  yt_dlp/extractor/itprotv.py
  yt_dlp/extractor/jable.py
  yt_dlp/extractor/kommunetv.py
  yt_dlp/extractor/mainstreaming.py
  yt_dlp/extractor/mediaite.py
  yt_dlp/extractor/mocha.py
  yt_dlp/extractor/nfl.py
  yt_dlp/extractor/novaplay.py
  yt_dlp/extractor/nubilesporn.py
  yt_dlp/extractor/oftv.py
  yt_dlp/extractor/sina.py
  yt_dlp/extractor/twitter.py
  yt_dlp/extractor/utreon.py
  yt_dlp/extractor/vk.py
  yt_dlp/extractor/weverse.py
  yt_dlp/extractor/wimtv.py
  yt_dlp/extractor/xhamster.py
  yt_dlp/extractor/youtube.py
  yt_dlp/extractor/zoom.py
  yt_dlp/options.py
Labels: docs/meta/cleanup

#3668 [rh:requests] Add support for `requests`
  .github/workflows/core.yml
  README.md
  requirements.txt
  setup.py
  test/test_networking.py
  test/test_socks.py
  yt_dlp/YoutubeDL.py
  yt_dlp/__pyinstaller/hook-yt_dlp.py
  yt_dlp/dependencies/__init__.py
  yt_dlp/networking/__init__.py
  yt_dlp/networking/_helper.py
  yt_dlp/networking/_requests.py
  yt_dlp/networking/_urllib.py
  yt_dlp/options.py
Labels: enhancement

#8348 [rh:requests] Handle both `bytes` and `int` for `IncompleteRead.partial`
  test/test_networking.py
  yt_dlp/networking/_requests.py
  yt_dlp/networking/exceptions.py
Labels: bug, high-priority, regression

#8373 [core] Only ensure playlist thumbnail dir if writing thumbs
  yt_dlp/YoutubeDL.py
Labels: bug, regression

#8427 [ie/twitcasting] twitcasting live element status had change from 'onl…
  yt_dlp/extractor/twitcasting.py
Labels: site-bug

#8413 Change to POST request in the NPO extractor
  yt_dlp/extractor/npo.py
Labels: site-bug

#8426 [ie/QDance] Update `_VALID_URL`
  yt_dlp/extractor/qdance.py
Labels: site-bug

#8340 [ie/generic] Improve direct video link ext detection
  yt_dlp/extractor/generic.py
Labels: site-bug

#8337 [ie/youtube] Deprioritize iOS client formats
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#8336 [ie/youtube] Check newly uploaded iOS HLS formats
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/youtube.py
Labels: site-bug

#8459 [ie/polskieradio] Fixed issue #8419
  yt_dlp/extractor/polskieradio.py
Labels: site-bug

#8458 [extractor/weverse] Fix username check for invalid accounts
  yt_dlp/extractor/weverse.py
Labels: site-bug
