Repository yt-dlp/yt-dlp, pull requests merged in 2023-08, with the labels that each got.

#7724 update FOX regex to include Fox Sports replays
  yt_dlp/extractor/fox.py
Labels: site-bug

#7730 [extractor/s4c]: Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/s4c.py
Labels: site-request

#7727 [ie/PicartoVod] Fix VOD download for picarto.tv
  yt_dlp/extractor/picarto.py
Labels: site-bug

#7603 [networking] Add basic RH Preference System
  test/test_networking.py
  yt_dlp/YoutubeDL.py
  yt_dlp/networking/common.py
Labels: enhancement

#7774 [ie/youtube] Fix consent cookie
  yt_dlp/extractor/youtube.py
Labels: site-bug

#7800 [cookies] Containers JSON should be opened as utf-8
  yt_dlp/cookies.py
Labels: bug

#7484 CBCPlayer
  yt_dlp/extractor/cbc.py
  yt_dlp/extractor/scrippsnetworks.py
  yt_dlp/extractor/theplatform.py
Labels: site-enhancement

#7765 TBS Free (Japan) extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tbsjp.py
Labels: site-request

#7914 [ie/zee5] Update access token endpoint
  yt_dlp/extractor/zee5.py
Labels: site-bug

#7870 Added CBCPlayerPlaylistIE
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/cbc.py
Labels: site-request

#7898 fix(wat.tv): remove `MYTF1` context to remove "Permission insuffisante" error
  yt_dlp/extractor/tf1.py
  yt_dlp/extractor/wat.py
Labels: site-bug

#7611 [rh/urllib] Simplify gzip decoding
  yt_dlp/networking/_urllib.py
Labels: enhancement

#7929 [ie/StagePlusVODConcert] Fix m3u8 extraction
  yt_dlp/extractor/stageplus.py
Labels: site-bug

#7924 Use Weverse preview endpoint if no auth provided
  yt_dlp/extractor/weverse.py
Labels: site-enhancement

#7926 [ie/Dropbox] Fix extractor
  yt_dlp/extractor/dropbox.py
Labels: site-bug

#7584 [extractor/antenna] Improvements
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/antenna.py
Labels: site-enhancement

#7757 [ie/hungama] Overhaul extractors
  yt_dlp/extractor/hungama.py
Labels: site-bug

#7830 [extractor/noodlemagazine] Fix format metadata not found
  yt_dlp/extractor/noodlemagazine.py
Labels: NSFW, site-bug

#7923 [Mediaite] Broken downloading fix
  yt_dlp/extractor/mediaite.py
Labels: site-bug

#7869 [ie/Hotstar] year added in hotstar metadata
  yt_dlp/extractor/hotstar.py
Labels: site-enhancement
