Repository yt-dlp/yt-dlp, pull requests merged in 2023-12, with the labels that each got.

#8409 [ie/francetv] Add support for episode and season tagging
  yt_dlp/extractor/francetv.py
Labels: site-enhancement

#8657 Fixed mediastream when hls uses extra arguments
  yt_dlp/extractor/mediastream.py
Labels: site-bug

#8677 [ie/ondemandkorea] Fix format upgrade
  yt_dlp/extractor/ondemandkorea.py
Labels: site-bug

#8673 [utils] `traverse_obj`: Move `is_user_input` into output template
  test/test_utils.py
  yt_dlp/YoutubeDL.py
  yt_dlp/utils/traversal.py
Labels: docs/meta/cleanup

#8635 Improving ThePlatform Metadata extraction
  yt_dlp/extractor/aenetworks.py
  yt_dlp/extractor/cbc.py
  yt_dlp/extractor/cwtv.py
  yt_dlp/extractor/mediaset.py
  yt_dlp/extractor/nbc.py
  yt_dlp/extractor/scrippsnetworks.py
  yt_dlp/extractor/theplatform.py
Labels: site-enhancement

#8763 fixed key error for like_count
  yt_dlp/extractor/youtube.py
Labels: site-bug

#8778 [RinseFM] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/rinsefm.py
Labels: site-request

#8331 [Extractors] Add maariv.co.il extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/maariv.py
Labels: site-request

#8783 [ie/bundestag] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/bundestag.py
Labels: site-request

#8724 [ie/twitter] Extract stale tweets
  yt_dlp/extractor/twitter.py
Labels: site-bug

#8384 [ie/joqrag] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/joqrag.py
Labels: site-request

#8802 [networking] Strip whitespace around header values
  test/test_utils.py
  yt_dlp/utils/networking.py
Labels: bug, networking

#8814 [test:networking] Update tests for OpenSSL 3.2
  test/test_networking.py
  test/test_websockets.py
Labels: docs/meta/cleanup, networking

#8321 [ie/bbc] extract more formats
  yt_dlp/extractor/bbc.py
Labels: site-enhancement

#8640 [core] Release workflow & Updater maintenance
  .github/workflows/build.yml
  .github/workflows/release.yml
  test/test_update.py
  yt_dlp/update.py
Labels: docs/meta/cleanup

#8664 [c13cl] Adding support for www.13.cl and rudo.video
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/rudovideo.py
Labels: site-request, geo-blocked

#8841 [ci] Skip core tests on extractor only changes
  .github/workflows/core.yml
Labels: docs/meta/cleanup

#8842 [ie/litv] Fix premium content extraction
  yt_dlp/extractor/litv.py
Labels: site-bug

#8843 [ie/instagram] Fix stories extraction
  yt_dlp/extractor/instagram.py
Labels: site-bug

#8826 [ie/twitter] Prioritize m3u8 formats
  yt_dlp/extractor/twitter.py
Labels: site-bug

#8825 [ie/twitter] Work around API rate-limit
  yt_dlp/extractor/twitter.py
Labels: site-enhancement

#8797 [core] Fix format selection parse error for CPython 3.12
  test/test_YoutubeDL.py
  yt_dlp/YoutubeDL.py
Labels: bug

#8687 Support ARD Mediathek URLs with "serien" (fixes #7666)
  yt_dlp/extractor/ard.py
Labels: site-bug

#8681 [ie/Facebook] Fix Unhandled IndexError
  yt_dlp/extractor/facebook.py
Labels: site-bug

#8836 Backports from youtube-dl (2023-12)
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/epidemicsound.py
  yt_dlp/extractor/imgur.py
  yt_dlp/extractor/telewebion.py
  yt_dlp/utils/_utils.py
Labels: solved-upstream

#8720 Create `run_tests.py`
  .github/workflows/core.yml
  .github/workflows/download.yml
  .github/workflows/quick-test.yml
  CONTRIBUTING.md
  devscripts/run_tests.bat
  devscripts/run_tests.py
  devscripts/run_tests.sh
Labels: docs/meta/cleanup

#8878 [ie/ARDBetaMediathekIE] Rework extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/ard.py
Labels: site-enhancement, site-bug

#8598 [cleanup] Misc (for 2023.12 release)
  .github/workflows/core.yml
  .github/workflows/quick-test.yml
  Collaborators.md
  README.md
  devscripts/changelog_override.json
  devscripts/make_changelog.py
  devscripts/make_issue_template.py
  requirements.txt
  test/test_YoutubeDL.py
  test/test_update.py
  test/test_utils.py
  yt-dlp.cmd
  yt-dlp.sh
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/banbye.py
  yt_dlp/extractor/duoplay.py
  yt_dlp/extractor/floatplane.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/panopto.py
  yt_dlp/extractor/radiofrance.py
  yt_dlp/extractor/wordpress.py
  yt_dlp/extractor/youtube.py
  yt_dlp/networking/__init__.py
  yt_dlp/networking/_helper.py
  yt_dlp/networking/_requests.py
  yt_dlp/networking/_websockets.py
  yt_dlp/networking/websocket.py
  yt_dlp/socks.py
  yt_dlp/utils/_utils.py
  yt_dlp/utils/traversal.py
Labels: docs/meta/cleanup
