Repository yt-dlp/yt-dlp, pull requests merged in 2023-02, with the labels that each got.

#5988 [utils] `traverse_obj`: Add `set` transformations/filters and `re.Match` group names
  test/test_utils.py
  yt_dlp/utils.py
Labels: enhancement

#5240 [txxx] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/txxx.py
  yt_dlp/utils.py
Labels: site-request, NSFW, hacktoberfest-accepted

#5705 [extractor/niconico] Add support for like history
  yt_dlp/extractor/niconico.py
Labels: site-enhancement

#6172 [extractor/huya] Add support for HD streams
  yt_dlp/extractor/huya.py
Labels: site-enhancement, needs-testing

#6158 [extractor/wrestleuniverse] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/wrestleuniverse.py
Labels: enhancement, site-request

#6074 [extractor/DouyuTV]: Fix extractor and use new api
  yt_dlp/extractor/douyutv.py
Labels: site-bug

#6159 Hotfix for radiko.jp
  yt_dlp/extractor/radiko.py
Labels: site-bug

#5828 Fix Hidive - Subtitles and Age-restriction.
  yt_dlp/extractor/hidive.py
Labels: site-bug

#5932 [91porn] fix title & comment extraction
  yt_dlp/extractor/porn91.py
Labels: NSFW, site-bug

#5954 [extractor/moviepilot] Fix extractor
  yt_dlp/extractor/moviepilot.py
Labels: site-bug

#5985 [Stripchat] fix: implement patch for stripchat
  yt_dlp/extractor/stripchat.py
Labels: NSFW, site-bug

#6086 Update tnaflix.com extractor url
  yt_dlp/extractor/tnaflix.py
Labels: NSFW, site-bug

#6102 [extractor/clyp] Added wav download support
  yt_dlp/extractor/clyp.py
Labels: site-enhancement

#6025 added support for rmc prefix to bfmtv
  yt_dlp/extractor/bfmtv.py
Labels: site-enhancement

#6155 [extractor/npo] Fix extractor and add HD support
  yt_dlp/extractor/npo.py
Labels: site-bug

#5700 [extractor/rcs] Improved and fixed RCS extractor
  yt_dlp/extractor/rcs.py
Labels: site-bug, pending-fixes, needs-testing

#6122 [extractor/vk] playlist fix for new API requirements
  yt_dlp/extractor/vk.py
Labels: site-bug

#6208 [NZOnScreen] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nzonscreen.py
Labels: site-request

#6222 [extractor/nfl] Add `NFLPlus` extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nfl.py
Labels: site-request

#6240 Improve how default youtube subs are selected
  yt_dlp/YoutubeDL.py
Labels: enhancement, pending-fixes

#6236 [extractor/nitter] Update Nitter instance list
  yt_dlp/extractor/nitter.py
Labels: site-enhancement

#6176 [utils] Don't trust Content-length when Content-encoding is present
  yt_dlp/downloader/http.py
  yt_dlp/utils.py
Labels: bug

#6170 feat: add extractor for ebay video listings
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/ebay.py
Labels: site-request

#6117 [extractor/vocaroo] Add Vocaroo extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/vocaroo.py
Labels: site-request

#6111 [extractor/yappy] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/yappy.py
Labels: site-request

#6089 [utils] Fix race condition in `make_dir`
  yt_dlp/cache.py
  yt_dlp/utils.py
Labels: bug

#6092 [extractor/anchor.fm] Add Episode Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/anchorfm.py
Labels: site-request

#6094 [extractor/hypergryph] Add MonsterSirenHypergryphMusic extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/hypergryph.py
Labels: site-request

#6041 Fix/SportDeutschland extractor
  yt_dlp/extractor/sportdeutschland.py
Labels: site-bug

#6005 updated path extension replace in ffmpeg postproc
  yt_dlp/__init__.py
  yt_dlp/postprocessor/ffmpeg.py
Labels: bug

#5983 [extractor/boxcast] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/boxcast.py
Labels: site-request

#5837 [extractor/tempo] Add IVXPlayer extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tempo.py
Labels: site-request

#5950 [extractor/tencent]: Add more formats and info
  yt_dlp/extractor/tencent.py
Labels: site-enhancement, needs-testing
