Repository yt-dlp/yt-dlp, pull requests merged in 2023-03, with the labels that each got.

#6301 [youtube:comments] Detect comment section loop
  yt_dlp/extractor/youtube.py
Labels: site-bug

#6291 [extractor/iprima] fix token retrieval, fix extractor
  yt_dlp/extractor/iprima.py
Labels: site-bug

#6403 [extractor/ntvru] Extract HLS and DASH formats
  yt_dlp/extractor/ntvru.py
Labels: site-enhancement

#6401 [extractor/mediastream] Support WinSports URLs without IDs
  yt_dlp/extractor/mediastream.py
Labels: site-bug

#6402 [extractor/yle_areena] Extract non-Kaltura videos
  yt_dlp/extractor/yle_areena.py
Labels: site-bug

#6414 [xvideos] Added support for quickies
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/xvideos.py
Labels: NSFW, site-enhancement

#6316 [Prankcast] Tags are no longer a JSON list
  yt_dlp/extractor/prankcast.py
Labels: site-bug

#6437 [extractor/teamcoco] Fix extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/teamcoco.py
Labels: site-bug

#6231 [extractor/nubilesporn] Add NubilesPorn extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nubilesporn.py
Labels: site-request, NSFW

#6445 [extractor/chilloutzone] Fix extractor
  yt_dlp/extractor/chilloutzone.py
Labels: site-bug

#6037 [postprocessor/ffmpeg] Handle chapters if duration is not known
  yt_dlp/postprocessor/ffmpeg.py
  yt_dlp/postprocessor/modify_chapters.py
Labels: bug

#6371 [extractor/opencast] Add ltitools interface to OpencastPlaylistIE and fix Tests
  yt_dlp/extractor/opencast.py
Labels: site-bug

#6254 [extractor/youtube] Add the first 3 characters of client name in `format_note`
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#6379 [extractor/LastFM]: Playlist pagination broken
  yt_dlp/extractor/lastfm.py
Labels: site-bug

#6502 [extractor/medaltv] Fix medal.tv clips URL (#6489)
  yt_dlp/extractor/medaltv.py
Labels: site-bug

#6383 [extractor/jwplatform] Updated jwplatform _extract_embed_urls and tests
  yt_dlp/extractor/jwplatform.py
Labels: site-bug

#6516 Add beta.nebula.tv to Nebula extractor
  yt_dlp/extractor/nebula.py
Labels: site-enhancement, pending-fixes

#6510 [youtube] Check for incomplete data in watch initial data
  yt_dlp/extractor/youtube.py
Labels: site-bug

#6523 [extractor/youtube] Fix parsing `comment_count` with unit suffix
  yt_dlp/extractor/youtube.py
Labels: site-bug

#6426 [extractor/mediastream] Improve `WinSportsVideo` and embed extraction
  yt_dlp/extractor/mediastream.py
Labels: site-bug

#6474 [extractor/genius] Add support for articles
  yt_dlp/extractor/genius.py
Labels: site-bug

#6520 [extractor/tiktok] Improve `TikTokLive` extractor
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#6552 [extractor/drtv] Fix video id parsing on radio pages
  yt_dlp/extractor/drtv.py
Labels: site-bug

#6557 [extractor/iwara] Overhaul extractors
  yt_dlp/extractor/iwara.py
Labels: site-bug

#6590 [extractor/rozhlas] Extract manifest formats
  yt_dlp/extractor/rozhlas.py
Labels: site-bug

#6567 [extractor/generic] Add extractor-args `hls_key` and `variant_query`
  README.md
  yt_dlp/extractor/generic.py
Labels: enhancement

#6604 [extractor/cbs] Add `ParamountPressExpress` extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/brightcove.py
  yt_dlp/extractor/cbs.py
Labels: site-request

#6601 [extractor/telecaribe] Expand livestream support
  yt_dlp/extractor/telecaribe.py
Labels: site-bug

#6613 [extractor/pgatour] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/pgatour.py
Labels: site-request

#6614 [extractor/hollywoodreporter] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/hollywoodreporter.py
Labels: site-request

#6615 [extractor/tiktok] Fix slideshow mp3 formats
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#6623 [utils] `js_to_json`: Implement template strings
  test/test_utils.py
  yt_dlp/utils.py
Labels: enhancement

#6636 [extractor/triller] Support short URLs, detect removed videos
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/triller.py
Labels: site-bug

#6637 [extractor/nbc] Fix `NBCStations` direct mp4 formats
  yt_dlp/extractor/nbc.py
Labels: site-bug

#6641 [extractor/iwara] Detect private video
  yt_dlp/extractor/iwara.py
Labels: site-enhancement

#6647 [postprocessor/EmbedThumbnail,postprocessor/FFmpegMetadata] Fix potential error on attaching thumbnails and info json for mkv/mka
  yt_dlp/postprocessor/embedthumbnail.py
  yt_dlp/postprocessor/ffmpeg.py
Labels: bug
