Repository yt-dlp/yt-dlp, pull requests merged in 2023-06, with the labels that each got.

#7180 [extractor/nhk] merge YouTube-dl changes for NHK
  yt_dlp/extractor/nhk.py
  yt_dlp/extractor/piksel.py
Labels: site-bug

#7200 [extractor/twitch] Update and add extractor-arg for `_CLIENT_ID`
  README.md
  yt_dlp/extractor/twitch.py
Labels: site-bug

#6244 [vrtnu] Fix extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/canvas.py
  yt_dlp/extractor/ketnet.py
  yt_dlp/extractor/vrt.py
Labels: site-bug

#7218 [extractor/substack] Fix extraction
  yt_dlp/extractor/substack.py
Labels: site-bug

#7219 [extractor/tencent] Fix fatal metadata extraction
  yt_dlp/extractor/tencent.py
Labels: site-bug

#7220 [extractor/sverigesradio] Support slug URLs
  yt_dlp/extractor/sverigesradio.py
Labels: site-bug

#7222 [extractor/foxnews] Fix extractors
  yt_dlp/extractor/amp.py
  yt_dlp/extractor/foxnews.py
Labels: site-bug

#7223 [extractor/sonyliv] Fix login with token
  yt_dlp/extractor/sonyliv.py
Labels: site-bug

#7224 [extractor/shemaroome] Pass `stream_key` header to downloader
  yt_dlp/extractor/shemaroome.py
Labels: site-bug

#7225 [extractor/hotstar] Support `/shows/` URLs
  yt_dlp/extractor/hotstar.py
Labels: site-bug

#7228 [extractor/tiktok] Extract 1080p formats
  yt_dlp/extractor/tiktok.py
Labels: site-enhancement

#7129 [extractor/rozhlas] Add `MujRozhlas` extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/rozhlas.py
Labels: site-request

#7257 [extractor/lbry] Extract original quality formats
  yt_dlp/extractor/lbry.py
Labels: site-enhancement

#7258 [extractor/twitter] Add login support
  yt_dlp/extractor/twitter.py
Labels: site-enhancement

#7227 [extractor/voot] Fix extractor
  yt_dlp/extractor/voot.py
Labels: site-bug

#6091 [extractor/Dumpert] Fix videos downloading as m3u8 files and added new-style valid URLs
  yt_dlp/extractor/dumpert.py
Labels: site-bug, pending-fixes, stale-pr

#7217 [extractor/odnoklassniki] Fix formats extraction
  yt_dlp/extractor/odnoklassniki.py
Labels: site-enhancement, site-bug

#7280 [extractor/zee5] Fix extraction of new content
  yt_dlp/extractor/zee5.py
Labels: site-bug

#7237 [TikTok] Fix format resolution sorting
  yt_dlp/extractor/tiktok.py
Labels: site-enhancement

#7254 [extractor/zaiko] Adding new extractor for zaiko.io
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/zaiko.py
Labels: site-request

#7291 add funker530 extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/funker530.py
  yt_dlp/extractor/rumble.py
Labels: site-request

#7309 [extractor/urplay] Support multi-langguage subtitles
  yt_dlp/extractor/urplay.py
  yt_dlp/utils/_utils.py
Labels: site-enhancement

#6624 [extractor/discogs] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/discogs.py
Labels: site-request

#6579 [extractor/ettutv] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/ettutv.py
Labels: site-request

#7306 stripchat: update m3u8 url
  yt_dlp/extractor/stripchat.py
Labels: NSFW, site-bug, pending-review

#5649 [extractor/tv4] Fix tv4 extraction
  yt_dlp/extractor/tv4.py
Labels: geo-blocked, site-bug, pending-review

#7137 [extractor/iwara] Fix and improve authentication
  yt_dlp/extractor/iwara.py
Labels: NSFW, site-bug, pending-review

#7332 [extractor/nhk] add NHK Radiru Live IE
  README.md
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nhk.py
Labels: site-request

#7346 [extractor/yappy] Support /profile/ URLs
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/yappy.py
Labels: site-enhancement

#7347 [extractor/zaiko] Add support for eticket links on zaiko.io
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/zaiko.py
Labels: site-enhancement, pending-review

#6682 [options] Add authentication option `netrc-cmd`
  README.md
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/extractor/common.py
  yt_dlp/options.py
  yt_dlp/utils/_utils.py
Labels: enhancement

#7304 [extractor/dropout] Dropout season pagination
  yt_dlp/extractor/dropout.py
Labels: site-bug

#7156 [nebula] change to new API URL, fix up tests
  yt_dlp/extractor/nebula.py
Labels: site-bug, pending-review

#7211 [extractor/motherless] Adding Gallery and fixing
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/motherless.py
Labels: site-request, NSFW, pending-review

#7360 [extractor/dplay] GlobalCyclingNetworkPlus: Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/dplay.py
Labels: site-request

#7311 [extractor/rheinmaintv] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/rheinmaintv.py
Labels: site-request

#7420 [extractor/qdance] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/qdance.py
Labels: site-request

#7439 Modify the regular expression so that it allows downloading videos wi…
  yt_dlp/extractor/crunchyroll.py
Labels: site-bug, pending-review

#7434 [extractor/abc] Fix #6433 by add 2 re patterns
  yt_dlp/extractor/abc.py
Labels: site-bug, pending-review

#7432 [extractor/stacommu] Add extractors
  README.md
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/stacommu.py
  yt_dlp/extractor/wrestleuniverse.py
Labels: site-request
