Repository yt-dlp/yt-dlp, pull requests merged in 2023-05, with the labels that each got.

#6957 [extractor/twitter] Migrate to GraphQL, handle auth errors
  README.md
  yt_dlp/extractor/twitter.py
Labels: site-bug

#6697 [extractor/dlf] Add support for Deutschlandfunk
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/dlf.py
Labels: site-request

#6978 [extractor/clipchamp] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/clipchamp.py
Labels: site-request

#6856 [extractor/Facebook] fix: Username getting and liveViewerCount
  yt_dlp/extractor/facebook.py
Labels: site-bug

#6982 [extractor/wrestleuniverse] Fix extraction, add login
  README.md
  yt_dlp/extractor/wrestleuniverse.py
Labels: site-enhancement, site-bug

#6904 [core] Implement `--color` flag
  README.md
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/downloader/common.py
  yt_dlp/options.py
Labels: enhancement

#6237 [extractor/crunchyroll] Rewrite internals and endpoint usage
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/crunchyroll.py
Labels: site-enhancement

#6505 [bibeltv] new implementation
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/bibeltv.py
Labels: site-enhancement

#7100 [extractor/youtube] extract viewership heatmap for info-json
  yt_dlp/extractor/common.py
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#7108 Add support for cc.com movies
  yt_dlp/extractor/comedycentral.py
Labels: site-enhancement

#7091 [cookies] Move `YouTubeDLCookieJar` to `cookies.py`
  test/test_YoutubeDLCookieJar.py
  yt_dlp/YoutubeDL.py
  yt_dlp/cookies.py
  yt_dlp/extractor/common.py
  yt_dlp/utils/_legacy.py
  yt_dlp/utils/_utils.py
Labels: enhancement

#7124 Weyyak latest
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/weyyak.py
Labels: site-request

#5948 [polskieradio] category fixes, tag support
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/polskieradio.py
Labels: site-enhancement

#5966 [daftsex] fix: update domain and embed player url
  yt_dlp/extractor/daftsex.py
Labels: NSFW, site-bug

#6140 [extractor/wykop] new extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/wykop.py
Labels: site-request

#5940 [extractor/rai] General overhaul of the extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/rai.py
Labels: site-enhancement

#6324 Livstream: support for downloading videos with account id
  yt_dlp/extractor/livestream.py
Labels: site-enhancement

#6367 [extractor/zingmp3]: add Hub extractor and update secretKey and apiKey
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/zingmp3.py
Labels: site-enhancement, site-bug

#6533 [extractor/owncloud] New Extractor for Owncloud
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/owncloud.py
Labels: site-request

#6528 [extractor/playsuisse] fix new url format
  yt_dlp/extractor/playsuisse.py
Labels: site-enhancement, pending-fixes

#6732 [extractor/idolplus] New extractor for idolplus.com
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/idolplus.py
Labels: site-request

#6781 [extractor/cbc] Workaround CBC returning a http 426 when querying file data
  yt_dlp/extractor/cbc.py
Labels: site-bug

#6783 [cookies] Add support for Safari custom cookies path
  yt_dlp/cookies.py
Labels: enhancement

#6896 [extractor/dacast] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/dacast.py
Labels: site-request

#6252 [extractor/JStream] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/jstream.py
Labels: site-request

#5764 [extractor/niconico:live] Add extractor
  yt_dlp/downloader/__init__.py
  yt_dlp/downloader/niconico.py
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/niconico.py
Labels: enhancement, site-request

#6681 [extractor/cbsnews] Overhaul extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/anvato.py
  yt_dlp/extractor/cbslocal.py
  yt_dlp/extractor/cbsnews.py
Labels: site-bug

#6844 [RottenTomatoes] fix: update rotten tomatoes regex and extraction
  yt_dlp/extractor/rottentomatoes.py
Labels: site-bug

#7003 [extractor/nekohacker] Add Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nekohacker.py
Labels: site-request

#7163 Support for Mzaalo
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mzaalo.py
Labels: site-request

#7168 [Crtvg] Add Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/crtvg.py
Labels: site-request

#7171 [extractor/bravotv] Detect DRM
  yt_dlp/extractor/bravotv.py
Labels: site-bug

#6297 [recurbate.com] Add recurbate extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/recurbate.py
Labels: site-request, NSFW

#7148 [extractor/youtube:comments] Deep check response for incomplete data
  yt_dlp/extractor/youtube.py
Labels: site-bug
