Repository yt-dlp/yt-dlp, pull requests merged in 2023-07, with the labels that each got.

#7358 [extractor/vkplay] Adding new extractor for vkplay.live
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/vk.py
Labels: site-request, pending-review

#7395 [googledrive] Fix missing "source" format
  yt_dlp/extractor/googledrive.py
Labels: site-bug

#7512 [extractor/twitter:spaces] Fix extraction
  yt_dlp/extractor/twitter.py
Labels: site-bug

#7476 [extractor/twitter] Fix unauthenticated extraction
  README.md
  yt_dlp/extractor/twitter.py
Labels: site-bug

#7497 Add CodeQL workflow
  .github/workflows/codeql.yml
Labels: docs/meta/cleanup

#7516 [extractor/twitter] Improve unauthenticated extraction
  yt_dlp/extractor/twitter.py
Labels: site-enhancement, pending-review

#7337 [extractor/Bilibili] Fixed bilibili bangumi extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/bilibili.py
Labels: site-bug, pending-review

#7519 Update vrt.py
  yt_dlp/extractor/vrt.py
Labels: site-bug

#7556 Fixes for clean_podcast_url()
  test/test_utils.py
  yt_dlp/utils/_utils.py
Labels: bug

#7592 fix: Update piapro tests and content url scheme
  yt_dlp/extractor/piapro.py
Labels: site-enhancement

#6621 [youtube:tab] Detect looping feeds
  yt_dlp/extractor/youtube.py
Labels: site-bug

#5138 Feat: add color to '* has already been recorded in the archive' message
  yt_dlp/YoutubeDL.py
Labels: enhancement, hacktoberfest-accepted

#7591 [extractor/pornhub] Fix download error in UK.
  yt_dlp/extractor/pornhub.py
Labels: NSFW, site-bug

#7564 [extractor/facebook] Fix Reels Format
  yt_dlp/extractor/facebook.py
Labels: site-bug

#7550 [ie/twitter:spaces] Fix format protocol
  yt_dlp/extractor/twitter.py
Labels: site-bug

#7648 [networking] Fix POST requests with 0-byte payloads
  test/test_networking.py
  yt_dlp/extractor/ettutv.py
  yt_dlp/networking/_urllib.py
  yt_dlp/networking/common.py
Labels: bug

#7645 [networking] Fix `--legacy-server-connect`
  test/test_networking.py
  yt_dlp/YoutubeDL.py
Labels: bug

#7616 [ie/MagellanTV] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/magellantv.py
Labels: site-request

#7614 [ie/MuseAI] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/museai.py
Labels: site-request

#7632 [ie/crunchyroll] Remove initial state scrape
  yt_dlp/extractor/crunchyroll.py
Labels: site-enhancement, site-bug, needs-testing

#7655 [fd/external] Fix ffmpeg input from stdin
  test/test_downloader_external.py
  yt_dlp/downloader/external.py
Labels: bug

#7664 [ie/PatreonCampaign] Fix extraction
  yt_dlp/extractor/patreon.py
Labels: site-bug

#7604 [networking/rh] Add strict extension checking
  test/test_networking.py
  yt_dlp/networking/_urllib.py
  yt_dlp/networking/common.py
Labels: enhancement

#7670 [ie/triller] Fix unlisted video extraction
  yt_dlp/extractor/triller.py
Labels: site-bug

#7667 [ie] Extract subtitles from SMIL manifests
  yt_dlp/extractor/common.py
  yt_dlp/extractor/livestream.py
  yt_dlp/extractor/mediaset.py
  yt_dlp/extractor/nbc.py
  yt_dlp/extractor/theplatform.py
Labels: enhancement, site-enhancement

#7704 [networking] Fix handling of unrelated invalid proxy urls from env
  test/test_networking.py
  yt_dlp/networking/common.py
  yt_dlp/utils/networking.py
Labels: bug, high-priority, regression

#7683 update(MotorTrendIE): #7680 _VALID_URL
  yt_dlp/extractor/dplay.py
Labels: site-bug

#7551 [extractor/wimbledon] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/wimbledon.py
Labels: site-request

#7710 [ie/hotstar] Support `/clips/` URLs
  yt_dlp/extractor/hotstar.py
Labels: site-bug

#7711 [ie/LBRY] Fix original format extraction
  yt_dlp/extractor/lbry.py
Labels: site-bug

#7712 [ie/tiktok] Fix audio-only format extraction
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#7621 [ie/twitter] Add fallback, improve error handling
  yt_dlp/extractor/twitter.py
Labels: site-bug

#7602 [extractor/pbskids] Add support for pbskids.org videos
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/pbs.py
Labels: site-request
