Repository yt-dlp/yt-dlp, pull requests merged in 2023-11, with the labels that each got.

#8339 [fd/dash] Force native downloader for `--live-from-start`
  yt_dlp/downloader/dash.py
Labels: bug

#8521 [core] Fix format sorting with `--load-info-json`
  yt_dlp/YoutubeDL.py
Labels: bug, regression

#8356 Add `--compat-option manifest-filesize-approx`
  README.md
  yt_dlp/YoutubeDL.py
  yt_dlp/options.py
Labels: enhancement, regression

#8383 [ie/twitter:broadcast] Update extraction
  yt_dlp/extractor/periscope.py
  yt_dlp/extractor/twitter.py
Labels: site-enhancement

#7847 [zoom] Fixed screen share and added combined video
  yt_dlp/extractor/zoom.py
Labels: site-enhancement, site-bug

#8326 Add sbs.co.kr extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/sbscokr.py
Labels: site-request

#8346 [ie/thisav] Remove
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/thisav.py
  yt_dlp/extractor/unsupported.py
Labels: docs/meta/cleanup

#8352 [ie/brilliantpala] Fix login detection when using Cookies
  yt_dlp/extractor/brilliantpala.py
Labels: site-bug

#8368 [nova.py] Added support for mediatn embed URLs.
  yt_dlp/extractor/nova.py
Labels: site-bug

#8386 Rewrite OnDemandKorea Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/ondemandkorea.py
Labels: site-bug

#8388 NHK metadata fixes/improvements
  yt_dlp/extractor/nhk.py
Labels: site-enhancement, site-bug

#8412 [laxarxames] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/laxarxames.py
Labels: site-request

#8463 [extractor/weibo] Fix visitor request
  yt_dlp/extractor/weibo.py
Labels: site-bug

#8561 [ie/thisoldhouse] Add login support
  yt_dlp/extractor/thisoldhouse.py
Labels: site-enhancement, site-bug

#8560 [ie/theatercomplextown] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/stacommu.py
Labels: site-request

#8475 [ie/twitter:broadcast] Support `--wait-for-video`
  yt_dlp/extractor/periscope.py
  yt_dlp/extractor/twitter.py
Labels: site-enhancement

#8486 [ie/orf] Add extractor for sound.orf.at podcasts
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/orf.py
Labels: site-request

#8531 [ie/NeteaseMusic] more metadata
  yt_dlp/extractor/neteasemusic.py
Labels: site-enhancement

#8508 [RadioComercial] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/radiocomercial.py
Labels: site-request

#8414 Fix n-tv.de extractor, website format has changed
  yt_dlp/extractor/ntvde.py
Labels: site-bug

#8582 [ie] Do not test truth value of `xml.etree.ElementTree.Element`
  yt_dlp/extractor/cbc.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/mtv.py
  yt_dlp/extractor/nbc.py
  yt_dlp/extractor/slideslive.py
Labels: docs/meta/cleanup

#8510 [cleanup] Misc. (for 2023-11 release)
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  devscripts/changelog_override.json
  yt_dlp/extractor/la7.py
  yt_dlp/extractor/redtube.py
  yt_dlp/extractor/videoken.py
  yt_dlp/extractor/youtube.py
  yt_dlp/networking/_requests.py
Labels: docs/meta/cleanup

#8576 [ie/beatbump] Add new domain and update tests
  yt_dlp/extractor/beatbump.py
Labels: site-bug

#4209 Update tv5mondeplus.py to detect subtitles
  yt_dlp/extractor/tv5mondeplus.py
Labels: site-enhancement

#8484 [DRTV extractor] Fix drtv.py
  yt_dlp/extractor/drtv.py
Labels: site-bug

#8216 [eltrecetv] Add new extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/eltrecetv.py
Labels: site-request

#8307 [JioSaavn] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/jiosaavn.py
Labels: site-request

#8454 [ZenYandex] Fix downloader
  yt_dlp/extractor/yandexvideo.py
Labels: site-bug

#7692 [extractor/dailymotion] Update URL regex and fix unit tests
  yt_dlp/extractor/dailymotion.py
Labels: site-bug

#8570 [njpwworld] service moved to brightcove with DRM
  supportedsites.md
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/njpwworld.py
  yt_dlp/extractor/unsupported.py
Labels: docs/meta/cleanup

#8574 [extractor/twitcasting] Twitcasting Live webpage changed
  yt_dlp/extractor/twitcasting.py
Labels: site-bug

#8586 [ie/abc.net.au:iview:showseries] Fix extraction
  yt_dlp/extractor/abc.py
Labels: site-bug

#8585 [build] Make `secretstorage` an optional dependency
  .github/workflows/build.yml
  .github/workflows/release.yml
  requirements.txt
Labels: docs/meta/cleanup, high-priority

#8361 Remove Python 3.7 support
  .github/workflows/build.yml
  .github/workflows/core.yml
  .github/workflows/download.yml
  .github/workflows/quick-test.yml
  CONTRIBUTING.md
  README.md
  setup.cfg
  setup.py
  test/test_update.py
  yt_dlp/__init__.py
  yt_dlp/compat/functools.py
  yt_dlp/update.py
Labels: docs/meta/cleanup

#8590 [ie/drtv] Set ext for m3u8 extraction
  yt_dlp/extractor/drtv.py
Labels: site-bug

#7189 [extractor/zingmp3]: add live radio extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/zingmp3.py
Labels: site-request

#8291 [ie/altcensored] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/altcensored.py
Labels: site-request

#8542 [duoplay] Add Duoplay extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/duoplay.py
Labels: site-request

#8609 [ie/nintendo] Fix Nintendo Direct extraction
  yt_dlp/extractor/nintendo.py
Labels: site-bug

#8612 [ie/vidly] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/vidly.py
Labels: site-request

#8600 [twitter] concurrent view count for live streams & username
  yt_dlp/extractor/periscope.py
Labels: site-enhancement

#8606 [ie/vocaroo] change getheader to headers.get
  yt_dlp/extractor/vocaroo.py
Labels: site-bug

#8504 [ie] Extract info from <media> elements in SMIL manifest
  yt_dlp/extractor/common.py
Labels: enhancement

#8535 [TheGuardian] Add Extractor for podcasts
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/theguardian.py
Labels: site-request

#8601 [extractor/twitcasting] Changed to detect live streaming from show page
  yt_dlp/extractor/twitcasting.py
Labels: site-bug

#8614 [ci] Concurrency optimizations
  .github/workflows/core.yml
  .github/workflows/release-master.yml
Labels: docs/meta/cleanup

#8343 [extractor/bilibili] Support interactive videos and course videos
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/bilibili.py
Labels: site-request

#8615 [ie/vvvvid] fix user agent and tests
  yt_dlp/extractor/vvvvid.py
Labels: site-bug

#8274 [Allstar] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/allstar.py
Labels: site-request

#8566 [ie/nebula] Finish Refactor
  test/helper.py
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nebula.py
Labels: site-enhancement

#7720 [rh:websockets] Migrate websockets to networking framework
  requirements.txt
  test/conftest.py
  test/test_networking.py
  test/test_socks.py
  test/test_websockets.py
  yt_dlp/YoutubeDL.py
  yt_dlp/downloader/niconico.py
  yt_dlp/extractor/fc2.py
  yt_dlp/extractor/niconico.py
  yt_dlp/networking/__init__.py
  yt_dlp/networking/_websockets.py
  yt_dlp/networking/websocket.py
  yt_dlp/utils/_legacy.py
  yt_dlp/utils/_utils.py
Labels: enhancement

#8607 [ie/abematv] Fix season extraction
  yt_dlp/extractor/abematv.py
Labels: site-bug

#8385 Add `NO_COLOR` environment variable support
  yt_dlp/YoutubeDL.py
Labels: enhancement

#8524 Improve documentation and usage of release_year
  README.md
  test/helper.py
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/archiveorg.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/harpodeon.py
  yt_dlp/extractor/monstercat.py
  yt_dlp/extractor/youtube.py
Labels: docs/meta/cleanup

#8296 [Facebook] Fix captions not included as subtitles
  yt_dlp/extractor/facebook.py
Labels: site-enhancement

#8639 [ie/floatplane] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/floatplane.py
Labels: site-request

#8647 [pp/FFmpegMetadata] Embed stream metadata in single format downloads
  yt_dlp/postprocessor/ffmpeg.py
Labels: bug

#8650 [ie/TwitCastingUser] Fix extraction
  yt_dlp/extractor/twitcasting.py
Labels: site-bug

#8651 [ie/bfmtv] Fix extractors
  yt_dlp/extractor/bfmtv.py
Labels: site-bug

#8649 [ie/box] Fix formats extraction
  yt_dlp/extractor/box.py
Labels: site-bug

#7681 [WebVTT] Allow spaces before newlines for CueBlock
  yt_dlp/webvtt.py
Labels: enhancement
