Repository yt-dlp/yt-dlp, pull requests merged in 2023-01, with the labels that each got.

#5553 Improve plugin architecture
  .gitignore
  README.md
  devscripts/make_lazy_extractors.py
  test/test_plugins.py
  test/testdata/yt_dlp_plugins/extractor/_ignore.py
  test/testdata/yt_dlp_plugins/extractor/ignore.py
  test/testdata/yt_dlp_plugins/extractor/normal.py
  test/testdata/yt_dlp_plugins/postprocessor/normal.py
  test/testdata/zipped_plugins/yt_dlp_plugins/extractor/zipped.py
  test/testdata/zipped_plugins/yt_dlp_plugins/postprocessor/zipped.py
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/extractors.py
  yt_dlp/options.py
  yt_dlp/plugins.py
  yt_dlp/postprocessor/__init__.py
  yt_dlp/utils.py
  ytdlp_plugins/extractor/__init__.py
  ytdlp_plugins/extractor/sample.py
  ytdlp_plugins/postprocessor/__init__.py
  ytdlp_plugins/postprocessor/sample.py
Labels: enhancement

#3724 [downloader/aria2c] Native progress for aria2c via RPC
  README.md
  yt_dlp/downloader/external.py
  yt_dlp/options.py
  yt_dlp/utils.py
Labels: enhancement

#5916 Misc. plugin improvements
  README.md
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/extractors.py
  yt_dlp/extractor/testurl.py
Labels: bug, docs/meta/cleanup

#5920 [extractor/odnoklassniki] Extract subtitles
  yt_dlp/extractor/odnoklassniki.py
Labels: site-enhancement

#5921 [extractor/fifa] Fix Preplay extraction
  yt_dlp/extractor/fifa.py
Labels: site-bug

#5922 [extractor/iqiyi] Fix `Iq` JS regex
  yt_dlp/extractor/iqiyi.py
Labels: site-bug

#5917 Add `--enable-file-urls`
  README.md
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/options.py
Labels: enhancement

#5637 [extractor/TikTok] Add `TikTokLiveIE` to download Live Stream
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tiktok.py
Labels: site-enhancement

#5952 Update nbc extractor with update to ThePlatform query parameter
  yt_dlp/extractor/nbc.py
Labels: site-bug

#5644 [extractor/drtv] Add series and season support for DRTV extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/drtv.py
Labels: site-request

#5685 [extractor/reddit] Add the name of the subreddit as channel
  yt_dlp/extractor/reddit.py
Labels: site-enhancement

#5670 [extractor/youtube] Retry manifest refresh to avoid ending download early when live stream is temporarily offline
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#5687 [extractor/crunchyroll] Add language filter for playlist
  yt_dlp/extractor/crunchyroll.py
Labels: site-enhancement

#5969 [xanimu] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/xanimu.py
Labels: site-request, NSFW, pending-fixes

#5951 [rozhlas] Support the site update
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/rozhlas.py
Labels: site-request

#6034 [extractor/drtv] Fix bug in `ab4cbef`
  yt_dlp/extractor/drtv.py
Labels: site-bug

#6033 [extractor/nbc] Fix `NBC` and `NBCStations` extractors
  yt_dlp/extractor/common.py
  yt_dlp/extractor/nbc.py
Labels: site-bug

#6024 [extractor/slideslive] Fix thumbnails and chapters/duration
  yt_dlp/extractor/common.py
  yt_dlp/extractor/slideslive.py
Labels: site-bug

#6118 [utils] Fix `time_seconds` to use the provided TZ
  yt_dlp/utils.py
Labels: bug
