Repository yt-dlp/yt-dlp, pull requests merged in 2023-09, with the labels that each got.

#7789 [svt] Fix download of wrong episode and update test
  yt_dlp/extractor/svt.py
Labels: site-bug, pending-review

#7890 [extractor/Facebook] fix: Changed json data retrieval
  yt_dlp/extractor/facebook.py
Labels: site-bug, pending-review

#7776 S4C extractor:Add subtitles, thumbnail, and ability to download a series.
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/s4c.py
Labels: site-request, site-enhancement, pending-review

#7979 [WDR] Update extractor to fit the current markup
  yt_dlp/extractor/wdr.py
Labels: site-bug

#8016 [ie/twitter] Fix retweet extraction & remove broken fallback
  README.md
  yt_dlp/extractor/twitter.py
Labels: site-bug, pending-review

#8114 update mixcloud api url
  yt_dlp/extractor/mixcloud.py
Labels: site-bug, pending-review

#8046 [extractor/AbemaTV] Fix adding proxy parameters (fixes #8036)
  yt_dlp/extractor/abematv.py
Labels: site-bug, regression

#8059 Banbye support for URL's containing a hyphen
  yt_dlp/extractor/banbye.py
Labels: site-bug

#8094 [ie/Axs] new extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/axs.py
Labels: site-request

#8086 [Mediaklikk] Fix extractor (fixes #8053)
  yt_dlp/extractor/mediaklikk.py
Labels: site-bug

#8003 [extractor/videa] #7427: Fix broken URL.
  yt_dlp/extractor/videa.py
Labels: site-bug, pending-review

#7952 [tv5mondeplus] fix extractor
  yt_dlp/extractor/tv5mondeplus.py
Labels: site-bug

#8119 [ie/bpb] Support more urls and extract more metadata
  yt_dlp/extractor/bpb.py
  yt_dlp/utils/_utils.py
Labels: site-bug

#8120 [extractor/TwitCasting] expand extractor regex
  yt_dlp/extractor/twitcasting.py
Labels: site-bug

#7689 [extractor/cbc] Fix upgrade required
  yt_dlp/extractor/cbc.py
Labels: site-bug

#7555 [extractor/bilibili] add format_id
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement

#8103 [amazonminitv] Fix extraction
  yt_dlp/extractor/amazonminitv.py
Labels: site-bug

#8102 Fixes the issue #7575 [Nitter] unable to extract OpenGraph description
  yt_dlp/extractor/nitter.py
Labels: site-bug

#8054 [ie/zaiko] add thumbnails from event pages
  yt_dlp/extractor/zaiko.py
Labels: site-enhancement

#8040 [extractor/Funker530] fix: funker530 rumble embed link extraction and video download
  yt_dlp/extractor/funker530.py
  yt_dlp/extractor/rumble.py
Labels: site-bug

#8035 [extractor/Rumble] fix: updated field extraction
  yt_dlp/extractor/rumble.py
Labels: site-enhancement, site-bug

#8032 [ie/Bild.de] fix extraction when HLS formats are available (fixes #7951)
  yt_dlp/extractor/bild.py
Labels: site-bug

#7628 [extractor/sohu] Fix for unsupported base64-encoded url
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/sohu.py
Labels: site-bug

#8074 [ie/facebook] improve format sorting
  yt_dlp/extractor/facebook.py
Labels: site-enhancement

#7788 [BBC Sounds] Tracklist Extraction
  yt_dlp/extractor/bbc.py
Labels: site-enhancement

#8132 [ie/web.archive:vlive] Remove extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/archiveorg.py
  yt_dlp/extractor/naver.py
Labels: docs/meta/cleanup

#8131 [ie/RTVSLO] Fix format extraction
  yt_dlp/extractor/rtvslo.py
Labels: site-bug

#8130 [core] Fix support for upcoming Python 3.12
  .github/workflows/core.yml
  devscripts/update-version.py
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/aws.py
  yt_dlp/extractor/goplay.py
  yt_dlp/extractor/motherless.py
  yt_dlp/extractor/panopto.py
  yt_dlp/networking/_urllib.py
  yt_dlp/networking/exceptions.py
  yt_dlp/utils/_utils.py
Labels: high-priority

#8124 [devscripts] `make_changelog`: Fix changelog groups and add networking
  devscripts/changelog_override.json
  devscripts/make_changelog.py
Labels: enhancement

#7117 [rule34video] Extract tags for videos
  yt_dlp/extractor/rule34video.py
Labels: NSFW, site-enhancement, pending-review

#7649 [ie/lecturio] fix .de site url regex
  yt_dlp/extractor/lecturio.py
Labels: site-bug, pending-review

#8129 [extractor/indavideo] Fix video extraction
  yt_dlp/extractor/indavideo.py
Labels: site-bug

#7813 [massengeschmacktv] Update extractor
  yt_dlp/extractor/massengeschmacktv.py
Labels: site-bug

#8065 [networking] Fix various bugs in socks proxy implementation
  test/test_socks.py
  yt_dlp/networking/_helper.py
  yt_dlp/networking/_urllib.py
  yt_dlp/socks.py
Labels: bug

#7006 [radiofrance] Add live stations, podcast, profile and program schedule extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/radiofrance.py
Labels: site-enhancement, pending-review

#7518 [extractor/bilibili] support mutiple playlists including series, favorites and watchlater
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement

#7657 [extractor/weibo] Rewrite to fix extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/weibo.py
Labels: site-bug

#7373 [N1] Fix extractor for new player
  yt_dlp/extractor/n1.py
Labels: site-bug

#7386 [Pornbox] New extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/pornbox.py
Labels: site-request, NSFW

#8144 playlist_id should be case-sensitive #8138
  yt_dlp/extractor/ccc.py
Labels: site-bug

#8151 [ie/pr0gramm] Rewrite pr0gramm extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/pr0gramm.py
Labels: site-enhancement, site-bug

#8128 Update to ytdl-commit-66ab08
  README.md
Labels: docs/meta/cleanup

#5782 [extractor/eplus] Add extractor for URLs from "ib.eplus.jp"
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/eplus.py
Labels: site-request, pending-review

#7151 Add extractors for CaracolTvPlay and Canal1
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/canal1.py
  yt_dlp/extractor/caracoltv.py
  yt_dlp/extractor/mediastream.py
Labels: site-request, pending-review

#7652 [extractor/douyutv] fix broken DouyuTV and DouyuShow
  yt_dlp/extractor/douyutv.py
Labels: site-bug

#8142 [ie/bilibili] Extract Dolby Vision & Dolby Audio
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement

#8153 Add 'nyheter' and 'video-player/embed/' to the expressen regex
  yt_dlp/extractor/expressen.py
Labels: site-enhancement

#7910 [NovaEmbed] Fix extractor (handle new player)
  yt_dlp/extractor/nova.py
Labels: site-bug

#7216 [extractor/iprima] Fix extractor (relax nuxt function regex, add js_to_json hack)
  yt_dlp/extractor/iprima.py
Labels: enhancement, site-bug, pending-review

#7975 [extractor/TwitCasting] fix: Use UserNotLive
  yt_dlp/extractor/twitcasting.py
Labels: enhancement, site-bug

#8182 [cleanup] Misc
  CONTRIBUTING.md
  README.md
  devscripts/make_changelog.py
  test/test_YoutubeDL.py
  test/test_networking_utils.py
  yt_dlp/YoutubeDL.py
  yt_dlp/compat/urllib/__init__.py
  yt_dlp/extractor/abc.py
  yt_dlp/extractor/ign.py
  yt_dlp/extractor/nebula.py
  yt_dlp/extractor/peekvids.py
  yt_dlp/extractor/radiofrance.py
  yt_dlp/extractor/rcs.py
  yt_dlp/extractor/rokfin.py
  yt_dlp/extractor/s4c.py
  yt_dlp/extractor/sovietscloset.py
  yt_dlp/extractor/youtube.py
  yt_dlp/networking/__init__.py
  yt_dlp/networking/_urllib.py
  yt_dlp/networking/exceptions.py
Labels: docs/meta/cleanup, pending-review

#8133 Add Monstercat extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/monstercat.py
Labels: site-request

#7903 [ie/PIAULIZAPortal] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/piaulizaportal.py
Labels: site-request

#8146 add Cineverse IEs
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/asiancrush.py
  yt_dlp/extractor/cineverse.py
Labels: site-request, geo-blocked

#5686 [extractor/niconicochannelplus] Add extractor
  README.md
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/niconicochannelplus.py
Labels: site-request

#6680 [brilliantpala] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/brilliantpala.py
Labels: site-request

#7838 [ie/nfl.com:plus:replay] Fix extractor
  README.md
  yt_dlp/extractor/nfl.py
Labels: site-bug, pending-review

#8183 [core] Update minimum recommended Python version
  devscripts/changelog_override.json
  test/test_execution.py
  yt_dlp/YoutubeDL.py
  yt_dlp/update.py
Labels: docs/meta/cleanup
