Repository yt-dlp/yt-dlp, pull requests merged in 2023-04, with the labels that each got.

#6714 [extractor/youtube] Fix comment loop detection for pinned comments
  yt_dlp/extractor/youtube.py
Labels: site-bug

#6690 Fix youku extractor
  yt_dlp/extractor/youku.py
Labels: site-bug

#6741 [extractor/zoom] Update extraction logic
  yt_dlp/extractor/zoom.py
Labels: site-bug

#5945 [extractor/gmanetwork] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/gmanetwork.py
Labels: site-request

#6079 [extractor/biliIntl] Add comment extraction
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement

#6106 [BrainPOP] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/brainpop.py
Labels: site-request

#6651 Fix iwara quality selection
  yt_dlp/extractor/iwara.py
Labels: site-bug

#6789 [extractor/zoom] Fix share URL extraction
  yt_dlp/extractor/zoom.py
Labels: site-bug

#6777 [extractor/tiktok] Fix and improve metadata extraction
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#6778 [FFmpegFixupM3u8PP] Fix postprocessing for non-AAC audio codecs
  yt_dlp/postprocessor/ffmpeg.py
Labels: bug

#6775 [extractor/generic] Attempt to detect live HLS
  README.md
  yt_dlp/extractor/generic.py
Labels: enhancement

#6384 [youtube] Redefine uploader metadata
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#6825 [extractor/reddit] Support cookies and short URLs
  yt_dlp/extractor/reddit.py
Labels: site-bug

#6817 [extractor/gronkh] add duration and chapters
  yt_dlp/extractor/gronkh.py
Labels: site-enhancement

#6803 [extractor/whyp] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/whyp.py
Labels: site-request

#6792 [pornez] Issues with missing url video id
  yt_dlp/extractor/pornez.py
Labels: NSFW, site-bug

#6838 [extractor/stageplus] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/stageplus.py
Labels: site-request

#6547 [extractor/bilibili] Support festival videos
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#6839 [extractor/sbs] Overhaul extractor for new APIs
  yt_dlp/extractor/sbs.py
  yt_dlp/utils.py
Labels: site-bug

#6819 [extractor/nhk] Add NHK Radiru (らじる) extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nhk.py
Labels: site-request

#6868 [extractor/wevidi] Add support for WeVidi
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/wevidi.py
Labels: site-request

#6629 [extractor/twitch] Update thumbnail size
  yt_dlp/extractor/twitch.py
Labels: site-bug

#6685 [extractor/pornhub][fix] fix changed ageverification cookie
  yt_dlp/extractor/pornhub.py
Labels: NSFW, site-bug, patch-available

#6625 [extractor/cbc] Fix livestream downloading and playlist URL regex
  yt_dlp/extractor/cbc.py
Labels: site-bug

#6950 [extractor/reddit] Add login support
  yt_dlp/extractor/reddit.py
Labels: site-enhancement
