Repository yt-dlp/yt-dlp, pull requests merged in 2024-05, with the labels that each got.

#9800 [ie/wrestleuniverse] Avoid partial stream formats
  yt_dlp/extractor/wrestleuniverse.py
Labels: site-bug

#9821 [ie/soundcloud] Extract `genres`
  yt_dlp/extractor/soundcloud.py
Labels: site-bug

#9772 [ie/crunchyroll] Always make metadata available
  yt_dlp/extractor/crunchyroll.py
Labels: site-enhancement

#9850 [ie/patreon] Extract multiple embeds
  yt_dlp/extractor/patreon.py
Labels: site-bug

#9756 [networking] Add response extensions for impersonate info
  test/test_networking.py
  yt_dlp/networking/_curlcffi.py
  yt_dlp/networking/common.py
Labels: enhancement, networking

#9805 [core] Warn user when FFmpeg is missing
  yt_dlp/YoutubeDL.py
Labels: enhancement

#8827 [youporn] Fix extraction of video URLs
  yt_dlp/extractor/youporn.py
Labels: NSFW, site-bug

#9866 [cbc.ca] support new URL format (fixes #9825)
  yt_dlp/extractor/cbc.py
Labels: site-bug

#9857 [ie/crunchyroll] Add impersonation support
  yt_dlp/extractor/crunchyroll.py
Labels: site-enhancement, site-bug

#9522 [ie/Boosty] include auth token in API call if available
  yt_dlp/extractor/boosty.py
Labels: site-enhancement

#9860 [ie/mixch] Add comment extraction; update a test
  yt_dlp/extractor/mixch.py
Labels: site-enhancement

#9885 [ie/vk] Improve format extraction
  yt_dlp/extractor/vk.py
Labels: site-enhancement, site-bug

#9839 [ie/BilibiliSpace] better error message
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement

#9817 [ie/bilibili] apply geo-verification-proxy to webpage download
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement

#9813 [ie/yandexvideo] Fix extractor
  yt_dlp/extractor/yandexvideo.py
Labels: site-bug

#7019 [ie/Qub] Fix extractor
  yt_dlp/extractor/tva.py
Labels: site-bug

#9488 [ie/netease:program] Improve `--no-playlist` message
  yt_dlp/extractor/neteasemusic.py
Labels: site-bug

#9675 [ie/canalalpha] Fix extractor
  yt_dlp/extractor/canalalpha.py
Labels: site-bug

#9897 [ie/commonmistakes] Raise error on blob URLs
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/commonmistakes.py
Labels: enhancement

#9578 [test] Add http proxy tests
  test/conftest.py
  test/helper.py
  test/test_http_proxy.py
  test/test_networking.py
  test/test_websockets.py
  yt_dlp/networking/_curlcffi.py
Labels: bug, networking

#9650 Changes to NFB extractor to reflect recent site changes
  yt_dlp/extractor/nfb.py
Labels: site-bug

#9658 Fix alura extractor
  yt_dlp/extractor/alura.py
Labels: site-bug

#9672 [ie/hytale] Use CloudflareStreamIE explicitly
  yt_dlp/extractor/hytale.py
Labels: site-bug

#9747 Enable use of session cookies in chrome
  yt_dlp/cookies.py
Labels: enhancement

#9873 Suggest --list-subs when no matching subtitle format found (Resolve #9760)
  yt_dlp/YoutubeDL.py
Labels: enhancement

#9647 [ie/EuroParlWebstream] Support new URL format
  yt_dlp/extractor/europa.py
Labels: site-bug

#9143 [ie/TV5Monde] Fix extractor
  yt_dlp/extractor/tv5mondeplus.py
Labels: geo-blocked, site-bug

#9546 Add YouTube client for 1080p muxed videos
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#9911 [cleanup] Remove questionable extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/cableav.py
  yt_dlp/extractor/einthusan.py
  yt_dlp/extractor/jable.py
  yt_dlp/extractor/porn91.py
  yt_dlp/extractor/unsupported.py
  yt_dlp/extractor/xfileshare.py
  yt_dlp/extractor/yourporn.py
  yt_dlp/extractor/yourupload.py
Labels: docs/meta/cleanup

#9834 [ie/XVideosQuickies] Fix extractor
  yt_dlp/extractor/xvideos.py
Labels: NSFW, site-bug

#9908 [extractor/GoogleDrive] Add more supported types
  yt_dlp/extractor/googledrive.py
  yt_dlp/extractor/youtube.py
Labels: site-bug

#9914 [ie/pornhub] Update login to email
  yt_dlp/extractor/pornhub.py
Labels: NSFW, site-bug

#9855 [ie/eplus] Check if it's a pass ticket url; replace a dead url in test
  yt_dlp/extractor/eplus.py
Labels: site-bug

#9938 [ie/tiktok] Extract via mobile API only if `app_info` is passed
  README.md
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#9926 [ie/twitter] Support x.com URLs
  yt_dlp/extractor/twitter.py
Labels: site-bug

#9939 [extractor/cda] Fix age restriction
  yt_dlp/extractor/cda.py
Labels: site-bug

#9705 Issue 9701: NEXT_DATA field video extraction for bbc US website
  yt_dlp/extractor/bbc.py
Labels: site-bug

#9879 Apends the hash of the POST data to the dump file name with --write-pages
  yt_dlp/extractor/common.py
Labels: enhancement

#9649 [cookies] Add `--cookies-from-browser` support for Whale
  README.md
  yt_dlp/cookies.py
Labels: enhancement

#9553 [ie/youtube] Remove `android` from default clients
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-bug

#9906 [test] Fix connect timeout test
  test/test_networking.py
  test/test_websockets.py
  yt_dlp/networking/common.py
Labels: bug, networking

#9952 [ie/twitter] Fix auth for x.com migration
  yt_dlp/extractor/twitter.py
Labels: site-bug

#9982 [build] Exclude `requests` from `py2exe`
  README.md
  bundle/py2exe.py
Labels: docs/meta/cleanup

#9960 [ie/tiktok] Extract all web formats
  yt_dlp/extractor/tiktok.py
Labels: site-enhancement

#9992 [rh:requests] Patch support for `requests` 2.31+, 2.32.2+
  .github/workflows/build.yml
  README.md
  bundle/py2exe.py
  pyproject.toml
  yt_dlp/networking/_requests.py
Labels: bug, docs/meta/cleanup, networking

#9993 [build] `macos` job requires `setuptools<70`
  pyproject.toml
Labels: docs/meta/cleanup

#9961 [ie/tiktok] Fix subtitles extraction
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#10004 [ie/soundcloud] Add `formats` extractor-arg
  README.md
  yt_dlp/extractor/soundcloud.py
Labels: site-enhancement

#10005 [ie/crunchyroll] Fix stream extraction
  yt_dlp/extractor/crunchyroll.py
Labels: site-bug

#9945 [ie/ArteTV] Separate forced subtitle tracks
  yt_dlp/extractor/arte.py
Labels: site-enhancement

#9366 [ie/Moviepilot] Fix extractor
  yt_dlp/extractor/moviepilot.py
Labels: site-bug

#9539 [ie/Instagram] Support new reels URL format
  yt_dlp/extractor/instagram.py
Labels: site-bug

#9629 [ie/GodResource] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/godresource.py
Labels: site-request

#9641 [ie/NTSLive] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nts.py
Labels: site-request

#9677 [ie/orf:on] Improve extraction
  yt_dlp/extractor/orf.py
Labels: site-enhancement, site-bug

#9949 [ie/HearThisAt] Improve `_VALID_URL`
  yt_dlp/extractor/hearthisat.py
Labels: site-bug

#9788 [ie/brilliantpala] Fix login
  yt_dlp/extractor/brilliantpala.py
Labels: site-bug

#9776 [ie/taptap] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/taptap.py
Labels: site-request

#10011 [ie/ORFTVthek] Remove extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/orf.py
Labels: docs/meta/cleanup

#10024 [ie/tele5] Overhaul extractor
  yt_dlp/extractor/tele5.py
Labels: site-bug

#10026 [ie/jiocinema] Add extractors
  README.md
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/jiocinema.py
  yt_dlp/extractor/voot.py
Labels: site-request

#10021 [ie/dangalplay] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/dangalplay.py
Labels: site-request

#9311 [ie/Piapro] Fix extractor
  yt_dlp/extractor/piapro.py
Labels: site-bug

#9646 [ie/xiaohongshu] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/xiaohongshu.py
Labels: site-request

#10012 Backports from youtube-dl (2024-05)
  README.md
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/caffeinetv.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/gbnews.py
  yt_dlp/extractor/youporn.py
Labels: solved-upstream

#9856 [ie/youtube] Extract upload date timestamp if available
  README.md
  test/test_utils.py
  yt_dlp/extractor/youtube.py
  yt_dlp/options.py
  yt_dlp/utils/_utils.py
Labels: site-enhancement

#9661 [ie/tiktok:user] Fix extractor
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#9986 Add Tiktok collection support
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tiktok.py
Labels: site-enhancement

#10025 [ie/LCI] Fix extractor
  yt_dlp/extractor/lci.py
Labels: site-bug

#9765 [misc] Cleanup for 2024-05 release
  Makefile
  README.md
  devscripts/changelog_override.json
  devscripts/run_tests.bat
  devscripts/run_tests.sh
  pyinst.py
  setup.py
  test/test_InfoExtractor.py
  yt_dlp/extractor/ceskatelevize.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/thisvid.py
  yt_dlp/extractor/vk.py
  yt_dlp/utils/_utils.py
Labels: docs/meta/cleanup

#9225 [ie] Fix parsing of base URL in SMIL manifest
  yt_dlp/extractor/common.py
Labels: bug

#9223 [ie/Piksel] Update domain
  yt_dlp/extractor/piksel.py
Labels: site-bug

#10035 [ie/tiktok:user] Fix extraction loop
  yt_dlp/extractor/tiktok.py
Labels: high-priority, site-bug

#10043 [cleanup] Misc 2024.05.27
  README.md
  yt_dlp/options.py
Labels: docs/meta/cleanup

#10044 [peertube] add livestream support
  yt_dlp/extractor/peertube.py
Labels: site-enhancement

#9975 Fixed tubitv extractor
  yt_dlp/extractor/tubitv.py
Labels: site-bug

#10053 [ie/orf:on] Support segmented episodes
  yt_dlp/extractor/orf.py
Labels: site-enhancement

#10069 [build] Bump Pyinstaller to `>=6.7.0` for all builds
  .github/workflows/build.yml
  pyproject.toml
Labels: docs/meta/cleanup

#10070 [ie/PatreonCampaign] Fix `campaign_id` extraction
  yt_dlp/extractor/patreon.py
Labels: site-bug
