Repository yt-dlp/yt-dlp, pull requests merged in 2024-07, with the labels that each got.

#10055 [ie/laracasts] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/laracasts.py
Labels: site-request

#10314 [ie/orf:on] Allow downloading of video in segments
  README.md
  yt_dlp/extractor/orf.py
Labels: site-enhancement

#10319 [ie/pokergo] Make metadata extraction non-fatal
  yt_dlp/extractor/pokergo.py
Labels: site-bug

#10266 Add `playlist_channel` and `playlist_channel_id` fields
  README.md
  yt_dlp/YoutubeDL.py
Labels: enhancement

#10268 [ie/graspop] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/graspop.py
Labels: site-request

#9768 [ie/qqmusic] Fix QQMusic extractors for new URLs
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/qqmusic.py
Labels: site-bug

#10316 [ie/nuum] Pass Referer header to m3u8 playlists
  yt_dlp/extractor/nuum.py
Labels: site-bug

#9177 [ie/microsoftembed] Add extractors for dev materials
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/microsoftembed.py
  yt_dlp/extractor/microsoftvirtualacademy.py
Labels: site-request

#9117 [ie/bilibili] Add support for legacy formats
  README.md
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#10327 [ie/vimeo] Support browser impersonation
  yt_dlp/extractor/patreon.py
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#10075 [cleanup] Misc (for 2024.06.xx release)
  .github/workflows/build.yml
  CONTRIBUTING.md
  Collaborators.md
  README.md
  devscripts/changelog_override.json
  devscripts/cli_to_api.py
  pyproject.toml
  test/test_jsinterp.py
  test/test_youtube_signature.py
  yt_dlp/YoutubeDL.py
  yt_dlp/cookies.py
  yt_dlp/downloader/external.py
  yt_dlp/extractor/arcpublishing.py
  yt_dlp/extractor/arkena.py
  yt_dlp/extractor/bandcamp.py
  yt_dlp/extractor/brightcove.py
  yt_dlp/extractor/cbsnews.py
  yt_dlp/extractor/dailymail.py
  yt_dlp/extractor/eitb.py
  yt_dlp/extractor/eporner.py
  yt_dlp/extractor/go.py
  yt_dlp/extractor/hbo.py
  yt_dlp/extractor/hketv.py
  yt_dlp/extractor/instagram.py
  yt_dlp/extractor/iwara.py
  yt_dlp/extractor/nbc.py
  yt_dlp/extractor/nhl.py
  yt_dlp/extractor/peloton.py
  yt_dlp/extractor/performgroup.py
  yt_dlp/extractor/pr0gramm.py
  yt_dlp/extractor/prosiebensat1.py
  yt_dlp/extractor/tubetugraz.py
  yt_dlp/extractor/twitter.py
  yt_dlp/extractor/viewlift.py
  yt_dlp/extractor/weibo.py
  yt_dlp/extractor/wsj.py
  yt_dlp/extractor/yahoo.py
  yt_dlp/extractor/yandexdisk.py
  yt_dlp/extractor/youtube.py
  yt_dlp/networking/_websockets.py
  yt_dlp/options.py
  yt_dlp/postprocessor/ffmpeg.py
Labels: docs/meta/cleanup

#10336 [core] Fix `--compat-opt allow-unsafe-ext`
  yt_dlp/__init__.py
Labels: bug

#9249 [ie/murrtube] Fix extractor
  yt_dlp/extractor/murrtube.py
Labels: NSFW, site-bug

#10332 [ie/banbye] Fix extractor
  yt_dlp/extractor/banbye.py
Labels: site-bug

#10130 [ie/zaiko] Add support jwt-protected video urls
  yt_dlp/extractor/zaiko.py
Labels: site-bug

#10330 [cleanup] Misc (for 2024.07.xx hotfix release)
  .gitignore
  Changelog.md
  Makefile
  README.md
  devscripts/changelog_override.json
  yt_dlp/options.py
Labels: docs/meta/cleanup

#10345 [core] Fix `--ignore-no-formats-error`
  yt_dlp/utils/_utils.py
Labels: bug, regression

#10347 [ie/douyutv] Do not rely on a CDN under the control of a bad actor
  yt_dlp/extractor/douyutv.py
Labels: security

#10341 [ie/vimeo] Fix password-protected video extraction
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#10348 [ie/abematv] set availability
  yt_dlp/extractor/abematv.py
Labels: site-enhancement

#10155 [ie/vidyard] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/cellebrite.py
  yt_dlp/extractor/swearnet.py
  yt_dlp/extractor/vidyard.py
Labels: site-request

#10362 [core] Address gaps in allowed extensions
  yt_dlp/utils/_utils.py
Labels: bug, regression

#10379 [ie/yle_areena] Fix subtitle extraction
  yt_dlp/extractor/yle_areena.py
Labels: site-bug

#10380 [ie/yle_areena] Fix metadata extraction
  yt_dlp/extractor/yle_areena.py
Labels: site-bug

#10173 [ie/vtv] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/vtv.py
Labels: site-request

#10382 Bugfix/10369 jiosaavn playlist download
  yt_dlp/extractor/jiosaavn.py
Labels: site-enhancement

#10383 [cleanup] Misc
  devscripts/changelog_override.json
  yt_dlp/extractor/toggle.py
  yt_dlp/utils/_utils.py
Labels: docs/meta/cleanup

#10390 [ie/youtube] Fix failing nsig decoding for player `b22ef6e7`
  test/test_youtube_signature.py
  yt_dlp/extractor/youtube.py
Labels: bug, site-bug

#10389 [ie/soundcloud] Fix rate-limit handling
  yt_dlp/extractor/soundcloud.py
Labels: site-bug

#9862 [core] Fix `simulate` changing format selection
  README.md
  test/test_YoutubeDL.py
  yt_dlp/YoutubeDL.py
Labels: bug

#10401 [ie/youtube] Invalidate nsig cache from < 2024.07.09
  yt_dlp/extractor/youtube.py
Labels: site-bug

#10408 Bugfix for #10407: Alternative way to access room_id for TikTok lives
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#10417 [ie/tv5monde] Support browser impersonation
  yt_dlp/extractor/tv5mondeplus.py
Labels: site-bug

#10419 [ie/box] Support enterprise URLs
  yt_dlp/extractor/box.py
Labels: site-bug

#10430 [ie/tv5monde] Fix impersonation (Bugfix for 9b95a6765a5f6325af99c4aca961587f0c426e8c)
  yt_dlp/extractor/tv5mondeplus.py
Labels: site-bug

#10456 [ie/youtube] Avoid poToken experiment player responses
  yt_dlp/extractor/youtube.py
Labels: site-bug

#10448 [networking] Add `legacy_ssl` request extension
  test/test_networking.py
  test/test_websockets.py
  yt_dlp/networking/_curlcffi.py
  yt_dlp/networking/_requests.py
  yt_dlp/networking/_urllib.py
  yt_dlp/networking/_websockets.py
  yt_dlp/networking/common.py
Labels: enhancement, networking

#10414 [ie/Picarto] Fix failed to parse JSON error
  yt_dlp/extractor/picarto.py
Labels: site-bug

#10440 [ie/afreecatv] Fix login and use `legacy_ssl`
  yt_dlp/extractor/afreecatv.py
Labels: site-bug, regression

#10436 Fix Epidemic Sound SFX unsupported url
  yt_dlp/extractor/epidemicsound.py
Labels: site-bug

#10399 [ie/adn] domain change from .fr/.de to .com
  yt_dlp/extractor/adn.py
Labels: site-bug

#10464 [ie/youtube] Fix initial player response usage
  yt_dlp/extractor/youtube.py
Labels: site-bug

#10468 [ie/generic] Fix direct video link extensions
  yt_dlp/extractor/generic.py
Labels: site-bug, regression

#10463 [soundcloud] Change permalink extractor to more-expected behavior
  yt_dlp/extractor/soundcloud.py
Labels: site-enhancement

#10467 [ie/youtube] Reduce android client priority
  yt_dlp/extractor/youtube.py
Labels: site-bug

#10471 [ie/dplay] Fix extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/discovery.py
  yt_dlp/extractor/discoverygo.py
  yt_dlp/extractor/dplay.py
Labels: site-bug

#10454 [core] Fix `noprogress` if `test=True` with `--quiet` and `--verbose`
  yt_dlp/YoutubeDL.py
Labels: bug

#10453 [core] Support `auto-tty` and `no_color-tty` for `--color`
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/options.py
Labels: enhancement

#10486 [update] Fix network error handling
  yt_dlp/update.py
Labels: bug

#10487 [cleanup] Misc
  pyproject.toml
  yt_dlp/utils/_utils.py
Labels: docs/meta/cleanup

#10493 [build] Pin `setuptools` version
  pyproject.toml
Labels: docs/meta/cleanup

#10491 [ie/abematv] Migrate key retrieval to request handler framework
  yt_dlp/extractor/abematv.py
Labels: site-bug, regression, networking

#10542 [ie/youtube] Fix `n` function name extraction for player `3400486c`
  test/test_youtube_signature.py
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-bug

#10516 [ie/tiktok] Fix and deprioritize JSON subtitles
  yt_dlp/extractor/tiktok.py
Labels: site-bug, regression

#10544 [ie/vimeo] Fix chapters extraction
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#10531 [ie/facebook] Fix extraction
  yt_dlp/extractor/facebook.py
Labels: site-bug

#10515 [ie/MLBTV] Fix extractor
  yt_dlp/extractor/mlb.py
Labels: site-bug

#10566 [ie/DiscoveryPlus] Support olympics URLs
  yt_dlp/extractor/dplay.py
Labels: site-bug

#10567 [ie/tva] Fix extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tva.py
  yt_dlp/extractor/unsupported.py
Labels: site-bug

#10589 [utils] `unified_timestamp`: Recognize Sunday
  test/test_utils.py
  yt_dlp/utils/_utils.py
Labels: bug

#10569 [ie/abematv] fix episode availability extraction
  yt_dlp/extractor/abematv.py
Labels: site-bug

#10598 [ie/vimeo:review] Fix password-protected video extraction
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#10302 [ie/cbc.ca:player] Fix extractor
  yt_dlp/extractor/cbc.py
Labels: site-bug, pending-review

#10590 [ie/learningonscreen] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/learningonscreen.py
Labels: site-request

#10573 [ie/youtube] Player client maintenance
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-enhancement, site-bug

#10607 [ie/mlbtv] Fix makeup game extraction
  yt_dlp/extractor/mlb.py
Labels: site-bug

#10604 [ie/olympics] Fix extractor
  yt_dlp/extractor/olympics.py
Labels: site-bug

#10600 [ie/TVer] Add support for downloading Paris Olympic (2024) VOD
  yt_dlp/extractor/tver.py
Labels: site-enhancement, pending-fixes

#10605 [ie/mediaklikk] Fix extractor
  yt_dlp/extractor/mediaklikk.py
Labels: site-bug

#10611 [ie/youtube] Fix `n` function name extraction for player `20dfca59`
  test/test_youtube_signature.py
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-bug

#10610 [ie/youtube] Fix age-verification workaround
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-bug
