Repository yt-dlp/yt-dlp, pull requests merged in 2024-03, with the labels that each got.

#9333 [ie/francetv] Fix extraction
  yt_dlp/extractor/francetv.py
  yt_dlp/extractor/lumni.py
Labels: geo-blocked, site-bug

#9327 [ie/tiktok] Fix webpage extraction
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#9290 [ie/vimeo] Extract "live_status" and "release_timestamp" for live events
  yt_dlp/extractor/vimeo.py
Labels: site-enhancement

#9325 [ie/CCTV] Fix video id Regex
  yt_dlp/extractor/cctv.py
Labels: site-bug

#9320 [Dumpert] Broader url support
  yt_dlp/extractor/dumpert.py
Labels: site-bug

#9338 [ie/niconico] correctly check if the user has access to the video
  yt_dlp/extractor/niconico.py
Labels: site-bug, regression

#9347 [ie/francetv] Fix m3u8 formats extraction
  yt_dlp/extractor/francetv.py
Labels: site-bug

#8292 [ie/dailymotion] search support, fix #6126
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/dailymotion.py
Labels: site-enhancement

#9344 [test:websockets] Reduce timeout
  test/test_websockets.py
Labels: networking

#9295 [build] Add `default` optional dependency group
  README.md
  devscripts/install_deps.py
  pyproject.toml
Labels: docs/meta/cleanup

#8875 [RideHome] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/ridehome.py
Labels: site-request

#9380 [ie/francetv] Fix DAI livestreams
  yt_dlp/extractor/francetv.py
Labels: site-bug

#9356 [ie/newgrounds] Fix login and clean up extraction
  yt_dlp/extractor/newgrounds.py
Labels: account-needed, site-bug, can-share-account

#9384 [ie/craftsy] Fix extractor
  yt_dlp/extractor/craftsy.py
Labels: site-bug

#9355 [roosterteeth] Download ad-free streams
  yt_dlp/extractor/roosterteeth.py
Labels: site-enhancement

#9393 [ie/roosterteeth] Extract release date and timestamp
  yt_dlp/extractor/roosterteeth.py
Labels: site-enhancement

#9121 [ie/generic] Follow https redirects properly
  yt_dlp/extractor/generic.py
Labels: bug, docs/meta/cleanup

#9161 [Duboku] Decrypt m3u8 url link
  yt_dlp/extractor/duboku.py
Labels: site-bug

#9395 [ie/youtube] Further bump client versions
  yt_dlp/extractor/youtube.py
Labels: site-bug

#9404 Update regex for extractor in CrtvgIE extractor
  yt_dlp/extractor/crtvg.py
Labels: site-bug

#9403 [ie/roosterteeth] Add Brightcove fallback
  yt_dlp/extractor/roosterteeth.py
Labels: site-bug

#9394 Bugfix for 104a7b5a46dc1805157fb4cc11c05876934d37c1
  yt_dlp/YoutubeDL.py
Labels: bug, regression

#9392 [core] Handle `--load-info-json` format selection errors
  yt_dlp/YoutubeDL.py
Labels: bug

#9406 [ie/roosterteeth] support bonus features
  yt_dlp/extractor/roosterteeth.py
Labels: site-enhancement

#9354 Don't access `ydl._request_director` on `close()` (Fix 069b2aedae2279668b6051627a81fc4fbd9c146a)
  yt_dlp/YoutubeDL.py
  yt_dlp/networking/common.py
Labels: bug, networking

#9413 [ie/youtube:tab] Fix incorrect splitting of tags with whitespace
  yt_dlp/extractor/youtube.py
Labels: site-bug

#8399 Fix #4521: If `os.path.getsize` throws `FileNotFoundError`, set the retry to resume from 0.
  yt_dlp/downloader/http.py
Labels: bug

#9296 [build] Add transitional `setup.py` for compat
  pyinst.py
  setup.py
Labels: docs/meta/cleanup

#8977 [docs] Misc Cleanup
  .github/workflows/release.yml
  CONTRIBUTING.md
  Changelog.md
  README.md
  pyproject.toml
  test/test_execution.py
  test/test_utils.py
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/__main__.py
  yt_dlp/__pyinstaller/hook-yt_dlp.py
  yt_dlp/compat/urllib/request.py
  yt_dlp/cookies.py
  yt_dlp/dependencies/__init__.py
  yt_dlp/extractor/unsupported.py
  yt_dlp/networking/_urllib.py
  yt_dlp/networking/common.py
  yt_dlp/options.py
  yt_dlp/postprocessor/embedthumbnail.py
  yt_dlp/update.py
  yt_dlp/utils/_legacy.py
  yt_dlp/utils/_utils.py
Labels: docs/meta/cleanup

#9446 Fix download gofile.py
  yt_dlp/extractor/gofile.py
Labels: site-bug

#9444 [ie/tiktok] Update API hostname
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#9447 [ie/crunchyroll] Extract `vo_adaptive_hls` formats by default
  yt_dlp/extractor/crunchyroll.py
Labels: site-bug

#9423 [ie/SonyLIVSeries] Fix season extraction
  yt_dlp/extractor/sonyliv.py
Labels: site-bug

#9467 [test] Handle websockets server hanging
  test/test_websockets.py
Labels: networking

#9471 [extractor/imgur] Fix Imgur Extractor
  yt_dlp/extractor/imgur.py
Labels: site-bug

#9489 [ie/youtube] Fix tbr calculation
  yt_dlp/extractor/youtube.py
Labels: site-bug

#9481 [docs] Update yt-dlp tag-line
  .github/banner.svg
  README.md
  bundle/py2exe.py
  devscripts/prepare_manpage.py
  pyproject.toml
Labels: docs/meta/cleanup

#9456 [ie/YoutubeSearchDate] Fix search parameters
  yt_dlp/extractor/youtube.py
Labels: site-bug

#8686 Added Extractor for Loom
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/loom.py
Labels: site-request

#6531 [extractor/sharepoint] New extractor for Microsoft Sharepoint
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/sharepoint.py
Labels: site-request

#9504 [ie/box] Add support for implicit file ID
  yt_dlp/extractor/box.py
Labels: site-bug

#9502 [ie/xvideos] Fix regex (#9493)
  yt_dlp/extractor/xvideos.py
Labels: NSFW, site-bug

#9495 [ie/fathom] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/fathom.py
Labels: site-request

#9278 [downloader/ffmpeg] Accept output args from info dict
  yt_dlp/downloader/external.py
  yt_dlp/extractor/common.py
Labels: enhancement

#9548 [ie/tiktok] Fix API extraction
  README.md
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#9550 [build] Optional dependencies cleanup
  .github/workflows/build.yml
  devscripts/install_deps.py
  pyproject.toml
Labels: docs/meta/cleanup

#9574 [test] `traversal`: Separate traversal tests
  test/test_traversal.py
  test/test_utils.py
Labels: docs/meta/cleanup

#9575 [ie/tiktok] Prefer non-bytevc2 formats
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#9576 [ie/thisoldhouse] Support Brightcove embeds
  yt_dlp/extractor/thisoldhouse.py
Labels: site-bug

#9474 [ie] Add extractor impersonate API
  yt_dlp/extractor/common.py
  yt_dlp/networking/common.py
Labels: enhancement

#9584 [ie/soundcloud] Adjust format sorting
  yt_dlp/extractor/soundcloud.py
Labels: site-bug

#9560 [core] Fix `filesize_approx` calculation
  README.md
  devscripts/changelog_override.json
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/youtube.py
  yt_dlp/utils/_utils.py
Labels: bug, site-bug
