Repository yt-dlp/yt-dlp, pull requests merged in 2024-06, with the labels that each got.

#10079 [rh:requests] Bump minimum version requirement for `requests` to 2.32.2
  README.md
  bundle/py2exe.py
  pyproject.toml
  yt_dlp/networking/_requests.py
Labels: docs/meta/cleanup, networking

#10088 [build] Cache dependencies for `macos` job
  .github/workflows/build.yml
  .github/workflows/release-master.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
Labels: docs/meta/cleanup

#10116 [ie/tubitv:series] Fix extractor
  yt_dlp/extractor/tubitv.py
Labels: site-bug

#10177 [ie/francetv] Fix tokenized URL extraction
  yt_dlp/extractor/francetv.py
Labels: site-bug

#10165 [ie/francetv] Detect and raise errors for DRM
  yt_dlp/extractor/francetv.py
Labels: site-bug

#8418 [ie/rtvslo.si:show] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/rtvslo.py
Labels: site-enhancement

#10125 [ie/soundcloud] Fix `download` format extraction
  yt_dlp/extractor/soundcloud.py
Labels: site-bug

#10106 [ie/NHKRadiru] Switch to new metadata API
  yt_dlp/extractor/nhk.py
Labels: site-bug

#10124 [ie/tiktok] Detect and raise when login is required
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#10071 [ie/youtube:tab] Fix channel metadata extraction
  yt_dlp/extractor/youtube.py
Labels: site-bug

#9136 [ie/khanacademy] Fix extractors
  yt_dlp/extractor/khanacademy.py
Labels: site-bug

#10098 [ie/sproutvideo] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/patreon.py
  yt_dlp/extractor/sproutvideo.py
Labels: site-request

#10195 [ie/podbayfm] Fix extraction
  yt_dlp/extractor/podbayfm.py
Labels: site-bug

#10202 [ie/brightcove] Upgrade requests to HTTPS
  yt_dlp/extractor/brightcove.py
Labels: site-bug

#9875 [ie/youtube] Extract all formats from multi-language m3u8s
  yt_dlp/extractor/common.py
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#10215 [ie/cloudflarestream] Fix `_VALID_URL` and embed extraction
  yt_dlp/extractor/cloudflarestream.py
Labels: site-bug

#10216 [ie/tiktok] Fix API extraction
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#10223 [ie/youtube] Skip formats if nsig decoding fails
  yt_dlp/extractor/youtube.py
Labels: site-bug

#10232 [ie/facebook:reel] Fix extraction
  yt_dlp/extractor/facebook.py
Labels: site-bug

#10237 [cookies] Fix getting Linux desktop env from `$XDG_CURRENT_DESKTOP` in Ubuntu
  test/test_cookies.py
  yt_dlp/cookies.py
Labels: bug

#10190 [ie/matchtv] Fix extractor
  yt_dlp/extractor/matchtv.py
Labels: site-bug

#10271 [ie/cloudycdn] Fix videos with separate audio
  yt_dlp/extractor/cloudycdn.py
Labels: site-bug

#10273 [ie/mediasite] Fix extraction
  yt_dlp/extractor/mediasite.py
Labels: site-bug, regression

#10248 [pp/embedthumbnail] Fix
  yt_dlp/compat/imghdr.py
  yt_dlp/postprocessor/embedthumbnail.py
Labels: bug

#10258 [ie/neteasemusic] Use new API for url extraction
  yt_dlp/extractor/neteasemusic.py
Labels: site-enhancement

#10283 [test:download] Raise on network errors
  test/test_download.py
Labels: docs/meta/cleanup

#10282 [cleanup] Bump Ruff to 0.5.x
  pyproject.toml
  yt_dlp/extractor/atresplayer.py
  yt_dlp/extractor/cbc.py
  yt_dlp/jsinterp.py
  yt_dlp/networking/_requests.py
Labels: docs/meta/cleanup

#10301 [ie/bitchute] Fix extractors
  yt_dlp/extractor/bitchute.py
Labels: site-bug

#10296 [ie/mlbtv] Fix extraction
  yt_dlp/extractor/mlb.py
Labels: site-bug

#10139 [ie/jiocinema:series] Fix extraction
  yt_dlp/extractor/jiocinema.py
Labels: site-bug

#10152 [ie/digitalconcerthall] Rework extractor
  yt_dlp/extractor/digitalconcerthall.py
Labels: site-enhancement

#10174 [ie/AfreecaTV] downgrade api protocol to http
  yt_dlp/extractor/afreecatv.py
Labels: site-bug

#10235 [afreecatv] Support catchstory
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/afreecatv.py
Labels: site-enhancement

#10159 Ignore "Unavailable videos are hidden" warnings from YouTube
  yt_dlp/extractor/youtube.py
Labels: site-bug
