Repository yt-dlp/yt-dlp, pull requests merged in 2024-02, with the labels that each got.

#9116 [ie/zetland] Add ZetlandDKArticle Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/zetland.py
Labels: site-request

#9113 [ie/orf] Add ORFON extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/orf.py
Labels: site-request

#9119 [extractor/bilibili] fix BiliBiliSearch HTTP 412 banned
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#9130 [ie/CCMA] Add 1080p dash support
  yt_dlp/extractor/ccma.py
Labels: site-enhancement

#9115 [ie/radiko]add Metadata info (performer, duration)
  yt_dlp/extractor/radiko.py
Labels: site-enhancement

#9028 [eporner] Add support for AV1 codec
  yt_dlp/extractor/eporner.py
Labels: NSFW, site-enhancement

#9139 [extractor/bilibili] support noplaylist option for BilibiliPlaylistIE
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement

#9075 [ie/NYTimes] - Extractor overhaul - Article, Cooking Recipes and Guides
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nytimes.py
Labels: site-bug

#8868 [NUUM] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nuum.py
  yt_dlp/extractor/wasdtv.py
Labels: site-request

#9142 [ie/NYTimes] - adjust _GRAPHQL_QUERY to include the field 'firstPublished'
  yt_dlp/extractor/nytimes.py
Labels: site-enhancement

#9144 [ie/boosty] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/boosty.py
Labels: site-request

#8860 [extractor/tvp] fix live via vod
  yt_dlp/extractor/tvp.py
Labels: site-enhancement, site-bug

#9191 [ie/Ant1NewsGrEmbed] Fix extractor
  yt_dlp/extractor/antenna.py
Labels: site-bug

#9192 [ie/CrooksAndLiars] Fix extractor
  yt_dlp/extractor/crooksandliars.py
Labels: site-bug

#9194 [ie/Funk] Fix extractor
  yt_dlp/extractor/funk.py
Labels: site-bug

#9198 [ie/LeFigaroVideoEmbed] Fix extractor
  yt_dlp/extractor/lefigaro.py
Labels: site-bug

#9199 [ie/MagellanTV] Add episode support
  yt_dlp/extractor/magellantv.py
Labels: site-enhancement

#7047 make: numerically compare the major version of pandoc to be greater then or equal to 2
  Makefile
Labels: docs/meta/cleanup

#9210 [build:Makefile] Ensure compatibility with BSD `make`
  Makefile
Labels: docs/meta/cleanup, regression

#9189 [rai] fix #9154
  yt_dlp/extractor/rai.py
Labels: site-bug

#8938 [SVTPage] Fix extractor
  yt_dlp/extractor/svt.py
Labels: site-bug

#9221 [ie/Nova] Update embed regex
  yt_dlp/extractor/nova.py
Labels: site-bug

#9222 [ie/OneFootball] Fix extractor
  yt_dlp/extractor/onefootball.py
Labels: site-bug

#9232 [ie/Screencastify] Add new URL format
  yt_dlp/extractor/screencastify.py
Labels: site-bug

#9182 [Playeur] Rename Utreon to Playeur
  yt_dlp/extractor/utreon.py
Labels: site-bug

#9235 [build:Makefile] Restore compatibility with GNU Make <4.0
  Makefile
Labels: docs/meta/cleanup, regression

#9032 [rh] Remove additional logging handlers on close
  test/test_networking.py
  yt_dlp/networking/_requests.py
  yt_dlp/networking/_websockets.py
Labels: bug, networking

#9227 [ie/pornhub] fix is_logged check
  yt_dlp/extractor/pornhub.py
Labels: NSFW, site-bug

#9218 [err] Add lasteekraan.err.ee url match
  yt_dlp/extractor/err.py
Labels: site-enhancement

#9209 [ie/niconico] remove unusable legacy danmaku (comments, subtitle) extraction
  yt_dlp/extractor/niconico.py
Labels: site-bug

#9241 [build] Fix pyinstaller hooks
  Makefile
  pyproject.toml
  yt_dlp/__pyinstaller/hook-yt_dlp.py
Labels: docs/meta/cleanup, regression

#9162 [ie/NhkRadiru] Extract extended description
  yt_dlp/extractor/nhk.py
Labels: site-enhancement

#9178 [FlexTV] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/flextv.py
Labels: site-request

#6654 [extractor/goplay] Fix GoPlay downloads
  yt_dlp/extractor/goplay.py
Labels: site-bug

#8917 [ie] Add new fields with proper support for multiple values
  README.md
  test/helper.py
  test/test_YoutubeDL.py
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/youtube.py
  yt_dlp/postprocessor/ffmpeg.py
Labels: enhancement

#9229 Handle permission errors during plugin loading
  yt_dlp/plugins.py
Labels: bug

#9253 [ie/openrec] add referer for m3u8 (fix #6946)
  yt_dlp/extractor/openrec.py
Labels: site-bug

#9257 [ie/twitter] Extract bitrate for HLS audio formats
  yt_dlp/extractor/twitter.py
Labels: site-bug

#9263 [ie/twitter] Extract numeric `channel_id`
  yt_dlp/extractor/twitter.py
Labels: site-enhancement

#9269 [ie/NerdCubedFeed] Rework extractor
  yt_dlp/extractor/nerdcubed.py
Labels: site-bug

#8741 Fix cnbc.py / add CNBCVideoIE extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/cnbc.py
Labels: site-bug

#9250 [core] Warn user when directly launching `yt-dlp.exe`
  yt_dlp/__init__.py
  yt_dlp/options.py
Labels: enhancement

#9140 [ie/nebula] Add podcast support
  yt_dlp/extractor/nebula.py
Labels: site-enhancement

#9277 [build] Support failed build job re-runs
  .github/workflows/build.yml
Labels: docs/meta/cleanup

#9280 [ie/CloudflareStream] Improve `_VALID_URL`
  yt_dlp/extractor/cloudflarestream.py
Labels: site-bug

#9274 [ie/vimeo] Fix login
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#9276 [ie/ntvru] Fix extraction
  yt_dlp/extractor/ntvru.py
Labels: site-bug

#9281 [ie/swearnet] Raise for login required
  yt_dlp/extractor/swearnet.py
Labels: site-bug

#9279 [ie/archiveorg] Fix download URL encoding
  yt_dlp/extractor/archiveorg.py
Labels: site-bug

#9287 [ie/CloudflareStream] Improve embed detection
  yt_dlp/extractor/cloudflarestream.py
Labels: site-bug

#9083 [ie/youtube] Add helpful info if all responses are skipped
  yt_dlp/extractor/youtube.py
Labels: site-bug

#9297 [AltCensoredChannelIE] Fix page_count regular expression
  yt_dlp/extractor/altcensored.py
Labels: site-bug

#9239 [extractor/Douyin] fix Douyin
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#9306 [ie/MujRozhlas] Fix extraction
  yt_dlp/extractor/rozhlas.py
Labels: site-bug

#9309 [ie/CHZZK] Raise UserNotLive when the channel is not live.
  yt_dlp/extractor/chzzk.py
Labels: site-bug

#9291 [extractor/rai] fix #9154 and #887
  yt_dlp/extractor/rai.py
Labels: site-bug

#9282 [ie/niconico] Add support for DMS server; use robust info extraction logic; allow empty danmaku
  yt_dlp/extractor/niconico.py
Labels: site-enhancement, site-bug

#9317 [ie/youtube] Bump Android/iOS client versions to 18.x
  yt_dlp/extractor/youtube.py
Labels: site-bug
