Repository yt-dlp/yt-dlp, pull requests merged in 2024-12, with the labels that each got.

#11677 [ie/instagram] Support /share/ URLs
  yt_dlp/extractor/instagram.py
Labels: site-bug

#11683 [ie/Mitele] Fix regex extractor
  yt_dlp/extractor/mitele.py
Labels: site-bug

#11663 [ie/youtube] Adjust player clients for site changes
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#11667 [ie/bilibili] Provide fallback for playinfo extraction
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#11588 [ie/duoplay] Fix extractor
  yt_dlp/extractor/duoplay.py
Labels: site-bug

#11654 [ie/MicrosoftEmbed] Make format extraction non fatal
  yt_dlp/extractor/microsoftembed.py
Labels: site-bug

#11608 [cleanup] Bump ruff to 0.8.x
  pyproject.toml
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/aes.py
  yt_dlp/cookies.py
  yt_dlp/downloader/hls.py
  yt_dlp/downloader/youtube_live_chat.py
  yt_dlp/extractor/bilibili.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/funimation.py
  yt_dlp/extractor/youtube.py
  yt_dlp/plugins.py
  yt_dlp/postprocessor/__init__.py
  yt_dlp/postprocessor/ffmpeg.py
  yt_dlp/utils/_utils.py
Labels: docs/meta/cleanup

#11711 [ie/bilibili] don't raise if the user has logged in as a supporter when downloading supporter-only videos
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#10559 [BiliBili] extract 720p/1080p format without logging in by passing `'try_look': 1` to the api
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement

#11708 [ie/bilibili] Fix subtitles and chapters extraction
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#11715 [ie/vk] Fix extractors
  yt_dlp/extractor/vk.py
Labels: site-bug

#11731 [cookies] Add `--cookies-from-browser` support for Firefox from Microsoft Store
  yt_dlp/cookies.py
Labels: enhancement

#11724 [ie/youtube] Player client maintenance
  yt_dlp/extractor/youtube.py
Labels: site:youtube

#11734 [ie/bilibili] remove playinfo extraction from `window.__playinfo__`
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#11742 [ie/soundcloud] Fix formats extraction
  README.md
  yt_dlp/extractor/soundcloud.py
Labels: site-bug

#11751 [ie/youtube] Fix signature function extraction
  test/test_youtube_signature.py
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-bug, site:youtube

#11750 [ie/youtube] Fix `n` sig extraction for player `3bb1f723`
  test/test_youtube_signature.py
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-bug, site:youtube

#11752 [ie/youtube] Raise if `n` function returns input value
  yt_dlp/extractor/youtube.py
Labels: site-bug

#11777 [ie/soundcloud] Fix extraction
  yt_dlp/extractor/soundcloud.py
Labels: site-bug

#11756 [ie/patreon:campaign] Support /c/ URLs
  yt_dlp/extractor/patreon.py
Labels: site-bug

#11759 [youtube] Fix metadata extractor regex
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#11782 [Youtube] Fixed broken playlist search
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#11801 [ie/youtube] Fix signature function extraction for `2f1832d2`
  test/test_youtube_signature.py
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-bug, site:youtube

#11763 [cleanup] Make more playlist extractions lazy
  yt_dlp/extractor/brightcove.py
  yt_dlp/extractor/dvtv.py
  yt_dlp/extractor/nytimes.py
  yt_dlp/extractor/vidyard.py
Labels: docs/meta/cleanup, site-enhancement

#11827 [update] Fix endless update loop for `linux_exe` builds
  yt_dlp/update.py
Labels: bug, regression

#11819 [update] Check 64-bitness when upgrading ARM builds
  yt_dlp/update.py
Labels: bug

#11818 [ie/youtube] Fix `uploader_id` extraction
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#11821 [ie/youtube] Add new age-gate workaround
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#11820 [ie/soundcloud] Various fixes
  yt_dlp/extractor/soundcloud.py
Labels: site-bug

#9591 Don't sanitize filename on Unix when `--no-windows-filenames`
  README.md
  test/test_YoutubeDL.py
  yt_dlp/YoutubeDL.py
  yt_dlp/options.py
Labels: enhancement

#11890 [ie/youtube] Skip iOS formats that require PO Token
  README.md
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-bug, site:youtube

#11893 [ie/youtube] Player client maintenance
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#11910 [ie/youtube] Fix DASH formats incorrectly skipped in some situations
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube
