Repository yt-dlp/yt-dlp, pull requests merged in 2024-01, with the labels that each got.

#8909 [bugfix] Fix FireFox profile folder path for macOS
  yt_dlp/cookies.py
Labels: bug

#8894 nit: readme/deps/ffmpeg: fix minor typo
  README.md
Labels: docs/meta/cleanup

#8911 [utils] `traverse_obj`: Support `xml.etree.ElementTree.Element`
  test/test_utils.py
  yt_dlp/utils/traversal.py
Labels: enhancement

#8916 [ie/ard] Revert to using old id
  yt_dlp/extractor/ard.py
Labels: site-bug

#8960 [ie/Twitch] Fix video formats extraction
  yt_dlp/extractor/twitch.py
Labels: site-bug, pending-review

#8927 [ie/Turbo] Fix turbo extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/turbo.py
  yt_dlp/extractor/viously.py
Labels: site-enhancement, site-bug

#8999 fix: Piapro regex allowed characters
  yt_dlp/extractor/piapro.py
Labels: site-bug

#9005 [aenetworks] Prevent missing ratings extractor crash
  yt_dlp/extractor/aenetworks.py
Labels: site-bug

#9007 [CloudflareStream] fix-subtitle-warning Fixes #8830
  yt_dlp/extractor/cloudflarestream.py
Labels: site-bug

#8231 [ie/arte.tv] Extract accessible subtitles
  yt_dlp/extractor/arte.py
Labels: site-enhancement

#8990 [extractor/GoogleDrive] Update new Domain/URL for source file download
  yt_dlp/extractor/googledrive.py
Labels: site-bug

#7077 [extractor/biliIntl] Fix subtitle extraction and add more subtitles
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement, site-bug

#3824 [facebook] Update extractor for new URL
  yt_dlp/extractor/facebook.py
Labels: site-bug

#7416 [rule34video] Extract more video information
  yt_dlp/extractor/rule34video.py
Labels: NSFW, site-enhancement

#7790 [extractor] Add magentamusik.de
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/magentamusik.py
  yt_dlp/extractor/magentamusik360.py
Labels: site-request

#9001 [ie/ilpost] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/ilpost.py
Labels: site-request

#8948 [CapitalTVCy] Add Capital TV Cyprus extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/elementorembed.py
Labels: site-request

#8887 [CHZZK] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/chzzk.py
Labels: site-request

#8883 [ie/Naver] Fix extractor
  yt_dlp/extractor/naver.py
Labels: site-bug

#8895 [ie/abematv]: fix extraction when using cache
  yt_dlp/extractor/abematv.py
Labels: site-bug

#8901 [ie/abematv] allow login on AbemaTVTitle
  yt_dlp/extractor/abematv.py
Labels: site-bug

#8840 [9News] Add Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/ninenews.py
Labels: site-request

#8877 [KukuluLive] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/kukululive.py
Labels: site-request

#8744 Add support for Amadeus.tv
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/amadeustv.py
Labels: site-request

#8701 TrtWorld add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/trtworld.py
Labels: site-request

#8834 Update jiosaavn.py
  README.md
  yt_dlp/extractor/jiosaavn.py
Labels: site-enhancement

#8700 [ie/asobichannel] Implement Asobi Channel extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/asobichannel.py
Labels: site-request

#8708 feat(ADN): Add German variant and season downloads
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/adn.py
Labels: site-enhancement

#9019 Fix GoPro extractor.
  yt_dlp/extractor/gopro.py
Labels: site-bug

#8832 [BiliBili] - Few adjustments to the ``BiliIntlIE`` class
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement, site-bug

#8873 [GetCourseRuIE] & [AcademyMel] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/getcourseru.py
Labels: site-request

#8900 [test] Skip source address tests if the address cannot be bound to
  test/helper.py
  test/test_networking.py
  test/test_socks.py
  test/test_websockets.py
Labels: docs/meta/cleanup, networking

#8871 [networking] Remove `_CompatHTTPError`
  test/test_networking_utils.py
  yt_dlp/YoutubeDL.py
  yt_dlp/compat/_legacy.py
  yt_dlp/networking/exceptions.py
Labels: networking

#9034 [webvtt] Don't parse single fragment files
  yt_dlp/downloader/hls.py
Labels: bug

#9031 [rh:requests] Apply `remove_dot_segments` to absolute redirect locations
  test/test_networking.py
  yt_dlp/networking/_requests.py
Labels: bug, networking

#8676 redcdn livx and sejm.pl extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/redge.py
  yt_dlp/extractor/sejmpl.py
Labels: site-request

#8736 [extractor/mx3] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mx3.py
Labels: site-request

#8994 [extractor/MotherlessUploader] Add extractor for uploader playlists
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/motherless.py
Labels: NSFW, site-enhancement

#9046 [Newgrounds] Fix user page extractor
  yt_dlp/extractor/newgrounds.py
Labels: site-bug

#9044 [ie/Rule34Video] Fix valid URL regex
  yt_dlp/extractor/rule34video.py
Labels: NSFW, site-bug

#9037 [ie/ARDBetaMediathekIE] Add age verification
  yt_dlp/extractor/ard.py
Labels: site-enhancement

#8993 [patreon] fix not being able to download embedded videos
  yt_dlp/extractor/patreon.py
Labels: site-bug

#8934 [floatplane] feat: share playlist post fields with playlist entries
  yt_dlp/extractor/floatplane.py
Labels: site-bug

#8870 [ie/facebook] Support facebook.com/ads (Meta Ad Library)
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/facebook.py
Labels: site-request

#9051 [ie/pr0gramm] Enable POL filter and provide tags without login
  yt_dlp/extractor/pr0gramm.py
Labels: site-enhancement

#8643 [lsm] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/cloudycdn.py
  yt_dlp/extractor/lsm.py
Labels: site-request

#9063 [extractor/txxx] Added thumbnails
  yt_dlp/extractor/txxx.py
Labels: NSFW, site-enhancement

#9074 Fix download gofile.io
  yt_dlp/extractor/gofile.py
Labels: site-bug

#9076 fix download redtube.com
  yt_dlp/extractor/redtube.py
Labels: NSFW, site-bug

#9077 [extractor/playsuisse] fix #7974 with login
  yt_dlp/extractor/playsuisse.py
Labels: site-bug

#9092 [extractor] Fix Rumble extractor
  yt_dlp/extractor/rumble.py
Labels: site-bug

#9068 [ie/adn] require subscriptions in German
  yt_dlp/extractor/adn.py
Labels: site-bug

#9058 [ie/facebook] fix 403 error when downloading large video formats
  yt_dlp/extractor/facebook.py
Labels: site-bug

#9060 [ie/facebook] preserve thumbnail provided in video info
  yt_dlp/extractor/facebook.py
Labels: site-enhancement

#9061 [ie/facebook] update URL validation
  yt_dlp/extractor/facebook.py
Labels: site-enhancement

#8549 Add jupiter.err.ee, jupiterpluss.err.ee info extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/err.py
Labels: site-request

#9098 Fix MedalTV extractor
  yt_dlp/extractor/medaltv.py
Labels: site-bug

#9095 [ie/ViewLift] Added support for chorki.com [yt-dlp#3369]
  yt_dlp/extractor/viewlift.py
Labels: site-enhancement

#9099 [ie/art19] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/art19.py
Labels: site-request

#9055 [ie/facebook] add handling of facebook.com/events
  yt_dlp/extractor/facebook.py
Labels: site-enhancement

#9100 [ie/Vbox7] Fix extractor
  yt_dlp/extractor/vbox7.py
Labels: site-bug

#9084 [core] Add `--compat-options 2023`
  README.md
  yt_dlp/options.py
Labels: docs/meta/cleanup

#9016 [cookies] Fix `--cookies-from-browser` for `snap` Firefox
  yt_dlp/cookies.py
Labels: enhancement

#8946 [NinaProtocol] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/ninaprotocol.py
Labels: site-request

#9103 [ie/RedTube]Support redtube.com.br
  yt_dlp/extractor/redtube.py
Labels: NSFW, site-enhancement

#8997 [ie/nfb] Add series extractor, episode support, onf.ca support
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nfb.py
Labels: site-request

#9081 [ie/cineverse] Report account requirement
  yt_dlp/extractor/cineverse.py
Labels: site-bug
