Repository yt-dlp/yt-dlp, pull requests merged in 2024-10, with the labels that each got.

#11140 [cookies] Fix cookie load error handling
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/cookies.py
Labels: bug

#11190 [ie/youtube] Change default player clients to `ios,mweb`
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-bug

#11115 Make extended attribute writing more robust against filesystem limits.
  yt_dlp/postprocessor/xattrpp.py
Labels: enhancement

#11144 [NoodleMagazine] fix extractor
  yt_dlp/extractor/noodlemagazine.py
Labels: NSFW, site-bug

#11135 [ie/cwtv] Fix extractor
  yt_dlp/extractor/cwtv.py
Labels: site-bug

#11156 [ie/instagram] Fix extractor: set doc_id & update object path
  yt_dlp/extractor/instagram.py
Labels: site-bug

#11155 [ie/instagram] Do not hardcode user-agent
  yt_dlp/extractor/instagram.py
Labels: site-enhancement

#11215 [ie/weverse] Fix extractor
  yt_dlp/extractor/weverse.py
Labels: site-bug

#9507 [ie/TVer] Fix extractor
  yt_dlp/extractor/tver.py
Labels: site-enhancement

#11141 [ie/drtv] Fix DRTV token extraction by using android API
  yt_dlp/extractor/drtv.py
Labels: site-bug

#11230 [ie/cwtv] Fix extraction
  yt_dlp/extractor/cwtv.py
Labels: site-bug

#11235 [ie/patreon:campaign] Make `_VALID_URL` more strict
  yt_dlp/extractor/patreon.py
Labels: site-bug

#11197 Fix Python 3.9 compatibility in traceback generation (Fix e59c82a74cda5139eb3928c75b0bd45484dbe7f0)
  yt_dlp/YoutubeDL.py
Labels: bug, high-priority

#11206 [ie/generic] Add `impersonate` extractor arg
  README.md
  yt_dlp/extractor/generic.py
Labels: enhancement

#11205 [build] `make_lazy_extractors`: Force running without plugins
  README.md
  devscripts/make_lazy_extractors.py
  yt_dlp/YoutubeDL.py
  yt_dlp/plugins.py
Labels: bug, docs/meta/cleanup

#11203 [test] Allow running tests explicitly
  devscripts/run_tests.py
Labels: docs/meta/cleanup

#11198 [utils] `sanitize_path`: Reimplement function
  test/test_utils.py
  yt_dlp/utils/_utils.py
Labels: bug, high-priority

#10653 Add extractor helpers
  test/test_traversal.py
  yt_dlp/extractor/common.py
  yt_dlp/utils/_utils.py
  yt_dlp/utils/traversal.py
Labels: enhancement

#11202 [ie/reddit] Improve HTTP 403 error message
  yt_dlp/extractor/reddit.py
Labels: site-bug

#11250 [ie/adobepass] Use newer user-agent for provider redirect request
  yt_dlp/extractor/adobepass.py
Labels: site-bug

#11236 [build] Use `macos-13` image for macOS builds
  .github/workflows/build.yml
Labels: docs/meta/cleanup

#11258 [utils] `Popen`: Reset PyInstaller environment
  yt_dlp/utils/_utils.py
Labels: bug, regression

#11274 [ie/youtube] Fix `comment_count` extraction
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#11275 [ie/substack] Resolve podcast file extensions
  yt_dlp/extractor/substack.py
Labels: site-bug

#11289 [ie/Twitter:spaces] Fix extractor
  yt_dlp/extractor/twitter.py
Labels: site-bug

#11269 [ie/Funk] Extend `_VALID_URL`
  yt_dlp/extractor/funk.py
Labels: site-bug

#11277 Add option for specifying plugins directories
  README.md
  test/test_plugins.py
  test/testdata/plugin_packages/testpackage/yt_dlp_plugins/extractor/package.py
  yt_dlp/__init__.py
  yt_dlp/options.py
  yt_dlp/plugins.py
  yt_dlp/utils/_utils.py
Labels: enhancement

#11075 [ie/imgur] Support new URL format
  yt_dlp/extractor/imgur.py
Labels: site-bug

#10786 [ie/cda] Support folders
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/cda.py
Labels: site-enhancement

#11298 [ie/imgur] Fix thumbnail extraction
  yt_dlp/extractor/imgur.py
Labels: site-bug

#11297 [ie/youtube] Remove broken age-restriction workaround
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#11196 [CBC Gem] Fix 1080p detection after URL format change
  yt_dlp/extractor/cbc.py
Labels: site-bug

#11142 [ie/Telecinco] Fix extractor: Add headers
  yt_dlp/extractor/mitele.py
  yt_dlp/extractor/telecinco.py
Labels: site-bug

#11266 [ie/afreecatv] Adapt extractors to sooplive.co.kr domain
  yt_dlp/extractor/afreecatv.py
Labels: site-bug

#11001 [ie/youtube] Add support for logging in with OAuth2
  yt_dlp/extractor/youtube.py
Labels: site-enhancement, site:youtube

#10795 [ie/tubitv] strip spaces from episode title
  yt_dlp/extractor/tubitv.py
Labels: site-bug

#11256 [build] Migrate `py2exe` builds to `win_exe`
  .github/workflows/build.yml
  README.md
  bundle/py2exe.py
  pyproject.toml
  yt_dlp/update.py
Labels: docs/meta/cleanup

#11216 [cleanup] Misc
  .github/workflows/core.yml
  .github/workflows/download.yml
  .github/workflows/quick-test.yml
  CONTRIBUTING.md
  README.md
  devscripts/changelog_override.json
  pyproject.toml
  setup.cfg
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/nexx.py
  yt_dlp/extractor/tubetugraz.py
  yt_dlp/extractor/ustream.py
  yt_dlp/extractor/veoh.py
  yt_dlp/extractor/youtube.py
  yt_dlp/options.py
  yt_dlp/utils/traversal.py
Labels: docs/meta/cleanup

#11255 [build] Move optional dependencies to the `default` group
  pyproject.toml
Labels: docs/meta/cleanup

#11311 [cleanup] Misc (post-release)
  .github/workflows/build.yml
  devscripts/changelog_override.json
Labels: docs/meta/cleanup

#11321 Remove Python 3.8 support
  .github/workflows/build.yml
  CONTRIBUTING.md
  README.md
  devscripts/make_issue_template.py
  pyproject.toml
  setup.cfg
  test/test_update.py
  yt_dlp/__init__.py
  yt_dlp/compat/compat_utils.py
  yt_dlp/compat/functools.py
  yt_dlp/extractor/pornbox.py
  yt_dlp/plugins.py
  yt_dlp/update.py
  yt_dlp/utils/_utils.py
Labels: docs/meta/cleanup

#11328 [cleanup] Misc (2024.10 edition)
  README.md
  devscripts/changelog_override.json
  pyproject.toml
  yt_dlp/extractor/lbry.py
Labels: docs/meta/cleanup

#11334 Expand paths in `--plugin-dirs`
  yt_dlp/__init__.py
Labels: bug

#11343 [ie/facebook] Fix extractor
  yt_dlp/extractor/facebook.py
Labels: site-bug

#11336 [ie/generic] Do not impersonate by default
  README.md
  yt_dlp/extractor/generic.py
Labels: bug, regression

#11351 [ie/vimeo] Fix API retries
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#10185 [ie/CNN] Fix extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/cnn.py
Labels: site-bug

#11324 [ie/niconico] Fix NiconicoUserIE
  yt_dlp/extractor/niconico.py
Labels: site-bug

#11359 [ie] Safeguard against improper language values in ISM manifests
  yt_dlp/extractor/common.py
Labels: bug

#11353 [core] Populate format sorting fields before dependent fields
  yt_dlp/YoutubeDL.py
  yt_dlp/utils/_utils.py
Labels: bug, regression

#11366 [devscripts] `make_changelog`: Parse full commit message for fixes
  devscripts/changelog_override.json
  devscripts/make_changelog.py
Labels: docs/meta/cleanup

#11222 [ie/ccma] Update ccma.cat domain to 3cat.cat
  yt_dlp/extractor/ccma.py
Labels: site-bug

#11377 [ie/Soundcloud] Extract artists
  yt_dlp/extractor/soundcloud.py
Labels: site-enhancement

#11402 [utils] Fix `find_element` by class
  yt_dlp/utils/traversal.py
Labels: bug

#11408 Allow thumbnails with `.jpe` extension
  yt_dlp/utils/_utils.py
Labels: bug, regression

#11391 [utils] Allow partial application for more functions
  test/test_traversal.py
  test/test_utils.py
  yt_dlp/utils/_utils.py
  yt_dlp/utils/traversal.py
Labels: docs/meta/cleanup, enhancement

#11418 [build] Disable attestations for trusted publishing
  .github/workflows/release.yml
Labels: docs/meta/cleanup

#11358 [ie/yle_areena] Fix live events
  yt_dlp/extractor/yle_areena.py
Labels: site-bug
