Repository yt-dlp/yt-dlp, pull requests merged in 2024-08, with the labels that each got.

#10572 [ie/kick:clips] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/kick.py
Labels: site-request

#10457 [ie/youtube] Change default player client to `ios,tv`
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-bug

#10623 [cleanup] Misc
  yt_dlp/extractor/youtube.py
Labels: docs/meta/cleanup

#10626 Changed ccode value to 0564 in youku.py
  yt_dlp/extractor/youku.py
Labels: site-bug

#10625 [ie/olympics] Fix extraction
  yt_dlp/extractor/olympics.py
Labels: site-bug

#10664 [jsinterp] Improve `slice` implementation
  test/test_jsinterp.py
  yt_dlp/jsinterp.py
Labels: bug

#10668 [ie/youtube] Fix `n` function name extraction for player `b12cc44b`
  test/test_youtube_signature.py
  yt_dlp/extractor/youtube.py
Labels: site-bug

#10674 [ie/youtube] Change default player clients to `ios,web_creator`
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-bug

#10565 [gem.cbc.ca] Add support for downloading live replay content
  yt_dlp/extractor/cbc.py
Labels: site-enhancement

#10677 [ie/niconico] Fix extractor
  yt_dlp/extractor/niconico.py
Labels: site-bug

#10710 [ie/youtube] Support excluding `player_client`s in extractor-arg
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#10734 [PatreonCampaign] Add api campaign url for patreon
  yt_dlp/extractor/patreon.py
Labels: site-bug, regression

#10740 [ie/bilibili] fix bilibiliie valid url regex
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#10749 [ie/adn] adjustments for API changes
  yt_dlp/extractor/adn.py
Labels: site-bug

#10704 [ie/facebook:ads] Fix extractor
  yt_dlp/extractor/facebook.py
Labels: site-bug

#10768 [ie/asobistage] Support redirected URLs
  yt_dlp/extractor/asobistage.py
Labels: site-bug

#10726 [ie/radiko] make video_ids unique by including station ID
  yt_dlp/extractor/radiko.py
Labels: geo-blocked, site-bug

#10789 [ie/twitter:spaces] Support video spaces
  yt_dlp/extractor/twitter.py
Labels: site-bug

#10785 [ie/Eurosport] Support local variants
  yt_dlp/extractor/eurosport.py
  yt_dlp/extractor/tvn24.py
Labels: site-enhancement

#10815 [rh:websockets] Upgrade Websockets to v13
  .github/workflows/core.yml
  .github/workflows/quick-test.yml
  pyproject.toml
  test/test_websockets.py
  yt_dlp/networking/_websockets.py
Labels: high-priority, networking

#10002 [ie/Vidflex] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/vidflex.py
Labels: site-request

#10844 [ie/Rutube] Support livestreams
  yt_dlp/extractor/rutube.py
Labels: site-enhancement

#10861 [ci] Add issue tracker anti-spam protection
  .github/ISSUE_TEMPLATE/1_broken_site.yml
  .github/ISSUE_TEMPLATE/2_site_support_request.yml
  .github/ISSUE_TEMPLATE/3_site_feature_request.yml
  .github/ISSUE_TEMPLATE/4_bug_report.yml
  .github/ISSUE_TEMPLATE/5_feature_request.yml
  .github/ISSUE_TEMPLATE/6_question.yml
  .github/workflows/antispam.yaml
  devscripts/make_issue_template.py
Labels: docs/meta/cleanup
