Repository yt-dlp/yt-dlp, pull requests merged in 2024-04, with the labels that each got.

#8978 [ie, cleanup] No `from` stdlib imports
  yt_dlp/extractor/ard.py
  yt_dlp/extractor/bibeltv.py
  yt_dlp/extractor/bundestag.py
  yt_dlp/extractor/dtube.py
  yt_dlp/extractor/linkedin.py
  yt_dlp/extractor/masters.py
  yt_dlp/extractor/microsoftstream.py
  yt_dlp/extractor/naver.py
  yt_dlp/extractor/neteasemusic.py
  yt_dlp/extractor/niconico.py
  yt_dlp/extractor/panopto.py
  yt_dlp/extractor/polsatgo.py
  yt_dlp/extractor/pr0gramm.py
  yt_dlp/extractor/prosiebensat1.py
  yt_dlp/extractor/radiokapital.py
  yt_dlp/extractor/rokfin.py
  yt_dlp/extractor/telewebion.py
  yt_dlp/extractor/tenplay.py
  yt_dlp/extractor/wistia.py
  yt_dlp/extractor/zattoo.py
Labels: docs/meta/cleanup

#9585 [ie/soundcloud] Enable retries for rate-limiting
  yt_dlp/extractor/soundcloud.py
Labels: site-enhancement

#9586 [ie/soundcloud] Support cookies
  yt_dlp/extractor/soundcloud.py
Labels: site-enhancement

#9582 [build] Add SHA2-SUMS to GHA logs
  .github/workflows/build.yml
Labels: docs/meta/cleanup, regression

#8735 [ie/asobistage] Add extractor for live and archives
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/asobistage.py
Labels: site-request

#8761 [ie/mixch] Fix info extraction for archives
  yt_dlp/extractor/mixch.py
Labels: site-bug

#9158 [extractor/twitch] Support AV1/HEVC extraction
  yt_dlp/extractor/twitch.py
Labels: site-enhancement

#9122 [ie/Radio1Be] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/vrt.py
Labels: site-request

#9561 [ie/cbc.ca:player] Support new URL format
  yt_dlp/extractor/cbc.py
Labels: site-enhancement

#9610 Add option `--no-break-on-existing`
  README.md
  yt_dlp/options.py
Labels: enhancement

#9608 [ie/mixch] Fix extractor
  yt_dlp/extractor/mixch.py
Labels: site-bug

#9609 [ie/jiosaavn] Fix format extensions
  yt_dlp/extractor/jiosaavn.py
Labels: site-bug

#9612 [ie/jiosaavn] Extract artists
  yt_dlp/extractor/jiosaavn.py
Labels: site-enhancement

#9518 [ie/medici] Fix extractor
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/medici.py
Labels: site-bug

#9348 [ie/AfreecaTVLive] Fix extractor in Korea
  yt_dlp/extractor/afreecatv.py
Labels: site-bug

#9615 [ie/crunchyroll] Fix extractor
  README.md
  yt_dlp/extractor/crunchyroll.py
Labels: site-bug

#9627 [ie/dropbox] Fix anonymous download formats
  yt_dlp/extractor/dropbox.py
Labels: site-bug

#9566 [ie/afreecatv] Fix extractor
  yt_dlp/extractor/afreecatv.py
Labels: site-bug

#9624 [ie/joqrag] Fix live_status check when "Program_name" is empty
  yt_dlp/extractor/joqrag.py
Labels: site-bug

#9611 [ie/kick] Support browser impersonation
  yt_dlp/extractor/kick.py
Labels: site-bug

#9636 [ie/vkplay] Fix `_VALID_URL`
  yt_dlp/extractor/vk.py
Labels: site-bug

#9619 [cookies] Add support for Firefox installed via Flatpak
  yt_dlp/cookies.py
Labels: enhancement

#9637 [ie/tiktok] Restore `carrier_region` API param
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#9613 [patreon] fix some vimeo embed downloads
  yt_dlp/extractor/patreon.py
Labels: site-bug

#9623 [ie/nhk] Fix NHK World extractors
  yt_dlp/extractor/nhk.py
Labels: site-bug

#9622 [ie/jiosaavn] Support playlists
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/jiosaavn.py
Labels: site-enhancement

#9543 Adding ssl keys log using SSLKEYLOGFILE env var for SSLContext (yt-dlp/yt-dlp#9531)
  yt_dlp/networking/_helper.py
Labels: enhancement, networking

#9082 [progress] Implement progress update rate
  README.md
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/downloader/common.py
  yt_dlp/options.py
Labels: enhancement

#9653 [build] Do not include `curl_cffi` in `macos_legacy`
  .github/workflows/build.yml
  README.md
Labels: docs/meta/cleanup

#9426 [cleanup] Misc (for 2024.04 release)
  .github/workflows/quick-test.yml
  Makefile
  devscripts/changelog_override.json
  test/test_traversal.py
  yt_dlp/networking/_helper.py
  yt_dlp/update.py
Labels: docs/meta/cleanup

#9656 [ie/jiosaavn] Extract via API and fix playlists
  yt_dlp/extractor/jiosaavn.py
Labels: site-bug

#9666 [ie/afreecatv:live] Add `cdn` extractor-arg
  README.md
  yt_dlp/extractor/afreecatv.py
Labels: site-enhancement, site-bug

#9698 [build] Normalize `curl_cffi` group to `curl-cffi`
  .github/workflows/build.yml
  README.md
  pyproject.toml
Labels: docs/meta/cleanup

#9712 [ie/patreon] Fix Vimeo embed extraction
  yt_dlp/extractor/patreon.py
Labels: site-bug, regression

#9734 [ie/facebook] Fix DASH formats extraction
  yt_dlp/extractor/facebook.py
Labels: site-bug

#8937 [ie] Make `_search_nextjs_data` non fatal
  test/test_InfoExtractor.py
  yt_dlp/extractor/asobistage.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/stv.py
  yt_dlp/extractor/tiktok.py
Labels: bug

#9754 [ie/theatercomplextown] Fix extractors
  yt_dlp/extractor/stacommu.py
  yt_dlp/extractor/wrestleuniverse.py
Labels: site-bug

#9749 [ie/crunchyroll] Fix auth and remove cookies support
  yt_dlp/extractor/crunchyroll.py
Labels: site-bug

#9802 [core:windows] Improve shell quoting and tests
  test/test_utils.py
  yt_dlp/utils/_utils.py
Labels: enhancement

#9804 [build] Run `macos_legacy` on `macos-12`
  .github/workflows/build.yml
Labels: docs/meta/cleanup

#9811 [build] Create linux_static build target
  .github/workflows/build.yml
  bundle/docker/compose.yml
  bundle/docker/static/Dockerfile
  bundle/docker/static/entrypoint.sh
  yt_dlp/update.py
Labels: docs/meta/cleanup
