Repository yt-dlp/yt-dlp, pull requests merged in 2024-11, with the labels that each got.

#11437 [utils] Allow partial application for even more functions
  test/test_traversal.py
  yt_dlp/utils/_utils.py
  yt_dlp/utils/traversal.py
Labels: enhancement

#11055 [ie/Bluesky] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/bluesky.py
Labels: site-request

#11443 [utils] Fix and improve `find_element` and `find_elements`
  test/test_traversal.py
  yt_dlp/utils/traversal.py
Labels: bug

#11153 [core] Prioritize AV1
  README.md
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/extractor/youtube.py
  yt_dlp/options.py
  yt_dlp/utils/_utils.py
Labels: enhancement

#11438 [aes] Fix gcm pad length calculation
  test/test_aes.py
  yt_dlp/aes.py
Labels: bug

#11444 [ie/bfmtv] Fix extractors
  yt_dlp/extractor/bfmtv.py
Labels: site-bug

#10843 [ie/Dailymotion] Improve embed extraction
  yt_dlp/extractor/dailymotion.py
Labels: site-enhancement

#11228 [ie/chzzk] Fix video(fast replay) download
  yt_dlp/extractor/chzzk.py
Labels: site-bug

#11442 [ie/ARDMediathek] Extract chapters
  yt_dlp/extractor/ard.py
Labels: site-enhancement

#11374 [ie/Dailymotion] Support shortened URLs
  yt_dlp/extractor/dailymotion.py
Labels: site-enhancement

#11409 [ie/nfl] Fix extractors
  yt_dlp/extractor/anvato.py
  yt_dlp/extractor/nfl.py
Labels: site-bug

#11425 [cookies] Support chrome table version 24
  test/test_cookies.py
  yt_dlp/cookies.py
Labels: bug

#6057 [ie/Tumblr] Support more URLs
  yt_dlp/extractor/tumblr.py
Labels: site-bug

#11472 [ie/adobepass] Fix provider requests
  yt_dlp/extractor/adobepass.py
Labels: high-priority, site-bug, regression

#11368 [ie/GameDevTV] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/gamedevtv.py
Labels: site-request

#11420 [build] Enable attestations for trusted publishing
  .github/workflows/build.yml
  .github/workflows/release-master.yml
  .github/workflows/release-nightly.yml
  .github/workflows/release.yml
Labels: docs/meta/cleanup

#11488 [build] Pin `websockets` version to >=13.0,<14
  pyproject.toml
Labels: docs/meta/cleanup

#11486 [core] Catch broken cryptodome installations
  yt_dlp/dependencies/Cryptodome.py
Labels: enhancement

#11489 [ie/spreaker] Support episode pages and access keys
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/spreaker.py
Labels: site-enhancement

#11480 [ie/rutube] Rework extractors
  yt_dlp/extractor/rutube.py
Labels: site-enhancement, site-bug

#10968 [ie/spreaker] Support podcast and feed pages
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/spreaker.py
Labels: site-enhancement

#10897 [ie/MixchMovie] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mixch.py
Labels: site-request

#11507 [build] Bump PyInstaller version pin to `>=6.11.1`
  .github/workflows/build.yml
  pyproject.toml
Labels: docs/meta/cleanup

#11478 [ie/CloudflareStream] Avoid extraction via videodelivery.net
  yt_dlp/extractor/cloudflarestream.py
Labels: site-bug

#11466 [ie/goplay] Fix extractor
  yt_dlp/extractor/goplay.py
Labels: site-bug

#10595 [ie/Chaturbate] Support alternate domains
  yt_dlp/extractor/chaturbate.py
Labels: NSFW, site-enhancement

#11513 [ie/facebook] Fix formats extraction
  yt_dlp/extractor/facebook.py
Labels: site-bug

#11527 [ie/archiveorg] Fix crash (TypeError) when a review's body is None
  yt_dlp/extractor/archiveorg.py
Labels: site-bug

#11559 [utils] Fix `join_nonempty`, add `**kwargs` to `unpack`
  test/test_traversal.py
  test/test_utils.py
  yt_dlp/utils/_utils.py
  yt_dlp/utils/traversal.py
Labels: bug

#11508 [utils] `subs_list_to_dict`: Add `lang` default parameter
  test/test_traversal.py
  yt_dlp/utils/traversal.py
Labels: enhancement

#5607 [ie/RadioRadicale] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/radioradicale.py
Labels: site-request

#11535 [ie/bandlab] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/bandlab.py
Labels: site-request

#11542 [ie/spankbang] Support browser impersonation
  yt_dlp/extractor/spankbang.py
Labels: NSFW, site-bug

#11531 [ie/RedGifsUser] Fix extraction
  yt_dlp/extractor/redgifs.py
Labels: NSFW, site-bug

#11555 [ie/chaturbate] Extract from API and support impersonation
  yt_dlp/extractor/chaturbate.py
Labels: NSFW, site-bug

#11530 [ie/patreon] Fix comments extraction
  yt_dlp/extractor/patreon.py
Labels: site-bug

#11439 [cleanup] Deprecate more compat functions
  devscripts/generate_aes_testdata.py
  pyproject.toml
  test/helper.py
  test/test_YoutubeDL.py
  test/test_aes.py
  test/test_compat.py
  test/test_downloader_http.py
  test/test_utils.py
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/aes.py
  yt_dlp/compat/__init__.py
  yt_dlp/compat/_deprecated.py
  yt_dlp/compat/_legacy.py
  yt_dlp/compat/functools.py
  yt_dlp/compat/urllib/request.py
  yt_dlp/cookies.py
  yt_dlp/downloader/common.py
  yt_dlp/downloader/external.py
  yt_dlp/downloader/fragment.py
  yt_dlp/downloader/http.py
  yt_dlp/downloader/rtmp.py
  yt_dlp/downloader/rtsp.py
  yt_dlp/extractor/abematv.py
  yt_dlp/extractor/adn.py
  yt_dlp/extractor/anvato.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/shemaroome.py
  yt_dlp/postprocessor/common.py
  yt_dlp/postprocessor/embedthumbnail.py
  yt_dlp/postprocessor/ffmpeg.py
  yt_dlp/postprocessor/movefilesafterdownload.py
  yt_dlp/postprocessor/sponskrub.py
  yt_dlp/postprocessor/xattrpp.py
  yt_dlp/update.py
  yt_dlp/utils/_deprecated.py
  yt_dlp/utils/_legacy.py
  yt_dlp/utils/_utils.py
Labels: docs/meta/cleanup

#11558 [ie/youtube] Remove broken OAuth support
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#11565 Fix embed detection (Bugfix for 720b3dc453c342bc2e8df7dbc0acaab4479de46c)
  yt_dlp/extractor/chaturbate.py
Labels: site-bug

#3996 [kenh14] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/kenh14.py
Labels: site-request

#11566 [cleanup] Remove dead extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mildom.py
  yt_dlp/extractor/pokemon.py
  yt_dlp/extractor/veoh.py
Labels: docs/meta/cleanup

#11567 [ie/youtube] Fix podcasts tab extraction
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#8892 [ie/ctvnews] Fix playlist ID extraction
  yt_dlp/extractor/ctvnews.py
Labels: site-bug

#11534 [ie/ctvnews] Fix extractor
  yt_dlp/extractor/ctvnews.py
Labels: site-bug

#11569 [ie/SonyLIVSeries] Add `sort_order` extractor-arg
  README.md
  yt_dlp/extractor/sonyliv.py
Labels: site-enhancement

#11071 [ie/litv] Fix extractor + bypass georestriction
  yt_dlp/extractor/litv.py
Labels: site-bug

#11554 [cleanup] Misc (2024.11)
  README.md
  devscripts/changelog_override.json
  yt_dlp/extractor/bandlab.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/ctvnews.py
  yt_dlp/extractor/facebook.py
  yt_dlp/extractor/rutube.py
  yt_dlp/extractor/soundcloud.py
  yt_dlp/options.py
Labels: docs/meta/cleanup

#11571 [ie/digitalconcerthall] Support login with access/refresh tokens
  README.md
  yt_dlp/extractor/digitalconcerthall.py
Labels: site-bug

#11573 [ie/reddit] Improve error handling
  yt_dlp/extractor/reddit.py
Labels: site-bug

#11574 [cleanup] Misc (2024.11 part 2)
  Changelog.md
  devscripts/changelog_override.json
  yt_dlp/extractor/dailymotion.py
Labels: docs/meta/cleanup

#11596 FIX: Stripchat recent changes
  yt_dlp/extractor/stripchat.py
Labels: NSFW, site-bug

#11613 Add `playlist_webpage_url` field
  README.md
  yt_dlp/YoutubeDL.py
Labels: enhancement

#11576 [ie/facebook] fix _VALID_URL and add tests
  yt_dlp/extractor/facebook.py
Labels: site-bug

#11615 [ie/youtube:tab] Fix playlists tab extraction
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-bug, site:youtube

#11624 [ie/chaturbate] Support non-public (#11623)
  yt_dlp/extractor/chaturbate.py
Labels: NSFW, site-bug, regression

#11637 [ie] Handle fragmented formats in `_remove_duplicate_formats`
  yt_dlp/extractor/common.py
Labels: bug, needs-testing

#11644 [ie/dacast] Fix HLS AES formats extraction
  yt_dlp/extractor/dacast.py
Labels: site-bug

#11645 [ie/tiktok] Deprioritize animated thumbnails
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#11636 [ie/dropbox] Fix password-protected video extraction
  yt_dlp/extractor/dropbox.py
Labels: site-bug, pending-review
