Repository yt-dlp/yt-dlp, pull requests merged in 2024-09, with the labels that each got.

#10721 [ie/vimeo] Always try to extract original format
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#5788 [ie/KiKA] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/kika.py
  yt_dlp/extractor/mdr.py
Labels: site-bug

#10901 [build] Pin `delocate` version for `macos`
  .github/workflows/build.yml
Labels: docs/meta/cleanup

#10906 [ie/vimeo] Fix login detection
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#10915 [ci] Add comment sanitization workflow
  .github/ISSUE_TEMPLATE/1_broken_site.yml
  .github/ISSUE_TEMPLATE/2_site_support_request.yml
  .github/ISSUE_TEMPLATE/3_site_feature_request.yml
  .github/ISSUE_TEMPLATE/4_bug_report.yml
  .github/ISSUE_TEMPLATE/5_feature_request.yml
  .github/ISSUE_TEMPLATE/6_question.yml
  .github/workflows/issue-lockdown.yml
  .github/workflows/sanitize-comment.yml
  devscripts/make_issue_template.py
Labels: docs/meta/cleanup

#10913 [ie/khanacademy] Fix extractor
  yt_dlp/extractor/khanacademy.py
Labels: site-bug

#10947 [ie/SampleFocus] Fix extractor
  yt_dlp/extractor/samplefocus.py
Labels: site-bug

#10955 [networking] Fix handler not being added to RequestError
  test/test_networking.py
  yt_dlp/networking/_helper.py
Labels: networking

#10648 [ie/youtube] Add `po_token`, `visitor_data` and `data_sync_id` extractor-args
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-enhancement, site:youtube

#10938 [ie/youtube] Support new shorts tab view model
  yt_dlp/extractor/youtube.py
Labels: site-bug

#9901 [ie/beacon] Add extractor for Beacon.tv
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/beacon.py
Labels: site-request

#10956 [core] Fix jwplayer format parsing
  yt_dlp/extractor/common.py
Labels: bug

#10328 [ie/bandcamp] Extract extended user page
  yt_dlp/extractor/bandcamp.py
Labels: site-bug

#10787 [ie/RTP] Support more subpages
  yt_dlp/extractor/rtp.py
Labels: site-enhancement

#10686 [ie/huya:video] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/huya.py
Labels: site-request

#10832 [ximalaya.com] Add VIP support
  yt_dlp/extractor/ximalaya.py
Labels: site-enhancement

#10858 [extractor/facebook] Add extract total_comment_count, unified_reactors_count and share_count of the video. (yt-dlp#10824)
  yt_dlp/extractor/facebook.py
Labels: site-enhancement

#10860 [utils] `mimetype2ext`: Recognize `aacp` as `aac`
  yt_dlp/utils/_utils.py
Labels: bug

#10868 [ie] Handle decode errors when reading responses
  yt_dlp/extractor/common.py
Labels: bug, networking

#10867 Fix pinterest regex
  yt_dlp/extractor/pinterest.py
Labels: site-bug

#10904 [ie/LnkGo] Remove extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/lnk.py
Labels: docs/meta/cleanup

#10910 Better authentication for ESPN+
  yt_dlp/extractor/espn.py
Labels: site-enhancement

#10917 [ie/screenrec] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/screenrec.py
Labels: site-request

#10928 [ie/tenplay] Fix extractor
  yt_dlp/extractor/tenplay.py
Labels: site-bug

#10944 [ie/Servus] Fix extractor
  yt_dlp/extractor/servus.py
Labels: site-bug

#10950 [ie/Xinpianchang] Fix extractor
  yt_dlp/extractor/xinpianchang.py
Labels: site-bug

#10952 [ie/Sen] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/sen.py
Labels: site-request

#10959 [ie/IPrima] Fix extractor
  yt_dlp/extractor/iprima.py
Labels: site-bug

#10988 [ie/Kick] fix valid url
  yt_dlp/extractor/kick.py
Labels: site-bug

#10992 [ie/HGTVDe] Fix extractor
  yt_dlp/extractor/dplay.py
Labels: site-bug

#11074 [ie/tiktok] Fix web formats extraction
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#11028 [ie/youtube] Fix `format_note` (Bugfix for 3a3bd00)
  yt_dlp/extractor/youtube.py
Labels: site-bug, regression, site:youtube

#11092 [networking] Pin `curl-cffi` version to < 0.7.2
  pyproject.toml
  yt_dlp/networking/_curlcffi.py
Labels: networking

#11090 [cookies] Improve error message for Windows `--cookies-from-browser chrome` issue
  yt_dlp/cookies.py
Labels: bug

#10709 [build] Bump PyInstaller version pin to `>=6.10.0`
  .github/workflows/build.yml
  pyproject.toml
Labels: docs/meta/cleanup

#11083 [ie/mediaklikk] Fix extractor
  yt_dlp/extractor/mediaklikk.py
Labels: site-bug

#11019 [ie/Mojevideo] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mojevideo.py
Labels: site-request

#11030 [ie/SnapchatSpotlight] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/snapchat.py
Labels: site-request

#11091 [ie/ertgr] Fix video extraction
  yt_dlp/extractor/ertgr.py
Labels: site-bug

#10538 [ie/Germanupa] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/germanupa.py
Labels: site-request

#11049 Make Rumble extractor more robust.
  yt_dlp/extractor/rumble.py
Labels: site-bug

#11010 [ie/SVTPage] Fix extractor
  yt_dlp/extractor/svt.py
Labels: site-bug

#11099 [ie/bilibili] Fix chapters and subtitles extraction
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#11100 [ie/wistia] Support password-protected videos
  yt_dlp/extractor/wistia.py
Labels: site-bug

#11102 [ie/youtube:clip] Prioritize `https` formats
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#11103 [ie/niconico] Fix m3u8 formats extraction
  yt_dlp/extractor/niconico.py
Labels: site-bug

#11101 [ie/abc.net.au:iview:showseries] Fix extraction
  yt_dlp/extractor/abc.py
Labels: site-bug

#11104 [ie/YleAreena] Support podcasts
  yt_dlp/extractor/yle_areena.py
Labels: site-enhancement

#11107 [ie/kick:clips] Support new URL format
  yt_dlp/extractor/kick.py
Labels: site-bug

#11066 [option parser] Add conversion negation for thumbnails and subtitles
  README.md
  yt_dlp/__init__.py
  yt_dlp/options.py
Labels: enhancement

#11082 [ie/vimeo] Sort audio track by quality keyword in format_id
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#10884 vp9.2 vcodec format sort bug fix
  test/test_YoutubeDL.py
  test/test_utils.py
  yt_dlp/utils/_utils.py
Labels: bug

#10735 [ie/dropbox] Fix password-protected video support
  yt_dlp/extractor/dropbox.py
Labels: site-bug

#10760 [ie/loom] Fix hls format
  yt_dlp/extractor/loom.py
Labels: site-bug

#11098 Raise minimum recommended Python version to 3.9
  devscripts/changelog_override.json
  yt_dlp/update.py
Labels: docs/meta/cleanup

#10807 [cleanup] Misc
  .github/workflows/quick-test.yml
  .github/workflows/release.yml
  README.md
  pyproject.toml
  yt_dlp/downloader/external.py
  yt_dlp/extractor/academicearth.py
  yt_dlp/extractor/ard.py
  yt_dlp/extractor/callin.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/fc2.py
  yt_dlp/extractor/generic.py
  yt_dlp/extractor/getcourseru.py
  yt_dlp/extractor/golem.py
  yt_dlp/extractor/hrfensehen.py
  yt_dlp/extractor/japandiet.py
  yt_dlp/extractor/kaltura.py
  yt_dlp/extractor/mailru.py
  yt_dlp/extractor/mgtv.py
  yt_dlp/extractor/mit.py
  yt_dlp/extractor/nzonscreen.py
  yt_dlp/extractor/pornhub.py
  yt_dlp/extractor/radiofrance.py
  yt_dlp/extractor/reverbnation.py
  yt_dlp/extractor/tele13.py
  yt_dlp/extractor/twitcasting.py
  yt_dlp/extractor/viu.py
  yt_dlp/extractor/ximalaya.py
  yt_dlp/networking/_websockets.py
  yt_dlp/options.py
  yt_dlp/postprocessor/sponsorblock.py
  yt_dlp/utils/_utils.py
Labels: docs/meta/cleanup

#10903 [ie/ApplePodcasts] Fix extractor
  yt_dlp/extractor/applepodcasts.py
  yt_dlp/extractor/common.py
Labels: site-bug

#11143 [test] Rerun failed tests
  .github/workflows/core.yml
  .github/workflows/quick-test.yml
  pyproject.toml
Labels: docs/meta/cleanup

#11138 [ie/patreon] Extract all m3u8 formats for locked posts
  yt_dlp/extractor/patreon.py
Labels: site-bug
