Repository yt-dlp/yt-dlp, pull requests merged in 2025-07, with the labels that each got.

#13599 [rh:requests] Work around partial read dropping data
  test/test_networking.py
  yt_dlp/networking/_requests.py
Labels: bug, core:networking

#13601 [ie] Detect invalid m3u8 playlist data
  test/test_InfoExtractor.py
  yt_dlp/extractor/common.py
Labels: bug

#13603 [rh:requests] Do not allocate 2GB on read
  yt_dlp/networking/_requests.py
Labels: bug

#13618 [ie/twitch] Improve error handling
  yt_dlp/extractor/twitch.py
Labels: site-bug

#13655 [fd/hls] Do not fall back to ffmpeg when native is required
  yt_dlp/downloader/hls.py
Labels: bug

#13665 [ie/youtube:tab] Fix subscriptions feed extraction
  yt_dlp/extractor/youtube/_tab.py
Labels: site-bug, site:youtube

#13667 [ie/BiliBiliBangumi] Fix geo-block detection
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#13620 [devscripts] Fix filename/directory Bash completions
  devscripts/bash-completion.in
Labels: bug, docs/meta/cleanup

#13651 [ie/mir24.tv] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mir24tv.py
Labels: site-request

#13612 [ie/newspicks] Rework Extractor
  yt_dlp/extractor/newspicks.py
Labels: site-bug

#13640 [ie/youtube] Improve client PO Token enforcement policy
  README.md
  yt_dlp/extractor/youtube/_base.py
  yt_dlp/extractor/youtube/_video.py
Labels: site-enhancement, site:youtube

#13398 [ie] Add `_search_nextjs_v13_data` helper
  test/test_InfoExtractor.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/francetv.py
  yt_dlp/extractor/goplay.py
  yt_dlp/extractor/ninenow.py
Labels: enhancement

#13711 [ie] Rework `_search_nextjs_v13_data` helper
  test/test_InfoExtractor.py
  yt_dlp/extractor/common.py
Labels: bug

#13717 [ie/LRTRadio] Fix extractor
  yt_dlp/extractor/lrt.py
Labels: site-bug

#13700 [ie/hotstar] Fix: Headers & Parameters
  yt_dlp/extractor/hotstar.py
Labels: site-bug

#13726 [ie/francetv] Improve error handling
  yt_dlp/extractor/francetv.py
Labels: site-bug

#13505 [ie/TheHighWire] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/thehighwire.py
Labels: site-request

#12473 [ie/blackboardcollaborate] Support subtitles and authwalled videos
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/blackboardcollaborate.py
Labels: site-enhancement

#13749 [utils] `urlhandle_detect_ext`: Use `x-amz-meta-file-type` headers
  yt_dlp/utils/_utils.py
Labels: enhancement

#13747 [ie/aenetworks] Support new URL formats
  yt_dlp/extractor/aenetworks.py
Labels: site-bug

#13767 [core] Don't let format testing alter the return code
  yt_dlp/YoutubeDL.py
Labels: bug

#13090 [core] Warn when skipping formats
  yt_dlp/YoutubeDL.py
Labels: enhancement

#13768 [ie/dangalplay] Support other login regions
  yt_dlp/extractor/dangalplay.py
Labels: site-bug

#13761 [ie/mlbtv] Make formats downloadable with ffmpeg
  yt_dlp/extractor/mlb.py
Labels: site-bug

#13611 [ie/tenplay] Support new 10.com.au domain
  yt_dlp/extractor/tenplay.py
Labels: site-bug

#13778 Allow extractors to designate formats/subtitles for impersonation
  yt_dlp/YoutubeDL.py
  yt_dlp/downloader/__init__.py
  yt_dlp/downloader/http.py
  yt_dlp/extractor/common.py
Labels: enhancement, core:networking, core:downloader, core:extractor

#13785 [rh:requests] Refactor default headers
  yt_dlp/networking/_requests.py
Labels: core:networking

#13786 [ie/youtube] Use impersonation for downloading subtitles
  yt_dlp/extractor/youtube/_video.py
Labels: site-bug, site:youtube

#13736 [ie/bilibili] Pass newer user-agent with API requests
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#13800 [ie/BiliBiliBangumi] Fix extractor
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#13712 [ie/patreon:campaign] Fix extractor
  yt_dlp/extractor/patreon.py
Labels: site-bug

#13595 [cleanup] Misc (for 2025.07.XX release)
  CONTRIBUTING.md
  README.md
  devscripts/changelog_override.json
  test/test_download.py
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/mirrativ.py
  yt_dlp/extractor/newspicks.py
  yt_dlp/extractor/youtube/_video.py
Labels: docs/meta/cleanup

#13823 [ie/vimeo] Fix login support and require authentication
  README.md
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#9683 [ie/tbs] Fix truTV support
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tbs.py
  yt_dlp/extractor/trutv.py
  yt_dlp/extractor/turner.py
Labels: site-enhancement

#13844 [fd/external] Work around ffmpeg's `file:` URL handling
  yt_dlp/downloader/external.py
Labels: bug, core:downloader

#13814 [build] Use `macos-14` runner for `macos` builds
  .github/workflows/build.yml
  bundle/pyinstaller.py
Labels: docs/meta/cleanup

#13857 Deprecate `darwin_legacy_exe` support
  yt_dlp/update.py
Labels: docs/meta/cleanup

#13859 Raise minimum recommended Python version to 3.10
  yt_dlp/update.py
Labels: docs/meta/cleanup

#13873 [cookies] Load cookies with float `expires` timestamps
  yt_dlp/cookies.py
Labels: bug, core:cookies

#13880 [ie/archive.org] Fix metadata extraction
  yt_dlp/extractor/archiveorg.py
Labels: site-bug

#13885 [ie/TVer] Extract Streaks API info
  yt_dlp/extractor/streaks.py
  yt_dlp/extractor/tver.py
Labels: site-bug

#13598 [ie/TVer] Support `--ignore-no-formats-error` when geo-blocked
  yt_dlp/extractor/tver.py
Labels: site-enhancement

#13485 [ie/tbsjp] Fix extractor
  yt_dlp/extractor/tbsjp.py
Labels: geo-blocked, site-bug
