Repository yt-dlp/yt-dlp, pull requests merged in 2025-01, with the labels that each got.

#10657 [ie/PlVideo] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/plvideo.py
Labels: site-request

#11927 [core] Validate retries values are non-negative
  yt_dlp/__init__.py
Labels: bug

#11988 Fix filename sanitization with `--no-windows-filenames`
  yt_dlp/YoutubeDL.py
Labels: bug, regression

#12059 [ie/youtube] Use `tv` instead of `mweb` by default
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-bug, site:youtube

#11989 [ie/youtube] Refactor cookie SID auth
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#10831 [ie/DrTalks] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/drtalks.py
Labels: site-request

#11700 [ie/vine] Remove extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tumblr.py
  yt_dlp/extractor/twitter.py
  yt_dlp/extractor/vine.py
Labels: docs/meta/cleanup

#11915 [cleanup] Misc (for 2025 release)
  README.md
  pyproject.toml
  yt_dlp/YoutubeDL.py
Labels: docs/meta/cleanup

#12087 [ie/youtube] Do not use `web_creator` as a default client
  README.md
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-bug, site:youtube

#12102 [ie/dropout] Fix extraction
  yt_dlp/extractor/dropout.py
Labels: site-bug

#12088 [ie/Weibo] Extend `_VALID_URL`
  yt_dlp/extractor/weibo.py
Labels: site-enhancement

#12069 [ie/nrk] Extract more formats
  yt_dlp/extractor/nrk.py
Labels: site-enhancement

#12138 [ie/LBRY] Support signed URLs
  yt_dlp/extractor/lbry.py
Labels: site-enhancement

#9361 [ie/senategov] Fix extractors
  yt_dlp/extractor/senategov.py
Labels: site-bug

#12136 [ie/rtvslo.si:show] Extract more metadata
  yt_dlp/extractor/rtvslo.py
Labels: site-enhancement

#11904 [ie/eggs] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/eggs.py
Labels: site-request

#11747 [ie/nest] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/nest.py
Labels: site-request

#10777 [ie/piramidetv] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/piramidetv.py
Labels: site-request

#12147 [ie/XiaoHongShu] Extract more formats
  yt_dlp/extractor/xiaohongshu.py
Labels: site-enhancement

#11838 [ie/BiliBiliDynamic] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement

#12154 [ie/Bluesky] Prefer source format
  yt_dlp/extractor/bluesky.py
Labels: site-enhancement

#12168 [ie/youtube] Download `tv` client Innertube config
  yt_dlp/extractor/youtube.py
Labels: site-enhancement, site:youtube

#12090 [ie/youtube] Use different PO token for GVS and Player
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#12181 [ie/youtube] Restore convenience workarounds
  README.md
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube

#12173 [ie/GoodGame] Fix extractor
  yt_dlp/extractor/goodgame.py
Labels: site-bug

#11054 [ie/subsplash] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/subsplash.py
Labels: site-request

#11999 [ie/soundcloud:user] Add `/comments` page support
  yt_dlp/extractor/soundcloud.py
Labels: site-enhancement

#12193 [ie/nrk] Fix invalid HDR chunks returned
  yt_dlp/extractor/nrk.py
Labels: site-bug

#11880 fix unintended rounding of decimal comparison values in format filters
  test/test_YoutubeDL.py
  yt_dlp/YoutubeDL.py
Labels: bug

#12167 [ie/funimation] Remove extractors
  README.md
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/funimation.py
Labels: docs/meta/cleanup

#11964 [ie/bilibili] Update playlist url regex
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#11889 [ie/1tv] Support sport1tv.ru domain
  yt_dlp/extractor/firsttv.py
Labels: site-enhancement

#11923 [utils] `sanitize_path`: Fix some incorrect behavior
  test/test_utils.py
  yt_dlp/utils/_utils.py
Labels: bug

#12142 [ie/vimeo] update thumbnail extraction logic (#11931)
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#11945 [ie/soundcloud] Add more extracted fields
  yt_dlp/extractor/soundcloud.py
Labels: site-enhancement

#11041 [ie/ZDF] Rewrite channel extractor to use an API instead of HTML scraping
  yt_dlp/extractor/zdf.py
Labels: site-bug

#12089 [ie/bilibilispacevideo] extract without logging in
  yt_dlp/extractor/bilibili.py
Labels: site-enhancement, site-bug

#12037 [ie/naver] Fix m3u8 formats download
  yt_dlp/extractor/naver.py
Labels: site-bug

#11997 [ie/youtube] Attempt to extract title for Shorts from accessibilityText as fallback (#11991)
  yt_dlp/extractor/youtube.py
Labels: site-enhancement

#11822 [niconico:series] Fixed api reander. (temporary repair)
  yt_dlp/extractor/niconico.py
Labels: site-bug

#12024 [ie/pbs] #11514 pbs patch
  yt_dlp/extractor/pbs.py
Labels: site-bug

#12000 [ie/patreon] Include attachment filenames in metadata
  yt_dlp/extractor/patreon.py
Labels: site-enhancement

#11805 [redgifs] Support alternative URLs
  yt_dlp/extractor/redgifs.py
Labels: NSFW, site-bug

#11771 [ie/abematv] support season
  yt_dlp/extractor/abematv.py
Labels: site-enhancement

#11738 [ie/xhamster] wrong key used in extractor
  yt_dlp/extractor/xhamster.py
Labels: NSFW, site-bug

#11720 [ie/TheaterComplexTownPPV] Support `live` URLs
  yt_dlp/extractor/stacommu.py
Labels: site-bug

#11688 VIMPPlaylist: Add support for tags
  yt_dlp/extractor/videocampus_sachsen.py
Labels: site-enhancement

#11605 [ie/youtube] Expose 'livestream' media type
  yt_dlp/extractor/youtube.py
Labels: site-enhancement, site:youtube

#12194 [cleanup] Misc
  .gitignore
  devscripts/changelog_override.json
  yt_dlp/extractor/bilibili.py
  yt_dlp/extractor/bluesky.py
  yt_dlp/extractor/laracasts.py
  yt_dlp/extractor/plvideo.py
  yt_dlp/extractor/tver.py
  yt_dlp/utils/_utils.py
Labels: docs/meta/cleanup

#12207 [ie/cwtv] Fix extractor
  yt_dlp/extractor/cwtv.py
  yt_dlp/extractor/theplatform.py
Labels: site-bug

#11191 [ie/pbs] Support www.thirteen.org URLs
  yt_dlp/extractor/pbs.py
Labels: site-bug

#12223 [ie/acast] Support shows.acast.com URLs
  yt_dlp/extractor/acast.py
Labels: site-bug

#12228 [ie/dropbox] Fix extraction
  yt_dlp/extractor/dropbox.py
Labels: site-bug

#12236 [ie/francetv:site] Fix extractor
  yt_dlp/extractor/francetv.py
Labels: site-bug

#12237 [ie/goplay] Fix extractor
  yt_dlp/extractor/goplay.py
Labels: site-bug

#11795 [ie/globo] Fix extractor
  yt_dlp/extractor/globo.py
Labels: site-bug
