Repository yt-dlp/yt-dlp, pull requests merged in 2025-06, with the labels that each got.

#13335 [ie/adobepass] Fix Philo MSO authentication
  yt_dlp/extractor/adobepass.py
Labels: site-bug

#13361 [ie/odnoklassniki] Detect and raise when login is required
  yt_dlp/extractor/odnoklassniki.py
Labels: site-bug

#13350 [ie/vimeo] Extract subtitles from player subdomain
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#13373 [ie/umg:de] Rework extractor
  yt_dlp/extractor/umg.py
Labels: site-bug

#13403 [ie/youtube] Rework nsig function name extraction
  test/test_youtube_signature.py
  yt_dlp/extractor/youtube/_video.py
Labels: high-priority, site-bug, site:youtube

#13408 [ie/aenetworks] Fix playlist extractors
  yt_dlp/extractor/aenetworks.py
Labels: site-bug, regression

#13411 [youtube] Add support for --sub-format srt
  yt_dlp/extractor/youtube/_video.py
Labels: site-enhancement, site:youtube

#13389 [ie/youtube] Add `tv_simply` player client
  README.md
  test/test_pot/test_pot_builtin_utils.py
  test/test_pot/test_pot_builtin_webpospec.py
  yt_dlp/extractor/youtube/_base.py
  yt_dlp/extractor/youtube/pot/utils.py
Labels: site-enhancement, site:youtube

#13188 [ie/startrek] Fix extractor
  yt_dlp/extractor/startrek.py
Labels: site-bug

#13313 [ie/zdf] Fix language extraction and format sorting
  yt_dlp/extractor/dreisat.py
  yt_dlp/extractor/zdf.py
Labels: site-bug

#13278 [cleanup] Misc (for 2025.06.XX release)
  README.md
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/douyutv.py
  yt_dlp/extractor/qqmusic.py
  yt_dlp/extractor/vk.py
Labels: docs/meta/cleanup

#13461 [ie/brightcove:new] Improve metadata extraction
  yt_dlp/extractor/brightcove.py
Labels: site-enhancement

#13524 [ie/youtube] Check any `ios` m3u8 formats prior to download
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/youtube/_video.py
Labels: high-priority, site-bug, site:youtube

#13126 [ie/lsm] Fix extraction
  yt_dlp/extractor/cloudycdn.py
  yt_dlp/extractor/lsm.py
Labels: site-bug

#13520 [ie/huya:live] Fix extractor
  yt_dlp/extractor/huya.py
Labels: site-enhancement, site-bug

#13380 [ie/mave] Add extractor for Mave Digital
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mave.py
Labels: site-request, pending-fixes

#13533 [ie/BilibiliSpaceVideo] Extract hidden-mode collections as playlists
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#13158 [ie/niconico:live] Fix extractor and downloader
  yt_dlp/downloader/niconico.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/niconico.py
Labels: site-bug

#13560 [ie/hotstar] Fix metadata extraction
  yt_dlp/extractor/hotstar.py
Labels: site-bug

#10405 [ie/hotstar] Raise for login required
  yt_dlp/extractor/hotstar.py
Labels: site-bug

#13565 [ie/jiocinema] Remove extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/jiocinema.py
Labels: docs/meta/cleanup

#13563 [ie] Implement check for HLS streaming header
  test/test_InfoExtractor.py
  yt_dlp/extractor/common.py
Labels: bug

#13585 [ie/hotstar] Fix formats extraction
  yt_dlp/extractor/hotstar.py
Labels: site-bug

#13586 [ie/youtube] Fix premium formats extraction
  yt_dlp/extractor/youtube/_base.py
  yt_dlp/extractor/youtube/_video.py
Labels: high-priority, site-bug, regression, site:youtube

#13588 [ie] Fix m3u8 playlist data corruption
  test/test_InfoExtractor.py
  yt_dlp/extractor/common.py
Labels: bug, high-priority, regression

#13550 [ie/kick] Support subscriber-only content
  yt_dlp/extractor/kick.py
Labels: site-bug

#13590 [cleanup] Misc
  devscripts/changelog_override.json
Labels: docs/meta/cleanup
