Repository yt-dlp/yt-dlp, pull requests merged in 2025-09, with the labels that each got.

#14249 [ci] Test and lint workflows
  .github/actionlint.yml
  .github/workflows/release.yml
  .github/workflows/test-workflows.yml
Labels: docs/meta/cleanup

#14261 [build] Fix cache warmer
  .github/workflows/build.yml
  .github/workflows/cache-warmer.yml
Labels: bug, docs/meta/cleanup

#13878 [test:utils] Fix `sanitize_path` test for Windows CPython 3.11
  test/test_utils.py
Labels: docs/meta/cleanup

#14280 [ie/vimeo] Fix login error handling
  yt_dlp/extractor/vimeo.py
Labels: site-bug

#14197 [ie/newspicks] Add preview warning for premium videos when unauthenticated
  yt_dlp/extractor/newspicks.py
Labels: site-enhancement

#14196 [ie/pixivsketch] Remove dead extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/pixivsketch.py
Labels: docs/meta/cleanup

#14287 [ie/tiktok:live] Fix room ID extraction
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#14275 [build] Refactor Linux build jobs
  .github/workflows/build.yml
  bundle/docker/compose.yml
  bundle/docker/linux/build.sh
  bundle/docker/linux/verify.sh
Labels: docs/meta/cleanup

#14316 [ci] Improve workflow checks
  .github/workflows/test-workflows.yml
  bundle/docker/linux/build.sh
  devscripts/setup_variables_tests.py
Labels: docs/meta/cleanup

#14318 [build] Use PyInstaller 6.16 for Windows
  .github/workflows/build.yml
Labels: docs/meta/cleanup

#14345 [ie/xhamster] Fix extractor
  yt_dlp/extractor/xhamster.py
Labels: NSFW, site-bug

#14348 [ie/mitele] Remove extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/mitele.py
  yt_dlp/extractor/unsupported.py
Labels: docs/meta/cleanup

#14447 [ie/youtube] Improve logging
  yt_dlp/extractor/youtube/_video.py
Labels: site-enhancement

#14465 [ie/youtube] Replace `tv_simply` with `web_safari` in default clients
  README.md
  yt_dlp/extractor/youtube/_base.py
  yt_dlp/extractor/youtube/_video.py
Labels: high-priority, site-bug, site:youtube
