Repository yt-dlp/yt-dlp, pull requests merged in 2025-04, with the labels that each got.

#12821 [ie/vk] Fix chapter extraction
  yt_dlp/extractor/vk.py
Labels: site-bug

#12817 [ie/RoyaLive] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/roya.py
Labels: site-request

#12836 [ie/CrowdBunker] Make format extraction non-fatal
  yt_dlp/extractor/crowdbunker.py
Labels: site-bug

#12838 [ie/rumble] Improve format extraction
  yt_dlp/extractor/rumble.py
Labels: site-bug

#12769 [ie/parti] Add extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/parti.py
Labels: site-request

#12842 [ie/TokFMPodcast] Fix formats extraction
  yt_dlp/extractor/agora.py
Labels: site-bug

#12852 [ie/dzen.ru] Rework extractors
  yt_dlp/extractor/yandexvideo.py
Labels: site-bug

#12830 [ie/mixcloud] Refactor extractor
  yt_dlp/extractor/mixcloud.py
Labels: site-bug

#12855 [utils] `_yield_json_ld`: Make function less fatal
  yt_dlp/extractor/common.py
Labels: enhancement

#12848 [utils] `url_or_none`: Support WebSocket URLs
  test/test_utils.py
  yt_dlp/utils/_utils.py
Labels: enhancement

#12768 [ie/ivoox] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/ivoox.py
Labels: site-request

#12832 [ie/kika] Add playlist extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/kika.py
Labels: site-enhancement

#12809 [ie/niconico:live] Fix extractor
  yt_dlp/downloader/niconico.py
  yt_dlp/extractor/niconico.py
Labels: site-bug

#12801 [ie/LRTRadio] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/lrt.py
Labels: site-enhancement

#12938 [ie/youtube:tab] Extract continuation from empty page
  test/helper.py
  yt_dlp/extractor/youtube/_tab.py
Labels: site-bug, site:youtube

#12939 [ie/youtube] Add warning on playback recaptcha challenge
  yt_dlp/extractor/youtube/_video.py
Labels: site-enhancement, site:youtube

#12865 [ie/youtube] Add extractor arg to skip "initial_data" request
  README.md
  yt_dlp/extractor/youtube/_video.py
Labels: site-enhancement, site:youtube

#12884 [networking] Add PATCH request shortcut
  test/test_networking.py
  yt_dlp/networking/__init__.py
  yt_dlp/networking/common.py
Labels: enhancement, core:networking

#12919 [ie/CDAFolder] Extend `_VALID_URL`
  yt_dlp/extractor/cda.py
Labels: site-bug

#10907 [ie/manyvids] Fix extractor
  yt_dlp/extractor/manyvids.py
Labels: NSFW, site-bug

#12923 [ie/tvp:vod] Improve `_VALID_URL`
  yt_dlp/extractor/tvp.py
Labels: site-bug

#12927 [ie/linkedin] Support feed URLs
  yt_dlp/extractor/linkedin.py
Labels: site-bug

#12925 [ie/panopto] Fix formats extraction
  yt_dlp/extractor/panopto.py
Labels: site-bug

#12859 [ie/AbemaTV] Fix thumbnail extraction
  yt_dlp/extractor/abematv.py
Labels: site-enhancement

#11424 [ie/AtresPlayer] Rework extractor
  yt_dlp/extractor/atresplayer.py
Labels: site-bug

#12721 [ie/tvw:tvchannels] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tvw.py
Labels: site-enhancement

#10388 [ie/rtve] Rework extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/rtve.py
Labels: site-enhancement, site-bug

#12934 [ie/loco] Fix extractor
  yt_dlp/extractor/loco.py
Labels: site-bug

#12839 Add `--preset-alias` option
  yt_dlp/options.py
Labels: enhancement

#12976 [ie/vimeo] Fix API extraction
  yt_dlp/extractor/vimeo.py
Labels: high-priority, site-bug

#12977 [ie/twitcasting] Fix livestream extraction
  yt_dlp/extractor/twitcasting.py
Labels: site-bug

#12975 [ie/cda] Fix formats extraction
  yt_dlp/extractor/cda.py
Labels: site-bug

#12978 [ie/generic] Fix MPD extraction for `file://` URLs
  yt_dlp/extractor/generic.py
Labels: site-bug, regression

#12943 [ie/GetCourseRu] Fix extractors
  yt_dlp/extractor/getcourseru.py
Labels: site-bug

#12985 [ie/vk] Fix uploader extraction
  yt_dlp/extractor/vk.py
Labels: site-bug

#12971 [ie/RaiPlay] Fix DRM detection
  yt_dlp/extractor/rai.py
Labels: site-bug

#12979 [ie/dacast] Support tokenized URLs
  yt_dlp/extractor/dacast.py
Labels: site-bug

#12911 [ie/twitter:spaces] Improve metadata extraction
  yt_dlp/extractor/twitter.py
Labels: site-enhancement

#12958 [ie/youtube] Add context to video request rate limit error
  yt_dlp/extractor/youtube/_video.py
Labels: enhancement, site:youtube

#13003 [ie/youtube] Detect player JS variants for any locale
  yt_dlp/extractor/youtube/_video.py
Labels: site-bug, site:youtube

#13024 [ie/twitter] Fix extraction when logged-in
  yt_dlp/extractor/twitter.py
Labels: high-priority, site-bug

#13014 [ie/youtube] Detect when account cookies are rotated
  yt_dlp/extractor/youtube/_base.py
Labels: site-enhancement, site:youtube

#13036 [ci] Add file mode test to code check
  .github/workflows/quick-test.yml
  yt_dlp/extractor/vk.py
Labels: docs/meta/cleanup

#12926 [ie/linkedin:events] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/linkedin.py
Labels: site-request

#13022 [ie/twitch:clips] Fix uploader metadata extraction
  yt_dlp/extractor/twitch.py
Labels: site-bug, regression

#13015 [ie/bpb] Fix formats extraction
  yt_dlp/extractor/bpb.py
Labels: site-bug

#12945 [ie/TV2DK] Fix extractor
  yt_dlp/extractor/tv2dk.py
Labels: site-bug

#12993 [ie/reddit] Support `--ignore-no-formats-error`
  yt_dlp/extractor/reddit.py
Labels: site-enhancement

#13008 [ie/niconico] Fix login support
  yt_dlp/extractor/niconico.py
Labels: site-bug

#13034 [ie/vimeo] Extract from mobile API
  yt_dlp/extractor/vimeo.py
Labels: high-priority, site-bug

#13047 [ie/youtube] Cache signature timestamps
  yt_dlp/extractor/youtube/_video.py
Labels: site-enhancement, site:youtube

#12779 [ie/zdf] Fix extractors
  yt_dlp/extractor/dreisat.py
  yt_dlp/extractor/phoenix.py
  yt_dlp/extractor/zdf.py
Labels: site-bug

#13061 [ie/youtube] Do not strictly deprioritize `missing_pot` formats
  yt_dlp/extractor/youtube/_video.py
Labels: site-bug, site:youtube

#12844 [cleanup] Misc (for 2025-04)
  .github/workflows/core.yml
  README.md
  devscripts/changelog_override.json
  yt_dlp/update.py
  yt_dlp/utils/_utils.py
Labels: docs/meta/cleanup
