Repository yt-dlp/yt-dlp, pull requests merged in 2025-03, with the labels that each got.

#11652 [networking] Add `keep_header_casing` extension
  test/test_networking.py
  test/test_utils.py
  test/test_websockets.py
  yt_dlp/networking/_requests.py
  yt_dlp/networking/_urllib.py
  yt_dlp/networking/_websockets.py
  yt_dlp/networking/common.py
  yt_dlp/networking/impersonate.py
  yt_dlp/utils/networking.py
Labels: enhancement, core:networking

#12505 [ie/MagellanTV] Fix extractor
  yt_dlp/extractor/magellantv.py
Labels: site-bug

#12271 [ie/tvw] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/tvw.py
Labels: site-request

#11638 [ie/RTP] Rework extractor
  yt_dlp/extractor/rtp.py
Labels: site-bug

#12514 [ie/N1] Fix extractor on newer articles
  yt_dlp/extractor/n1.py
Labels: site-bug

#12537 [ie/twitter] Fix syndication token generation
  yt_dlp/extractor/twitter.py
Labels: site-bug, regression

#12538 [ie/pinterest] Fix extractor
  yt_dlp/extractor/pinterest.py
Labels: site-bug

#12510 [ie/vk] Improve metadata extraction
  yt_dlp/extractor/vk.py
Labels: site-enhancement

#12557 [ie/youtube] Split into package
  yt_dlp/extractor/youtube/__init__.py
  yt_dlp/extractor/youtube/_base.py
  yt_dlp/extractor/youtube/_clip.py
  yt_dlp/extractor/youtube/_mistakes.py
  yt_dlp/extractor/youtube/_notifications.py
  yt_dlp/extractor/youtube/_redirect.py
  yt_dlp/extractor/youtube/_search.py
  yt_dlp/extractor/youtube/_tab.py
  yt_dlp/extractor/youtube/_video.py
Labels: site-enhancement, site:youtube

#12608 [ie/openrec] Fix URL validation regex
  yt_dlp/extractor/openrec.py
Labels: site-bug

#12479 [ie/VRTMax] Rework Extractor
  yt_dlp/extractor/gigya.py
  yt_dlp/extractor/vrt.py
Labels: site-bug

#12552 [ie/cda] Fix error 400
  yt_dlp/extractor/cda.py
Labels: site-bug

#12603 [ie/youtube] Player client maintenance
  README.md
  yt_dlp/extractor/youtube/_base.py
Labels: site-enhancement

#12566 [ie/tiktok] Truncate title
  yt_dlp/extractor/tiktok.py
Labels: site-enhancement

#12567 [ie/reddit] Truncate title
  yt_dlp/extractor/reddit.py
Labels: site-enhancement

#12593 [ie/youtube] Warn on DRM formats
  yt_dlp/extractor/youtube/_video.py
Labels: site-enhancement, site:youtube

#12626 [networking] Always add unsupported suffix on version mismatch
  yt_dlp/networking/_requests.py
  yt_dlp/networking/_websockets.py
Labels: core:networking

#12513 [ie/msn] Rework extractor
  yt_dlp/extractor/msn.py
Labels: site-bug

#12534 [ie/NBCStations]allow for new nbc_data syntax
  yt_dlp/extractor/nbc.py
Labels: site-bug

#12497 [ie/Canalsurmas] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/canalsurmas.py
Labels: site-request

#12569 [ie/tv8.it] Add live and playlist extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/skyit.py
Labels: site-request

#12622 [ie/jamendo] Fix thumbnail extraction
  yt_dlp/extractor/jamendo.py
Labels: site-bug

#12690 [ie/BilibiliPlaylist] Fix extractor
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#12689 [ie/mitele] Fix extractor
  yt_dlp/extractor/mitele.py
  yt_dlp/extractor/telecinco.py
Labels: site-bug

#12609 [ie/soop] Fix timestamp extraction
  yt_dlp/extractor/afreecatv.py
Labels: site-bug

#12628 [ie/ketnet] Remove extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/vrt.py
Labels: docs/meta/cleanup

#12667 [ie/loco] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/loco.py
Labels: site-request

#12526 [cleanup] Misc (for 2025-03)
  pyproject.toml
  test/test_http_proxy.py
  test/test_jsinterp.py
  test/test_utils.py
  yt_dlp/aes.py
  yt_dlp/extractor/bandlab.py
  yt_dlp/extractor/bluesky.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/medaltv.py
  yt_dlp/extractor/weibo.py
  yt_dlp/jsinterp.py
  yt_dlp/postprocessor/ffmpeg.py
  yt_dlp/update.py
  yt_dlp/utils/_utils.py
Labels: docs/meta/cleanup

#12692 [ie/chzzk:video] Fix extraction
  yt_dlp/extractor/chzzk.py
Labels: site-bug

#12696 [core] Fix attribute error on failed VT init
  yt_dlp/YoutubeDL.py
Labels: bug, high-priority, regression

#12703 [ie/viki] Remove extractors
  test/test_subtitles.py
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/unsupported.py
  yt_dlp/extractor/viki.py
Labels: docs/meta/cleanup

#12704 [ie/deezer] Remove extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/deezer.py
  yt_dlp/extractor/unsupported.py
Labels: docs/meta/cleanup

#12670 [rh:curl_cffi] Support `curl_cffi` 0.10.x
  pyproject.toml
  test/test_networking.py
  yt_dlp/YoutubeDL.py
  yt_dlp/__init__.py
  yt_dlp/networking/_curlcffi.py
Labels: core:networking

#12728 [ie/youtube] Fix PhantomJS nsig fallback
  yt_dlp/extractor/youtube/_video.py
Labels: high-priority, site-bug, site:youtube

#12715 [utils] `js_to_json`: Make function less fatal
  test/test_utils.py
  yt_dlp/utils/_utils.py
Labels: bug

#12718 [ie/generic] Fix MPD base URL parsing
  yt_dlp/extractor/generic.py
Labels: bug

#12723 [ie/17live:vod] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/ichinanalive.py
Labels: site-enhancement

#12659 [ie/TVer] Fix extractor
  README.md
  yt_dlp/extractor/tver.py
Labels: geo-blocked, site-bug

#12748 [ie/youtube] Fix nsig extraction for player `4fcd6e4a`
  test/test_youtube_signature.py
  yt_dlp/extractor/youtube/_video.py
Labels: high-priority, site-bug, site:youtube

#12750 [ie/youtube] Only cache nsig code on successful decoding
  yt_dlp/extractor/youtube/_video.py
Labels: site-enhancement, site:youtube

#12760 [jsinterp] Fix nested attributes and object extraction
  test/test_jsinterp.py
  yt_dlp/jsinterp.py
Labels: bug

#12761 [ie/youtube] Make signature/nsig extraction more robust
  test/test_youtube_signature.py
  yt_dlp/extractor/youtube/_video.py
Labels: site-bug, site:youtube

#12777 [ie/youtube] Fix playlist continuation extraction
  yt_dlp/extractor/youtube/_base.py
Labels: high-priority, site-bug, site:youtube

#12789 Add `--compat-options 2024`
  README.md
  yt_dlp/options.py
Labels: enhancement

#12785 [ie/sbs] Fix subtitles extraction
  yt_dlp/extractor/sbs.py
Labels: site-bug

#12784 [ie/generic] Confirm URL is m3u8 before checking live status
  yt_dlp/extractor/generic.py
Labels: site-bug

#12792 [ie/mlbtv] Fix radio-only extraction
  yt_dlp/extractor/mlb.py
Labels: site-bug

#12788 [ie/stvr] Rename extractor from RTVS to STVR
  yt_dlp/extractor/rtvs.py
Labels: site-bug

#12787 [ie/francaisfacile] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/francaisfacile.py
Labels: site-request

#12799 [ie/MicrosoftLearnEpisode] Fix formats extraction
  yt_dlp/extractor/microsoftembed.py
Labels: site-bug

#12800 [ie/on24] Support `mainEvent` URLs
  yt_dlp/extractor/on24.py
Labels: site-bug

#12767 [ie/youtube] Add `player_js_variant` extractor-arg
  README.md
  yt_dlp/extractor/youtube/_video.py
Labels: site-enhancement, site:youtube

#12802 [cleanup] Misc
  README.md
  yt_dlp/extractor/youtube/_video.py
Labels: docs/meta/cleanup
