Repository yt-dlp/yt-dlp, pull requests merged in 2025-02, with the labels that each got.

#11499 [docs] Improve Issue/PR templates
  .github/ISSUE_TEMPLATE/1_broken_site.yml
  .github/ISSUE_TEMPLATE/2_site_support_request.yml
  .github/ISSUE_TEMPLATE/3_site_feature_request.yml
  .github/ISSUE_TEMPLATE/4_bug_report.yml
  .github/ISSUE_TEMPLATE/5_feature_request.yml
  .github/ISSUE_TEMPLATE/6_question.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE_tmpl/1_broken_site.yml
  .github/ISSUE_TEMPLATE_tmpl/2_site_support_request.yml
  .github/ISSUE_TEMPLATE_tmpl/3_site_feature_request.yml
  .github/ISSUE_TEMPLATE_tmpl/4_bug_report.yml
  .github/ISSUE_TEMPLATE_tmpl/5_feature_request.yml
  .github/ISSUE_TEMPLATE_tmpl/6_question.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  devscripts/make_issue_template.py
Labels: docs/meta/cleanup

#12110 [jsinterp] Add `js_number_to_string`
  test/test_jsinterp.py
  yt_dlp/jsinterp.py
Labels: enhancement

#11972 [downloader/hlsnative] Fix byterange logic
  yt_dlp/downloader/hls.py
Labels: bug

#12256 [ie/generic] Extract `live_status` for DASH manifest URLs
  yt_dlp/extractor/generic.py
Labels: site-enhancement

#12316 [ie/francetv:site] Fix livestream extraction
  yt_dlp/extractor/francetv.py
Labels: site-bug

#9565 [ie/zdf] Extract more metadata
  yt_dlp/extractor/zdf.py
Labels: site-enhancement

#12313 [jsinterp] Improve zeroise
  test/test_jsinterp.py
  test/test_youtube_signature.py
  yt_dlp/jsinterp.py
Labels: enhancement

#12107 [ie/twitter] Fix syndication token generation
  yt_dlp/extractor/twitter.py
Labels: site-enhancement

#12299 [test:download] Validate and sort info dict fields
  test/helper.py
Labels: docs/meta/cleanup

#12332 [misc] Clarify that the issue template cannot be removed
  .github/ISSUE_TEMPLATE/1_broken_site.yml
  .github/ISSUE_TEMPLATE/2_site_support_request.yml
  .github/ISSUE_TEMPLATE/3_site_feature_request.yml
  .github/ISSUE_TEMPLATE/4_bug_report.yml
  .github/ISSUE_TEMPLATE/5_feature_request.yml
  .github/ISSUE_TEMPLATE/6_question.yml
  devscripts/make_issue_template.py
Labels: docs/meta/cleanup, regression

#9902 [ie/Digiview] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/digiview.py
Labels: site-request

#12335 [ie/reddit] Bypass gated subreddit warning
  yt_dlp/extractor/reddit.py
Labels: site-bug

#12403 [ie/3sat] Fix extractor
  yt_dlp/extractor/dreisat.py
  yt_dlp/extractor/zdf.py
Labels: site-bug, regression

#12401 [ie/youtube] nsig hotfix for `tce` player JS
  yt_dlp/extractor/youtube.py
Labels: high-priority, site-bug, site:youtube

#12402 [ie/francetvinfo.fr] Fix extractor
  yt_dlp/extractor/francetv.py
Labels: site-bug

#12404 [ie/gem.cbc.ca] Fix extractors
  yt_dlp/extractor/cbc.py
Labels: site-bug

#12333 [fd/hls] Support `--write-pages` for m3u8 media playlists
  yt_dlp/downloader/hls.py
  yt_dlp/extractor/common.py
  yt_dlp/utils/_utils.py
Labels: enhancement

#12382 [docs] Add note to `supportedsites.md`
  devscripts/make_supportedsites.py
Labels: docs/meta/cleanup

#12238 [cleanup] Misc (for 2025.02.xx release)
  .github/workflows/codeql.yml
  README.md
  devscripts/run_tests.py
  yt_dlp/__init__.py
  yt_dlp/extractor/pbs.py
Labels: docs/meta/cleanup

#12419 [ie/niconico:live] Fix thumbnail extraction
  yt_dlp/extractor/niconico.py
Labels: site-bug, regression

#12420 [ie/soundcloud] Extract tags
  yt_dlp/extractor/soundcloud.py
Labels: site-enhancement

#10649 [core] Support emitting ConEmu progress codes
  yt_dlp/YoutubeDL.py
  yt_dlp/downloader/common.py
  yt_dlp/postprocessor/common.py
  yt_dlp/utils/_utils.py
Labels: enhancement

#12334 [test] Show all differences for `expect_value` and `expect_dict`
  test/helper.py
Labels: docs/meta/cleanup

#11586 [ie/BunnyCDN] Add extractor
  yt_dlp/downloader/__init__.py
  yt_dlp/downloader/bunnycdn.py
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/bunnycdn.py
  yt_dlp/extractor/sovietscloset.py
Labels: site-request

#12431 [ie/wsj] Support impersonation and opinion URLs
  yt_dlp/extractor/wsj.py
Labels: site-bug

#12447 [ie/soundcloud] Fix thumbnail extraction
  yt_dlp/extractor/soundcloud.py
Labels: site-bug

#12445 [ie/tiktok] Improve error handling
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#12397 [ie/instagram:story] Support `--no-playlist`
  yt_dlp/extractor/instagram.py
Labels: site-bug

#12359 [ie/instagram] Add `app_id` extractor-arg
  README.md
  yt_dlp/extractor/instagram.py
Labels: site-bug

#12451 [ie/instagram] Fix extraction of older private posts
  yt_dlp/extractor/instagram.py
Labels: site-bug

#12410 [ie/instagram] Improve error handling
  yt_dlp/extractor/instagram.py
Labels: site-bug

#12452 Fix lazy extractor state (Fix 4445f37a7a66b248dbd8376c43137e6e441f138e)
  yt_dlp/extractor/extractors.py
  yt_dlp/globals.py
Labels: bug, regression

#12318 Fix external downloader availability when using `--ffmpeg-location`
  yt_dlp/downloader/external.py
  yt_dlp/postprocessor/ffmpeg.py
Labels: bug

#12270 [ie/globo] Fix subtitles extraction
  yt_dlp/extractor/globo.py
Labels: site-bug

#12281 [ie/softwhiteunderbelly] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/softwhiteunderbelly.py
Labels: site-request

#12375 [ie/azmedien] Fix extractor
  yt_dlp/extractor/azmedien.py
Labels: site-bug

#12444 [ie/playsuisse] Fix login support
  yt_dlp/extractor/playsuisse.py
Labels: site-bug

#12414 [ie/gem.cbc.ca] Fix login support
  yt_dlp/extractor/cbc.py
Labels: site-bug

#12462 [ie/lbry] Raise appropriate error for non-media files
  yt_dlp/extractor/lbry.py
Labels: site-bug

#12463 [ie/lbry] Make m3u8 format extraction non-fatal
  yt_dlp/extractor/lbry.py
Labels: site-bug

#12442 [ie/niconico] Fix format sorting
  yt_dlp/extractor/niconico.py
Labels: site-bug

#12284 [ie/weibo] Support playlists
  yt_dlp/extractor/weibo.py
Labels: site-enhancement

#12464 [ie/Dailymotion] Improve embed detection
  yt_dlp/extractor/dailymotion.py
Labels: site-bug

#12486 [ie/CultureUnplugged] Extend `_VALID_URL`
  yt_dlp/extractor/cultureunplugged.py
Labels: site-bug

#12483 [ie/youtube] Warn on missing formats due to SSAP
  yt_dlp/extractor/youtube.py
Labels: site-bug, site:youtube
