Repository yt-dlp/yt-dlp, pull requests merged in 2025-05, with the labels that each got.

#13084 [ie/weverse] Fix live extraction
  yt_dlp/extractor/weverse.py
Labels: site-bug

#13079 [ie/youtube] Fix `--live-from-start` support for premieres
  yt_dlp/extractor/youtube/_video.py
Labels: site-bug, site:youtube

#13088 [build] Bump run-on-arch-action to v3
  .github/workflows/build.yml
Labels: docs/meta/cleanup

#13082 [build] Bump PyInstaller to v6.13.0
  .github/workflows/build.yml
  pyproject.toml
Labels: docs/meta/cleanup

#13081 [ie/bitchute] Fix extractor
  yt_dlp/extractor/bitchute.py
Labels: site-bug

#13089 [ie/youtube] Add `web_embedded` client for age-restricted videos
  README.md
  yt_dlp/extractor/youtube/_video.py
Labels: site-enhancement, site:youtube

#13111 [ie/wat.tv] Improve error handling
  yt_dlp/extractor/wat.py
Labels: site-bug

#13104 [ie/nytimesarticle] Fix extraction
  yt_dlp/extractor/nytimes.py
Labels: site-bug

#12957 [ie/SVTPage] Fix extractor
  yt_dlp/extractor/svt.py
Labels: site-bug

#13136 [ie/youtube] Extract `media_type` for all videos
  yt_dlp/extractor/youtube/_clip.py
  yt_dlp/extractor/youtube/_redirect.py
  yt_dlp/extractor/youtube/_video.py
Labels: site-enhancement, site:youtube

#12466 [ie/playsuisse] Improve metadata extraction
  yt_dlp/extractor/playsuisse.py
Labels: site-enhancement

#13045 [ie/niconico:live] Fix extractor
  yt_dlp/extractor/niconico.py
Labels: site-bug

#13147 [ie/amcnetworks] Fix extractor
  yt_dlp/extractor/amcnetworks.py
Labels: site-bug

#13149 [ie/sprout] Remove extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/sprout.py
Labels: docs/meta/cleanup

#12803 [ie/jiosaavn] enhancement: add artist and podcast support
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/jiosaavn.py
Labels: site-enhancement

#12937 [ie/iprima] Fix login support
  yt_dlp/extractor/iprima.py
Labels: site-bug

#13168 [ie/1tv] Fix extractor
  yt_dlp/extractor/firsttv.py
Labels: site-bug

#13164 [ie/once] Remove extractor
  yt_dlp/extractor/espn.py
  yt_dlp/extractor/gamespot.py
  yt_dlp/extractor/once.py
  yt_dlp/extractor/theplatform.py
  yt_dlp/extractor/voxmedia.py
Labels: docs/meta/cleanup

#13120 [ie/nebula] Support `--mark-watched`
  yt_dlp/extractor/nebula.py
Labels: site-enhancement

#13200 [ie/LRTRadio] Fix extractor
  yt_dlp/extractor/lrt.py
Labels: site-bug

#12840 [ie/youtube] Add a PO Token Provider Framework
  README.md
  test/test_YoutubeDL.py
  test/test_networking_utils.py
  test/test_pot/conftest.py
  test/test_pot/test_pot_builtin_memorycache.py
  test/test_pot/test_pot_builtin_utils.py
  test/test_pot/test_pot_builtin_webpospec.py
  test/test_pot/test_pot_director.py
  test/test_pot/test_pot_framework.py
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/youtube/_video.py
  yt_dlp/extractor/youtube/pot/README.md
  yt_dlp/extractor/youtube/pot/__init__.py
  yt_dlp/extractor/youtube/pot/_builtin/__init__.py
  yt_dlp/extractor/youtube/pot/_builtin/memory_cache.py
  yt_dlp/extractor/youtube/pot/_builtin/webpo_cachespec.py
  yt_dlp/extractor/youtube/pot/_director.py
  yt_dlp/extractor/youtube/pot/_provider.py
  yt_dlp/extractor/youtube/pot/_registry.py
  yt_dlp/extractor/youtube/pot/cache.py
  yt_dlp/extractor/youtube/pot/provider.py
  yt_dlp/extractor/youtube/pot/utils.py
  yt_dlp/networking/_curlcffi.py
  yt_dlp/networking/_helper.py
  yt_dlp/networking/_requests.py
  yt_dlp/networking/_urllib.py
  yt_dlp/networking/_websockets.py
  yt_dlp/utils/networking.py
Labels: high-priority, site-enhancement, site:youtube

#13236 [ie/niconico] Fix error handling
  yt_dlp/extractor/niconico.py
Labels: site-bug

#13216 [ie/vimeo:event] Add extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/vimeo.py
Labels: site-enhancement

#13217 [ie/youtube] Fix geo-restriction error handling
  yt_dlp/extractor/youtube/_video.py
Labels: site-bug, site:youtube

#13202 [ie/twitch] Support `--live-from-start`
  yt_dlp/extractor/twitch.py
  yt_dlp/options.py
Labels: site-enhancement

#13245 [ie/xinpianchang] Fix extractor
  yt_dlp/extractor/xinpianchang.py
Labels: site-bug

#13238 [jsinterp] Fix increment/decrement evaluation
  test/test_jsinterp.py
  test/test_youtube_signature.py
  yt_dlp/jsinterp.py
Labels: bug, high-priority

#13234 [ie/youtube] Add PO token support for subtitles
  README.md
  test/test_pot/test_pot_builtin_utils.py
  yt_dlp/extractor/youtube/_base.py
  yt_dlp/extractor/youtube/_video.py
  yt_dlp/extractor/youtube/pot/provider.py
  yt_dlp/extractor/youtube/pot/utils.py
Labels: high-priority, site-bug, site:youtube

#13197 [cookies] Fix Linux desktop environment detection
  test/test_cookies.py
  yt_dlp/cookies.py
Labels: bug, core:cookies

#13166 [cleanup] Misc (for 2025.05.XX release)
  README.md
  yt_dlp/extractor/playsuisse.py
  yt_dlp/extractor/soundcloud.py
  yt_dlp/extractor/twitter.py
  yt_dlp/options.py
Labels: docs/meta/cleanup

#13268 [ie/youtube] Fix automatic captions for some client combinations
  yt_dlp/extractor/youtube/_video.py
Labels: site-bug, regression, site:youtube

#13266 [ie/patreon] Fix m3u8 formats extraction
  yt_dlp/extractor/patreon.py
Labels: site-bug

#13276 [ie/patreon] Fix referer header used for embeds
  yt_dlp/extractor/patreon.py
Labels: site-bug

#13246 [ie/toutiao] Add Extractor
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/toutiao.py
Labels: site-request

#13248 [ie/twitter:broadcast] Support /events/ URLs
  yt_dlp/extractor/twitter.py
Labels: site-enhancement

#13222 [ie/youtube] Fix `--mark-watched` support
  yt_dlp/extractor/youtube/_video.py
Labels: site-bug, site:youtube

#13349 [ie/10play] Fix extractor
  yt_dlp/extractor/tenplay.py
Labels: site-bug

#13284 [ie/weverse] Support login with oauth refresh tokens
  yt_dlp/extractor/weverse.py
Labels: site-bug
