Repository yt-dlp/yt-dlp, pull requests merged in 2025-08, with the labels that each got.

#13240 [ie/niconico] Fix error handling & improve metadata extraction
  yt_dlp/extractor/niconico.py
Labels: site-enhancement

#13908 [ie/RoyaLive] Support `en` URLs
  yt_dlp/extractor/roya.py
Labels: site-enhancement

#13914 [ie/youtube] Add player params to mweb client
  yt_dlp/extractor/youtube/_base.py
Labels: site-bug, site:youtube

#13922 [fd/dash] Re-extract if using --load-info-json with --live-from-start
  yt_dlp/downloader/dash.py
Labels: bug, site:youtube, core:downloader

#13948 [ie/digitalconcerthall] Fix formats extraction
  yt_dlp/extractor/digitalconcerthall.py
Labels: site-bug

#13978 Deprecate `linux_armv7l_exe` support
  yt_dlp/update.py
Labels: docs/meta/cleanup

#13979 [ie/youtube] Update player params
  yt_dlp/extractor/youtube/_base.py
Labels: high-priority, site-bug, site:youtube

#13852 [cleanup] Misc (for 2025.08.XX release)
  CONTRIBUTORS
  README.md
  devscripts/bash-completion.in
  devscripts/changelog_override.json
  pyproject.toml
  setup.cfg
  yt_dlp/YoutubeDL.py
  yt_dlp/extractor/common.py
  yt_dlp/extractor/n1.py
  yt_dlp/options.py
  yt_dlp/update.py
Labels: docs/meta/cleanup

#14012 [ie/weibo] Fix extractors
  yt_dlp/extractor/weibo.py
Labels: site-bug

#13985 [ie] `_rta_search`: Do not assume `age_limit` is `0`
  yt_dlp/extractor/common.py
  yt_dlp/extractor/generic.py
Labels: bug

#14030 [ie/youtube:tab] Fix playlists tab extraction
  yt_dlp/extractor/youtube/_tab.py
Labels: site-bug, site:youtube

#14032 [ie/tiktok:user] Avoid infinite loop during extraction
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#14077 [ie/tiktok:user] Improve infinite loop prevention
  yt_dlp/extractor/tiktok.py
Labels: site-bug

#14052 [ie/mtv] Overhaul extractors
  test/test_subtitles.py
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/bet.py
  yt_dlp/extractor/cmt.py
  yt_dlp/extractor/comedycentral.py
  yt_dlp/extractor/mtv.py
  yt_dlp/extractor/nick.py
  yt_dlp/extractor/southpark.py
  yt_dlp/extractor/spike.py
  yt_dlp/extractor/tvland.py
  yt_dlp/extractor/vh1.py
Labels: site-bug

#14065 [ie/NRKTVEpisode] Fix ID extraction
  yt_dlp/extractor/nrk.py
Labels: site-bug

#14062 SVT sv-forced subtitles for forced subtitles
  yt_dlp/extractor/svt.py
Labels: site-bug

#14038 [ie/BiliBili] Redirect BiliBiliBangumi AV/BV ID to EPID
  yt_dlp/extractor/bilibili.py
Labels: site-bug

#14015 [ie/medialaan] Rework extractors
  yt_dlp/extractor/medialaan.py
  yt_dlp/extractor/vtm.py
Labels: site-bug

#14008 [ie/steam] Fix extractor
  yt_dlp/extractor/steam.py
Labels: site-bug

#13980 [fd] Support `available_at` format field
  yt_dlp/YoutubeDL.py
  yt_dlp/downloader/common.py
  yt_dlp/extractor/common.py
Labels: enhancement, core:downloader, core:extractor

#14082 [ie/francetv:site] Fix extractor
  yt_dlp/extractor/francetv.py
Labels: site-bug

#14003 [build] Add Windows ARM64 builds
  .github/workflows/build.yml
  README.md
  yt_dlp/update.py
Labels: docs/meta/cleanup

#13991 [cleanup] Misc (for 2025.08.20 release)
  Changelog.md
  devscripts/changelog_override.json
Labels: docs/meta/cleanup

#14090 [build] Post-release cleanup
  .github/workflows/build.yml
Labels: docs/meta/cleanup

#14093 [ie/steam] Fix extractors
  yt_dlp/extractor/_extractors.py
  yt_dlp/extractor/steam.py
Labels: site-bug

#14101 [ie/youtube] Update `tv` client config
  yt_dlp/extractor/youtube/_base.py
Labels: site-bug, site:youtube

#13975 [ie/mediaklikk] Fix extractor
  yt_dlp/extractor/mediaklikk.py
Labels: site-bug

#14114 [cookies] Fix `--cookies-from-browser` with Firefox 142+
  yt_dlp/cookies.py
Labels: bug, core:cookies

#14122 [ie/youtube] Improve `tv` client context
  yt_dlp/extractor/youtube/_base.py
Labels: site-bug, site:youtube

#14123 [ie/youtube] Replace `ios` with `tv_simply` in default clients
  README.md
  yt_dlp/extractor/youtube/_base.py
  yt_dlp/extractor/youtube/_video.py
Labels: site-bug, site:youtube

#14169 [ie/youtube] Use alternative `tv` user-agent when authenticated
  yt_dlp/extractor/youtube/_base.py
Labels: site-bug, site:youtube

#14161 [ie/ITVBTCC] Fix extractor
  yt_dlp/extractor/itv.py
Labels: site-bug

#14154 [ie/kick:vod] Support ongoing livestream VODs
  yt_dlp/extractor/kick.py
Labels: site-bug
